#+SETUPFILE: ../org-themes/readtheorg_inline.theme
#+EXPORT_FILE_NAME: ../../static/pages/project_ideas/index.html
#+OPTIONS: broken-links:t

#+TITLE: Project Ideas
A list of shit projects ideas. See [[https://geekodour.org/docs/updates/projects/][projects]] for projects that I am currently working on or were picked up by me in the past.
* Notes
** About this list
- This list is primarily used, viewed and edit from emacs in =org-mode=, I have just exported it for better accessibility so some of the things which are exported might seem out of place.
- I'll pick ideas from this list to work on. So any project idea that I have, will first be here in this list(I use =org-capture= for that). Will do basic brainstorming here and if I feel like it can be built, i'll actually pick it up after setting the correct legends.
- You are free to build on these ideas. I came up with these ideas but I don't think any of these are original or whatever. Feel free to ping me about it if you build on any of these, will make me super happy.
- Legends: =SEED=, =DIED=, =SAPLING=, =GROWING=, =GROWN=, =DIED= .
** Random quotes about side projects
- *Building blocks*
  - A portfolio of small bets.
  - Treat your ideas as cattle, not pets.
  - Build distribution then build whatever you want
  - Don't be a filmmaker that does not make films
- *Opinions*
  - The problems of the world are not my problems but i cannot just ignore them when i possibly can do something about it, even if not, i'll probably just try.
  - I want to make my community and city better and impact the happiness of the people, figure out why they are unhappy and what would make them feel better
  - Far from web 1,web 2 web3, there is a land called small web where small things are built, small inventions are done, math problem are solved, people's lives are made better. Stories are told. People play, there's happiness and joy and ways to navigate sorrows. And it's self healing.
  - want to work on small tools that help people think and take better decisions and keep special focus on ADHD and other disabilities
** Other lists
- [[https://github.com/samsquire/wants][samsquire/wants: A repository of wants]]
- [[https://archive.is/tNzC1][20,000 Startup Ideas]]
- [[https://nintil.com/startup-ideas/][Nintil - Random startup ideas]]
- [[https://silky.github.io/posts/2019-02-22-2018s-crazy-ideas.html][Noon van der Silk - 2018s Crazy Ideas]]
- [[https://github.com/captn3m0/ideas][captn3m0/ideas: Ideas for everyone under a CC licence]]
- [[https://joodaloop.com/idea-lists/][Idea Lists • joodaloop]]
- [[https://github.com/samsquire/ideas][samsquire/ideas: a hundred ideas for computing]]
- [[https://github.com/pel-daniel/mind-bicycles][pel-daniel/mind-bicycles: List of future of programming projects]]
* SEED blog-mentor :webdev:
- A p2p chat for any blog in this world where you can discuss about a certain blog when reading it
- Get a subscription, a mentor will help you absorb the ideas of the blog post clearly through the various mediums Eg. text, voice, video
** References
- [[https://github.com/benzguo/scroll.chat]]
- [[https://www.threaded.live/]]

* SEED brick and mortar institutions :offline:assam:
** Libraries
- Some kind of franchise of offline libraries, make offline libraries cool again
- If not books, we can do something else in these libraries
- Maybe call these places something else
** Museum
- Seeing spaces, computer history museum can be converted into an animal museum at any point of time
** Other shit
- A community place to lock physical goods for a few days. Eg. Phone detox, put phone there for 3 days. You won't get back. Infact you get reward for keeping more valuable things to you there.

* SEED Instagram water plant :fun:offline:hardware:
** Description:
Live Instagram page where a rpi will be:
- watering a plant
- lighting some light/ doing other random stuff
- based on things people do with the account they will be able to do things to the plant, like only fans but for the plant

This can also be a Instagram marketing experiment, while i learn how to run a proper page on Instagram.
See https://twitter.com/grow_slow

* SEED Mechanical Keyboard Painting Company :hardware:
** References:
- https://twitter.com/redditmechbot/status/1222849588194893824

* GROWING GitHub country flags from language colors :webdev:
- Issue: https://github.com/geekodour/experiments/issues/9
- Create a GitHub organization where repo names are country names and the language colors will represent the colors of their flag. If not the exact color, then the nearest color
* SEED Generate a cover photo containing logos of all the known dependencies :webdev:
** Description:
npm/pip/cargo/go cover photo from package.json/go.mod etc

* DIED Creative people opensource marketplace :social:
** Description:
- Basically bringing the idea of opensource to film-making and graphic designing and creative stuff.
- An open source platform where, writers can just publish their scripts and actors can apply to act on it. Then some videographer can offer to work on it, and someone can fund/crowdfunding can happen in the same place.

* SEED Student Job board :social:
** Description:
- A student job board with easy and quick buck gigs for students.
- Specific for students and not for freelancers, i.e not focused on quality of work as such but more on helping the student make some bucks on the side.
- This can also involve pointers to offline works and stories that people have come by. Krishnasish's story is inspiring.

* SEED CommunityHero :social:
** Description:
Finding trusted local communities, communities get funded and mentored, an
umbrella org to help grow offline communities of some specific niches.
** References:
- [[https://docs.google.com/document/d/1q2YoFHSCxd8PPlUIH8j4zUlypUI2mHRNst3svBSPotM/edit][Link to doc.]]
- [[https://drive.google.com/file/d/1WLdmslUR8JH50nQxYJ_mFN8yXHGQkgzM/view][Slide]]

* SEED Assam in Data :assam:social:data:
** Description:
like iip but for assam, talk to ashrish he had something up related to this as well
** References:
- [[https://tradingeconomics.com/india/gdp-growth][India GDP Growth Rate - 2022 Data - 2023 Forecast - 1996-2021 Historical - Chart]]
- [[https://statsofindia.in/][Stats of India | statsofindia.in]]
- [[https://www.reddit.com/r/bangalore/comments/xfinfd/in_the_early_70s_more_than_68_of_bengaluru_was/][In the early 70s, more than 68% of Bengaluru was covered in vegetation. By la...]]
- [[https://news.ycombinator.com/item?id=32902945][I accidentally started a movement – Policing the Police by scraping court dat...]]

* SEED OpenEducationIndia :social:education:
** Description:
Data, stats, reports about everything happening in the Indian education ecosystem
from startups to government policy change to teacher learning programs, links to
other useful places etc.
- Have a link rot check on every page
- live stats of budget distribution
  - Like a funnel
  - you should be able to see what money your college is getting
  - you'll be able to compare the standards that your educational institution should provide v/s what they are actually providing, students will be able to cast vote on something(with proof that something is not being provided)
  - All the research done by pratham and everyone else on improving education in India and writing extensively about it. A curation of all the think tanks to say, not just their names but their ideas.
  - This will be useful as in should emmit metrics that show where we have gaps and which orgs can help and helping them direct shit in the right direction.
** References:
- https://archive.is/qR173

* SEED API first donation platform for NGOs :social:
** Description:
- An API platform for third party applications/websites which they can use to programmatically allow their users to donate to various Indian NGOs
- can be extended to International later on
- Proper tagging and historical data
- Also NGOs can use to add crowdfunding capabilities to their websites
  - Embed Code
  - WordPress Plugin
- So basically the users of this API platform are 3:
  - A: NGOs/Ad Hoc Cause: These will have a dashboard. Can provide embedcode to A so that A can help them.
  - B: People who want to help NGOs/Ad Hoc Cause spead their message. B can promote the embed code provided by A so that C can donate.
  - C: Donators

* SEED A spider crawler to extract all 404/rotten links in GoI sites :social:govt:
** Description:
- A page with stats and a list of all rotted links from GoI sites
- List of govt sites not using https
- uptime checker
- List of govt sites using bad UI/UX -??
- Measure traffic of govt sites
*** Other Ideas:
- Just paste the URL of a website and it'll tell if its legit from the government if in confusion
  - This is required because of there are websites that look very legit and provide info about education but no where they mention that they are not a proper body or anything.
    https://www.indiaeducation.net/portals/
- Idea is that i am not stopping people from creating fakes or anything, that requires lot of thought but legit things are finite and i can save someone some time who is actually looking for legit resources this way
- It will also provide govt site links relevant to the content of that page(related subreddit kind of thing)

* SEED Govt sites in plain english like AWS in plain english :govt:social:
** Description:
This can also involve:
- Standard Naming Scheme for all govt orgs and then organize them in a hierarchy or whatever data structure is preferable. Build a proper hierarchy on my side based on how this should be and then link up the actual websites from there.
- Also make visualization of how everything works and is uptodate, because what students study in books in school are not uptodate.
  - I feel like there should be dynamic information board for this available to the public, one should not be reading the newspaper everyday to be updated on these things.
  - It's like someone has to verify the source of truth and also needs to verify that the source is upto date.
** References:
- https://expeditedsecurity.com/aws-in-plain-english/

* SEED Crowdfunded Textbook Helper :education:
** Description:
- students/kind knowledgeable adults help improve parts of textbook and add annotations related the recent things.
- Eg. one paragraph in a textbook can have obsolete info, someone adds better description, a current development section, the formula behind section etc.
  - I.e you can put down the ISBN of the book and you'll have a list of annotations done to it by different people
- Strict policy of no linking, the student must not get away from the book and go down some rabbit hole. Rabbit hole has its own place, but not when a student is studying for some exam.
- We can also instinctivise the volunteer by showing how many school kids will be impacted by their help when they improve the content of the text
** References:
- https://web.hypothes.is/start/

* SEED YT book recommendation ext. :webdev:fun:browser_ext:
** Description:
The browser extension that recommends books based on YouTube video you are watchin

* SEED Local Learning :education:social:
** Description:
- Today people are learning things from a plethora of online resources
- user updates the learning list whenever they are learning from some new course or anything.
- It shows possible people you can meet up and learn these things together locally because you are geographically close and are learning the same thing on the internet. You should be friends.
- It's like bumble for people learning the same things.

* SEED Landing Page Annotation :webdev:
** Description:
- Landing page annotations for getting feedback on the homepage. It's like fermatslibrary but for the landing page. (For feedback on landing pages)
- Some guy on twitter was like I have this landing page, please provide feedback on it. It'll be nice to have a tool altogether which allows people to leave annotations on your webpage. and then you can act upon it.
- +1 or some points to you if your suggestion is accepted

* DIED Smell Transmission :fun:
** Description:
Make a device to transmit smell (fragrance) over the network.

* SEED Educational Video Copyright :education:
** Description:
- Special rights to videos made for educational purposes, eg. direct ways to donate to the creator etc.
- Also the video will come with video source(PremerPro files etc) files if someone wants to do language voice translations of the video they can.
- Some kind of meta format to follow for educational videos, some kind of specification.

* SEED Archival App :notetaking:
** Description:
- I have a certain way how i bookmark tweets, I want a easily searchable, offline version of twitter bookmarks. Maybe my self hosted version of archive.is will solve this but this is something that I want.
- I do not want to perform more than one action, just one action whether on phone or laptop just to say that I would probably want to come back to this tweet later. Save it for me. That's it.
- A backup archival tool dead simple where you
  - bookmark a git repo
    - syncs a git repo daily + private repos with ur github key
  - bookmark tweet, save tweet
  - webpage
  - by default these bookmarks will be private with the ability to make them public.

* DIED Village location locator :social:
** Description:
many people in villages don't have a proper address to tell, they can use 3word address lat/lang
** References:
- https://github.com/google/open-location-code

* DIED Visual helper for I and l :browser_ext:
** Description:
Color I and l differently when extension button is toggled. (Uppercase i and Lowercase L)

This possibly is one of the shittiest ideas but just keeping it as part of the migration.

* SEED Streaming news format :social:
** Description:
- There is one time news and there are news that are in stream. We DO NOT have a format for streaming news.
- You might say social media feeds are a form of streaming news but it lacks to show connections between previous news. It's basically one time news sent in the same channel, that's not streaming. you can't apply one operation on them and get some insights, whereas you could do it for a stream.
- If we plan to crowdsource the stream, it has to be done is a common format of some sort.
- Eg. the oil leak in Dibrugarh is happening for 9 days now, where is the info? we can read the news but where is the data where is the truth, what's going on, what steps are taken. There is a need of some kind of streaming news format.
- See [[https://hapgood.us/2015/10/17/the-garden-and-the-stream-a-technopastoral/amp/][The Garden and the Stream: A Technopastoral – Hapgood]]

* SEED Social Runbooks :social:
** Description:
- documents stating on how we can improve anything in any kind of society, also have some measurement unit of what level the city/community is currently performing.
- For eg. 10 years ago the blind community in some city in Australia was suffering from the same issues that at present time Guwahati the blind community is suffering. If we have some measurement unit, then we can exactly see how close guwahati's situation is to australias situation. how that specific measurement was improved over time and see if we can use some of the things they applied.
- Basically have a runbook for any kind of society in any part of the world to solve social problems.
- But more importantly human to human communication is very important, not just understanding of the language but also understanding of humor what is appropriate and what is not etc. Some fixes can be applied to american people, those cannot never be directly applied here.
- Each city/place would have their own run-books and there will be one place where we can see all make all kinds of comparision and analysis
** References:
- [[https://www.cortex.io/post/keep-calm-and-use-the-runbook][“Keep calm and use the runbook” – Why runbooks are the key to handling any si...]]

* SEED Torrent Overlay Organizer :p2p:
** Description:
i was just thinking if there is some way to organize preexisting torrent files. eg. the
distributed2020 videos are distributed as separate torrent files. Is there anyway to
build a meta torrent file, that would define a directory structure where its sub torrents
should be downloaded to. When the torrent client uses that meta torrent files it uses
the trackers and everything of the individual torrent files but self organizes itself
based on the directory structure defined by the meta torrent file.

* SEED Bad Drawings :fun:
** Description:
Bad drawings of gali characters(sudirbhai, mokkel etc) and of computer scientists

* SEED Installed Packages Info page generator :notetaking:
** Description:
*** Offline
This has to be some kind of binary that has some inbuilt db, where i can merge and do crud operations on my listpackages alias for pacman. Things that i want:
- There are so many useful utils like lsof, nslookup but i often forget where they are useful etc. whenever i come across such a tool i can simply make a note of it here. Current listpackages lacks adding of os specific tooling that probably is already existing. I am not even sure if this will be the right way or we need some other tool. Maybe want to keep it small.
- It should be able to automatically generate: https://wiki.itdobelikethat.org/docs/tools/laptop_tools for me.
- Currently I can use the package manager to list installed things(explicitly/implicitly) but sometimes I just want to tag a set of programs(say games as games)
*** Online
Make some app where i can keep track of online tools that i use.🌟
** References:
- man69 is dead

* DIED Indian baby names generator :fun:
** Description:
Do it the fucking right way, ai, graphics and everything. Indian baby names should give top result. The current top result is a blogpost. This is more of a SEO exercise. Will have to hire writers to write top quality blogposts on babies etc.
** References:
- [[https://www.pupnames.com/dog-name/wiggles][Wiggles 🐶 - Dog Name Meaning & Popularity | PupNames.com™]] This but 100x more cute. I really like the taxonomy.
- [[https://mixedname.com/][Bilingual baby name finder]]

* SEED Government Hall of Shame/Fame :social:govt:
** Description:
A hall of fame and shame for things govt is doing. Can be location specific and aggregated upwards.
** References:
- https://www.deceptive.design/hall-of-shame/all
  - See the reading list as[[https://github.com/jnv/lists][GitHub - jnv/lists: The definitive list of lists (of lists) curated on GitHub...]] well[[https://github.com/jnv/lists][GitHub - jnv/lists: The definitive list of lists (of lists) curated on GitHub...]]

* SEED 1000% Duck :fun:
** Description:
make a website that just goes on from -10% to 100000000% duck memes. it'll have the memes from YT curated in one page.
[pcduck.xyz](http://pcduck.xyz) or something
** References:
- [[https://www.youtube.com/watch?v=Hh6_xfw8vEI]]

* SEED YourStacks/Stackshare inspired copy the entire thing model :webdev:
** Description:
- Like you'll have set of stacks that you can directly copy to start your business form existing business and u can mix and match the cost. It's like the octa trading app thing but for business/startup stack.
- This will also show pricing comparision of different stacks along with pros and cons
** References:
- [[https://news.ycombinator.com/item?id=28327660][Launch HN: Hotswap (YC S21) – Easily migrate customers away from competitors]]
- [[https://github.com/cjbarber/ToolsOfTheTrade][GitHub - cjbarber/ToolsOfTheTrade: Tools of The Trade, from Hacker News.]]
- [[https://github.com/255kb/stack-on-a-budget][GitHub - 255kb/stack-on-a-budget: A collection of services with great free ti...]]
- [[https://github.com/ripienaar/free-for-dev][GitHub - ripienaar/free-for-dev: A list of SaaS, PaaS and IaaS offerings that...]]
- [[https://www.sideprojectstack.com/showcases][Showcased companies and how their are build with no-code.]]

* SEED Wholesale store curation for merch :ecomm:
** Description:
- Indiamart but smaller and with more quality and proper reviews etc.
** References:
- helloabound

* SEED Dynamic catalog for public homechefs/builders/artisians :ecomm:social:assam:
** Description:
- For people who want to be discovered.
- Locality specific
- some algo to expose new interesting chefs etc.
- A similar idea to curate small shops like the leafy affair, cats co in etc in a nice place where new pages can come and we can add sponsors and everything also have a newsletter about it  etc.
** Reference:
- https://ihatchchile.com/
- Nilesh Mishra on Twitter

* SEED City Guides :social:
** Description:
- A blog on bachelor's guide to moving cities, needs, moving services etc number, other lesser known services, activity recommendation etc. Lot of these if i don't know i can just get by making legit post on city subreddits.
- Also city wise scam list. Behavior of drivers, what to do when someone misbehaves etc.
- best food joints
- work spots, places in the city where they can go work from. sometimes these places are not restaurants but some other hidden places. Sometimes the stadium can be an amazing place to work from. Can be a fun community. (laptop friendly cafes etc)
- every city needs to find what communication medium is best for its citizen. This is not only useful for the new people in the city but also for existing people in the city.
- docs about how to buy local chicken, what are health benefits of local vs broiler chicken.
- Market price with graph and everything. See turninp prices reference.
** References:
- [[https://lbb.in/bangalore/][Guide To Shopping, Where To Eat & Things To Do In Bangalore | LBB]]
- [[https://github.com/mikebryant/ac-nh-turnip-prices][GitHub - mikebryant/ac-nh-turnip-prices: Price calculator/predictor for Turni...]]
- [[https://news.ycombinator.com/item?id=39484685][Show HN: Little Fixes – a spatial forum to improve your city | Hacker News]]
- [[https://github.com/atxdevops/dodatx-food][GitHub - atxdevops/dodatx-food: food and restaurants in ATX]] Great format for food
- [[https://www.lesswrong.com/posts/WzPJRNYWhMXQTEj69/a-map-of-bay-area-memespace][A map of Bay Area memespace - LessWrong]] 🌟
- [[https://en.wikipedia.org/wiki/LocalWiki][LocalWiki - Wikipedia]]
- [[https://allaboutberlin.com/][All About Berlin]]
- https://github.com/blr-today (nemo)

* SEED A fight ring generator :fun:
** Description:
- Background from various different games, movie scenes, iconic fight scenes etc.
- The face in the characters can be replaced with faces we upload.
- I wanted to see muhamad ali and khali fight.
- Later can convert into video thing if required.
** References:
- [[https://deathgenerator.com/]]

* SEED Subscription service for gift to self :social:
** Description:
- There are so many undiscovered joys of life, this is a subscription service where people give their address and pay a small minimal fee and they get gifts every month from the mayraid of instagram shops where they promote their products directly to these people as gifts.
- They can select shops/categories from which they want to recieve gifts from we need to iterate on the business model.
** References:
- https://github.com/jacobian/notamazon
- Study the gifting market in india, learn how to scrape amazon to gain insights, why things like incredibuilds are not popular in india.
** Actions:
- we need to start on this by july because the yearly festivals start after august

* DIED Career trajectory of politicians :social:fun:
** Description:
This is important public information because public needs to know who are the people that are electing them.
eg. how many actors became politicians etc etc.

* SEED Directory of houses from movies :fun:
Directory of houses in movies and series/animie etc.
- Also can extend to houses/places, i personally want this because sort of makes a city more interesting that way. You get new ways to connect to a city because you watched some movie but now you know
- Like useful from inspiration point of view and set design point of view.
- A set design student will love this. Eg. Houses in drangon ball z, houses in lord of the rings etc. Nerdy info about it, /r/moviedetails /e/screengrabs
- See [[https://news.ycombinator.com/item?id=37902350][Hong Kong Locations in Ghost in the Shell | Hacker News]]

* SEED Legit Guides 🌟 :social:
** Description:
*** Priors
- A public directory for maintaining list of things.
- eg. wikipedia but wikipedia is for maintaining lot of info, github is there but it's too technical
- we need something just to maintain public lists, that's easily editable, updatable etc.
- accessible in print format and what not.
*** Theory
- teachyourselfcs type website for things like:
  - history of india/assam
  - caste system in india
  - Indian home remedies that actually work and why they work, references
  - learn about bangalore
  - starting up in guwahati what are the requirements
  - Guide to what instutions their kids can go to?
    - Parents should have proper idea about what are the options are their children. This should be provided to them.
    - he did not have to come to me to ask those questions about how to handle his kid, like he can but everyone should be aware of the "bible reference" whatever it might be. Govt should provide the full catalogue.
    - The vocabulary should be understandable. People don't have to be smart to chose the best for their children.
    - It's our collective responsibility as adults to provide information to all about how we can shape the best for our children.
- The "like" sort of have these meta properties:
  - basically social questions
  - things that refer to exact people, resources
  - These are not actual content but proper references and description of the reference and why the reference is good, what is the entire spectrum and where exactly does the reference fit in. Pretty meta.
  - list of questions that raises curiosity
  - Most of this knowledge is usually passed by parents to their childerens or by friends to friends but for some of us with broken families and friends who don't share too much, these kind of guides really help. Eg. How to file taxes, what does filing tax actually mean etc. Which kind of govertment needs taxes etc. Basically this will make our community more aware of the things that is going on.
  - Not everyone wants to read but the ones that want to, information should be easily available to them.
*** Practical
- More practical guides
  - proper manuals about how to transition your offline shop to online (location specific), not only about vendors but also mentioning what kind of new vendors are emerging. Also include case studies etc.
  - Guide on how to setup your online store in {location}
  - A directory about how different government and organizations are operating. i.e how to run your own government
    - how are bus managed in different cities, what tools do they use, what is the cost of operation etc. public directory of these things.
  - how to start a school in india
  - how to start your farm in india (location specific)
  - house rules list : different house rules that i like, practice myself or heard from fiends
  - community activity list : list of things we can do as a community for whatever reasons
  - what laptop should i buy (what battery is good, what is bad, what kind of display are available which is good for me)
** References:
- [[https://en.wikipedia.org/wiki/Anthology_series][Anthology series - Wikipedia]]
- [[https://news.ycombinator.com/item?id=38772382][Show HN: Whataaabout.com – unique activity ideas for the holiday break | Hacker News]]
- [[https://ooh.directory/][ooh.directory]]
- https://listium.com/explore/religion-and-spirituality
- https://www.ranker.com/
- [[https://twitter.com/shireenazam/status/1425102084605726728]]
- https://github.com/jnv/lists
- [[https://teachyourselfcs.com/][Teach Yourself Computer Science]]
- [[https://news.ycombinator.com/item?id=33252556][Comprehensive list of FPGA development boards | Hacker News]]
- See [[https://github.com/ustaxes/UsTaxes][GitHub - ustaxes/UsTaxes: Tax filing web application]] How to file taxes

* SEED Foone like generator but assamese :assam:fun:
** Description:
Do like foone but for arts from Assamese books
** References:
- [[https://deathgenerator.com][The Death Generator]]

* SEED Forks of Assamese stories :assam:bot:fun:
** Description:
- Publicly available forks of Assamese stories, poems etc in different languages(english).
- Sections posting twitter bots, generated images for instagram pages etc.
** References:
- [[https://twitter.com/FrogandToadbot]]

* SEED Crowdsourced Dataset Collective :social:assam:
** Description:
- A crowdsourced catalog of research/dataset request can be submitted by citizens/robots
- humans or robots can then try to fulfill the request of such research and earn points.
- Eg. Debanga wants number of house for sale in Guwahati and their prices. Vishal does the research and submits publicly, he gets the prize publicly.
  - how many trackers are there in guwahati, in narengi, how is their daily life like. what do they want what do they need etc.
  - what is the life in guwahati prison like, what books do they read
- This will promote research among citizens as they also get incentive to work.
- I am not sure why i included robots here, but it had that in the original idea so keeping it here
** References:
- [[https://mena.yougov.com/en/about/][YouGov | About YouGov]]
* SEED Movie release bot :bot:
** Description:
Movie release bot. Everyday some movie was released, this bot will pick movie poster and post on that day. Bonus post better lines out of the movie etc.

* SEED Self awareness at the community :social:
** Description:
- Figure out a way to understand as an individual or as a family where do we stand in different spectrum.
  - World spectrum, Financial spectrum, smartness spectrum, happiness spectrum etc.
  - So this way even in a globalized system where we are living locally and all around the world at the same time we can put the stats we know about us and see where we actually stand. And that's it.
  - This is not going to help you get better or worse, this will just tell you where you stand based on some calculation and data collection.
  - Interesting thing here is that it should show this in different levels, such as local. Eg. How wealthy are you in narengi, then how wealthy are you in guwahati, then assam, then india and so on.
** References:
- [[https://news.ycombinator.com/item?id=30708217][What is my place in the world population? | Hacker News]]
- See [[*Benifit Calculator][Benifit Calculator]]

* SEED USSD Directory :social:
** Description:
- a directory of everything we can get using ussd, like ur own phone number etc. Also what is ussd etc.
- Same for UPI, there are other hidden interfaces our phones are capable of, it's not just the apps.
** References:
#+begin_quote
We curate the most comprehensive list of bank and mobile money USSD codes that are available in Africa. Here you’ll find USSD codes, their appropriate descriptions, as well as tips, news and insights about how USSD is used in Africa for transactions & financial inclusion products.
- [[https://ussd.directory/][USSD Codes in Africa]]
#+end_quote
** Questions:
- Do simless phones have ussd?
* SEED Proxy Business Address :social:
** Description:
people are running business from their homes. So something like a proxy office address they can share publicly and not get doxxed.

* SEED AirportLuggageBuddy :social:
** Description:
Airport luggage buddy finder, find someone to carry your 3kgs in the airport in the same flight so that you don't have to pay extra. Pay the person some money, make new friends. Since it'll be hard to sell this thing to customer, what you can do is build the infrastructure and code and everything, perfect everything. API and all, and then sell this to PayTM later because most people in india use PayTM.

* SEED Home planning, not house planning :social:
** Description:
- Help people build better homes in different aspects
- Build something that debangas khura can come to and improve his family’s living. The common saying that, nobody is going to come and save you, does not have to be true. Build an army who will try to solve people problems and help them live a better life.
- build things, like houses and all but source these things from village areas, like spend time in those village and all understand the usecases of things that are abundant only in those places and then source it to build whatever you're building. basically use earth to build what you want to build. earth is giving things to you for free.
- Make therapy, family plans etc affordable, not only therapy but family planning, financial planning etc. Basically pay some money to understand where you stand etc.
- basically build a team which can pick one family unit and transform their life in every way
  - financial planning
  - house planning (this things can go in the guides)
  - other things and make a tv show out of it. or maybe not, maybe make it a generally available service.
** References:
- [[https://www.youtube.com/channel/UCnFxFSv7_31uPDqaxtghyaQ][A Mere Creator - YouTube]]
-[[https://www.youtube.com/channel/UCwhBJNZYmbx54v8v1Cb80WA][ Primitive Survival Skills - YouTube]]
-[[https://www.youtube.com/channel/UC_zQ777U6YTyatP3P1wi3xw][ NEVER TOO SMALL - YouTube]]

* SEED learxinymnutes for careers :education:
** Description:
- A start with x career types page https://learnxinyminutes.com/ eg. design:
  - what laptop should i buy
  - i see these people telling me to do design school, i see these people telling me to work on myself
  - i see these different roadmaps, which one to follow??
  - i see these sites which are curating roadmaps which worked for other people what to do.
  - there are these new fields and buzzwords i am hearing is it relevant now
  - what will happen if economy collapse
  - So a proper unbiased overview of things in the industry
- People can also request for shit and update shit, but this is NOT a roadmap

* SEED Word of the day :assam:bot:
** Description:
We can make a podcast of interesting assamese words and their origins
** References:
-[[https://podcasts.apple.com/us/podcast/merriam-websters-word-of-the-day/id164829166][‎Merriam-Webster's Word of the Day on Apple Podcasts]]

* SEED Indian Food Breakdown :social:
** Description:
Breakdown of common house hold items, what shit does it contain, how to read the ingredients list

** References:
- [[https://fillyourplate.org/blog/the-truth-about-nutella/][The Truth About Nutella - Fill Your Plate Blog]]
- [[https://news.ycombinator.com/item?id=40777601][Ask HN: Cooking book/resource, expressed in terms of (Bio)Chemistry? | Hacker News]]
- Masala Lab book

* SEED Benifit Calculator :social:
** Description:
- Realtime positioning of a person culturally and geographically.
- Eg. I am a person who’s hindu, making such and such income, living in Narengi Tiniali India. Based on these details one should be able to list/see all the benifits and rights that the person has.
** References:
- See [[*Self awareness at the community][Self awareness at the community]]

* SEED YT channel - Generated music :bot:
** Description:
YouTube channel of generated music. Machine learning for fun.

* SEED MathDoesNotAddUp :social:assam:fun:
** Description:
A satire website that debunks common myths/fallacies by *locality*, eg. charge new device once you have it in home after purchase
** References:
- [[http://n-gate.com/][n-gate.com. we can't both be right.]]

* SEED GithubStars Explorer :notetaking:tool:
** Description:
I have a repo digging habit, it honestly gives me pleasures and ideas of all kinds. I like to do it but doing it from the github interface is very tedious and time consuming.
- Github stars page shows limited number of things in it and the operation and info about those things are not quite there.
- Page is bulky, All i want is to go through a list see the description, see the readme, see when it was last updated etc. and then i decide whether i want to use it, take a look at it, tag it with something etc.

I want a tool that will basically make my repo digging habit easier:
- can preferch readmes as user usually would iterate one by one.
- Can either be a TUI or a web ui.
- Ability to do union of different github accounts
- keep track of what library user already looked at in the past
  - so that user can easily hide them when looking at a new set of repos

* SEED Scale Analogy :fun:webdev:
** Description:
- When we say 10mn, what does that mean? you can buy 1 honda city
- When you say 30mts that's the length of some popular statue.
- When you say 400kg, that's the weight of a maruti suzuki etc etc.
- Inputs can be multiple SI units and the analoges can be infinite[[https://javier.xyz/pokemon-to-scale/][Pokémon to Scale]] ;)
** References:
- [[https://javier.xyz/pokemon-to-scale/][Pokémon to Scale]]
- https://www.visualcapitalist.com/visualizing-the-speed-of-light-fast-but-slow/
- https://joshworth.com/dev/pixelspace/pixelspace_solarsystem.html
- [[https://github.com/javierbyte/emoji-to-scale][GitHub - javierbyte/emoji-to-scale: Your favorite emojis. To scale.]]
- [[https://humanclock.com/][The Human Clock™:]]
- [[https://www.dimensions.com/][Dimensions | Database of Dimensioned Drawings]] by Bryan Maddock
- [[https://www.ignboards.com/threads/have-you-encountered-the-useless-converter-bot-on-reddit.455969031/][Have you encountered the useless-converter-bot on reddit? | IGN Boards]]

* SAPLING Small network CLI apps :tool:bot:fun:
- Issue: https://github.com/geekodour/experiments/issues/22
- I will host a ton of these apis so need some kind of a framework for these.
** References:
- [[https://rate.sx/][rate.sx]]
- [[https://plaintextsports.com/][Plain Text Sports]] : I really love this, i want a news version of this for local news
- [[https://news.ycombinator.com/item?id=35313232][Text only news websites | Hacker News]]
- [[https://github.com/chubin/awesome-console-services][GitHub - chubin/awesome-console-services: A curated list of awesome console s...]]
- [[https://github.com/dariusk/corpora][GitHub - dariusk/corpora: A collection of small corpuses of interesting data ...]]
- [[https://botwiki.org/][Welcome to Botwiki | Botwiki]]

* SEED Deadline/Schedule Listings :notetaking:fun:social:tool:
** Description:
- deadlines for different things like exams, university applications, etc,
- Basically awesome list but for deadlines, like there are niche of everything music, drummers, programmers. Like a holiday listing for different niches.
** References:
- [[https://github.com/johnelliott/tdays][GitHub - johnelliott/tdays: get days since Trump was elected 😒]]
- [[https://github.com/paperswithcode/ai-deadlines][GitHub - paperswithcode/ai-deadlines: AI conference deadline countdowns]]

* SEED Data Analysis Poster :fun:data:
** Description:
Different beautiful posters of data, like the bgp poster of graph of every month etc.
** References:
- [[https://www.reddit.com/r/dataisbeautiful/][DataIsBeautiful]]
- [[https://www.behance.net/gallery/31058715/THE-BIGGEST-METEORITES-FALLEN-ON-HEARTH-Corriere][THE BIGGEST METEORITES FALLEN ON HEARTH - Corriere on Behance]]

* DIED Print kiosk :fun:assam:offline:
** Description:
kiosk where people can just send shit over and the later on collect it

* DIED 1Hour Photo Delivery :fun:assam:offline:
** Description:
- Flow
  - Send us the photo you want to be printed
  - Select quality, select paper, select any effect, call for any extra info
  - Select frame if required
  - Get photo delivered in less than 1 hour.
- Great for birthday party gifts.

* SEED Cycling Track Suggestion :fun:offline:assam:
** Description:
cycle track suggestion in and around guwahati, solve riddles on the track and get coupons.

* SEED Random Bot ideas :bot:
** Description:
- Interesting lines from song lyrics, song lyrics bot.
- I want a bot like this for every social media i use. Name change, bio change etc. Maybe make this publicly accessible.
  - So basically a meta monitoring agent for all my social media streams. Whenever something public(editable) like display name or whatever is changed it'll make a record update it publicly using tw or something. This can additionally post monthly usage summary of different social media. What were the rate changes and everything.
    - [[https://mobile.twitter.com/nahimname][This tw bot for example, i hope it lives]]

* DIED Bring back offline dating w consent! :offline:
** Description:
- it's a pretty pretty shitty idea
- when people are in restaurants, there are a lot of single ppl. so there should be something that verifies that they infact are in that place and then anonymously talk to other people who are in the same place and then talk to them and share other things then talk directly in person. the fastest dating app.

* SEED Scan Library :fun:data:experiment:
** Description:
Scan/3D scan usual things and present total anatomy of it. Like journey of a pencil for new things every month or so.
** References:
- [[https://www.scanofthemonth.com/scans][Explore the world within in our library of monthly scans.]]
- [[https://storymaps.arcgis.com/stories/c6457a1559b5472882a3d6870a93c7a5][Journey of a Pencil]]

* SEED ML app to replace ball in football screenshots with cats :fun:
** Description:
das it. or if not ML then do it manually as a hobby activity.

* SEED Build an org that spreads humor :offline:fun:assam:
** Description:
- Build a org that celebrates these various days in a humerous fashion. (we can make a list of days we want to celebrate)
- Wholesome graffiti all around assam,  eg. Go call your mom etc. Nilim Mahanta FTW.
- Put crazy signboards/billboards around and outside the city
** References:
Eg. On international jokes day: I got my daughter a fridge for her birthday, can't wait to see her face light up when she opens it.

* SEED HN Scripts :tool:webdev:fun:
** Description:
Something similar to Microsoft activation scripts where users can submit their own script to do something custom on the HN homepage or with the HN api on a daily basis.

Eg. 1. List all users in the homepage by karma
Eg. 2. List all HN users and their twitter profile side by side
Eg. 3. List the top N Ask HN posts this month.
** References:
- [[https://news.ycombinator.com/item?id=34110624][Show HN: Search HN Favorites or Export to CSV]]

* GROWN Sell 2023 Calendars :ecomm:
See daily.threesixfive.shop
** Description:
Sell 2023 calendar based on fandom of different things.

* SEED Subscription based Donation :social:ecomm:experiment:
** Description:
- I don't have the energy to re-write this now, need white board and will come back from it later.
- Collect x money from people for n days.
  - Split that money into 1 day
    - Use that money for donation.
- We only allow for micro donations
- COPY PASTE :
  - One rupee per day lucky draw entry, (can be crypto/inr upi payments)
  - so basically the idea is people contribute one rupee from their day or like 30 rupees per month and like that contribution of everyday will come towards the total that happens around 9:00 p.m. in the night and and in the 9:00 p.m.
  - what will happen is there will be a lucky drop and there will be a winner
  - so for every day there will be a limit how much a single person can win
    - if the amount that was collected from everyone for that day was less than the max amount  then the single person would win
    - otherwise there will be the amount will be split into whatever the number of people we want to distribute the amount
    - so like those people will be getting that money back so yeah it's like a 1 rupees entry to a lucky draw to infinite amount so basically the larger the network is the more people can make money out of it
    - the interesting thing about this is the investment is very very small 30 rupees per month and you could like you are entering a lucky draw that could give you so much and I guess it's a good incentive in a way.
  - crowdsourced list of things about what to do with the collected monie. see what good impacts 30rs per month is making.
** References:
- [[https://www.cbsnews.com/news/state-lotteries-transfer-wealth-out-of-needy-communities/][State lotteries transfer wealth out of needy communities]]

* DIED Protest Organizer/Crowd Gatherer :assam:offline:
** Description:
A website to help people organize protests

* SEED Event Crowdfunding :assam:social:offline:
** Description:
- We need people to fund local events, we need a trusted and authorized place to raise funds for local events. There should be a funding goals etc. Short term funds for short term events.
- In different places there is a requirement of different kind of knowledge distribution. So suppose there is a need of financial literacy in narangi so what someone can do is hey I can do a financial literacy workshop for 50 people but for that I will need 2,000 rupees then the person can put that thing somewhere and people around the world can fund that workshop with 2,000 rupees and once that is collected the person can directly contact the workshop so this way independently in a distributed manner without any centralized authority mandating the thing the whole thing can be done.
** References:
- [[https://archive.is/m8YhI][FreePizza.io]]
- [[https://hackclub.com/bank/][Bank – Hack Club]]
- [[https://opencollective.com/][Open Collective - Make your community sustainable. Collect and spend money]]

* SEED Night school :education:assam:social:
** Description:
Start a night school in the city, i have not thought what will be taught but I plan to start with family planning and life management

* SEED Assamese Software collective :assam:social:
** Description:
Software collective engaged in development, localization, standardization and popularization of various Free and Open Source Software in Assamese
** References:
- [[https://smc.org.in/][Swathanthra Malayalam Computing | സ്വതന്ത്ര മലയാളം കമ്പ്യൂട്ടിങ്ങ്]]
- [[https://github.com/hridaydutta123/Assamese2Vec][GitHub - hridaydutta123/Assamese2Vec: Assamese2Vec is an open source project ...]]
- [[https://github.com/varnamproject/govarnam][GitHub - varnamproject/govarnam: Easily Type Indian Languages on computer and...]]
- [[https://github.com/malaikannan/TamilSpellChecker][GitHub - malaikannan/TamilSpellChecker]]
- [[https://indic.page/][Code / Indic (Indian) language computing projects and resources]]
- [[https://github.com/knadh/dictmaker][GitHub - knadh/dictmaker: A stand-alone web server app for rapidly building a...]]
- [[https://github.com/andrewgodwin/uk-usa-dictionary][GitHub - andrewgodwin/uk-usa-dictionary: A UK-USA dictionary of common terms,...]]

* SEED Assamese translator, insult generator :fun:assam:
** References:
- [[https://pirate.monkeyness.com/insult][Pirate Monkeyness Insults and Translations]]
- [[https://github.com/surge-ai/profanity][GitHub - surge-ai/profanity: The world's largest profanity list.]]

* SEED Assamese things Archival :assam:offline:bot:tool:education:social:data:
** Description:
- Assamese movies screenplay archives, all old movies/new movies etc.
- Index of Assamese songs and connections of artists and places.  Song metadata.
- Poster archive.
- A bot to post it to the subreddit and twitter account aswell.
** References:
- [[https://xahitya.org/][home - সাহিত্য ডট অৰ্গ]]
- [[https://indiangigposterarchive.tumblr.com/][Indian Gig Poster Archive]]
- [[https://www.zonicweb.net/badalbmcvrs/index.htm][Museum of bad album covers: the worst album covers ever!]]
- [[https://simonsarris.com/art-collections][High Quality Collections of Digitized Art and Archival Finds | simon sarris]]
- [[https://kindofbloop.com/][Kind of Bloop: An 8-Bit Tribute to Miles Davis' Kind of Blue]]
- [[https://www.si.edu/search?edan_q=charles%2Bcourtney%2Bcurran&][Search | Smithsonian Institution]]
- [[https://digitalcollections.nypl.org/search/index?utf8=%E2%9C%93&keywords=Charles+Courtney+Curran][Search results - "Charles Courtney Curran" - NYPL Digital Collections]]
- [[https://www.artic.edu/artists/5703/charles-courtney-curran][Charles Courtney Curran | The Art Institute of Chicago]]
- [[https://www.nga.gov/collection-search-result.html?keyword=lamp][Collection Search Results]]
- [[https://github.com/adactio/TheSession-data][GitHub - adactio/TheSession-data: Data dumps from thesession.org]]  Irish traditional music

* SEED Local radio station :assam:
** Description:
Radio is a medium that's not used as much but i find it cool as heck. I want to start a pirate radio station where the old spirit of radio is revived and radio is made cool again. INCLUSIVE of all people.
** References:
- [[https://github.com/norns-study-group/pirate-radio][GitHub - norns-study-group/pirate-radio: norns pirate radio: explore, listen,...]]
- [[https://news.ycombinator.com/item?id=33608892][Show HN: Campus FM – live stream college and independent radio stations | Hac...]]

* SEED Crowdsourced Information for Guwahati/Assam :assam:social:data:govt:
** Description:
- AssamPolice Twitter is pretty active, I think it can make use of crowdsourced opinions.
** References:
- [[https://github.com/mysociety/alaveteli][GitHub - mysociety/alaveteli: Provide a Freedom of Information request system...]]
- [[https://www.whatdotheyknow.com/][WhatDoTheyKnow - Make and browse Freedom of Information (FOI) requests]]
- [[https://archive.is/Q6FDZ][RateOurCops: Public reviews of police officers and agencies]]
- [[https://www.lobbyfacts.eu/][Search | lobbyfacts]]
- [[https://github.com/openkamer/openkamer][GitHub - openkamer/openkamer: Insight into the Dutch parliament]]
- [[https://cpaproject.in/][Criminal Justice And Police Accountability Project]]
- [[https://iapp.org/resources/article/us-state-privacy-legislation-tracker/][US State Privacy Legislation Tracker]]
- [[https://www.huschblackwell.com/2022-state-privacy-law-tracker][2022 State Privacy Law Tracker | Husch Blackwell]]
- [[https://github.com/fivethirtyeight/police-settlements][fivethirtyeight/police-settlements]]
- [[https://news.ycombinator.com/item?id=35284314][Watch the Watchers: LAPD officer database | Hacker News]]
- [[https://wid.world/country/india/][India - WID - World Inequality Database]]
- [[https://news.ycombinator.com/item?id=32902945][I accidentally started a movement]]
- [[https://filecoin.io/blog/posts/starling-lab-establishing-trust-for-humanity-s-data/][Starling Lab: Establishing Trust for Humanity’s Data]]
* SEED Environmental and Geographical data for Assam :assam:social:offline:data:govt:
** Description:
- How many trees in Guwahati over the years (this can actually be done for other cities)
- Other env data about the city
** References:
- [[https://github.com/blutjens/awesome-forests][GitHub - blutjens/awesome-forests: 🌳 A curated list of ground-truth forest da...]]
- [[https://news.ycombinator.com/item?id=30642612][Goldilocks Zone Finder – Find your ideal climate | Hacker News]]
- [[https://archive.is/G0EU8][M D Madhusudan on Twitter: "Looking at Sonitpur on the FSI map, it turned out...]]

* SEED Design HighQuality Tech Courses in Assamese :assam:education:social:
** Description:
- Decentralization 101
- Internet 101
- Privacy 101
- Wikipedia 101, Assamese culture, Assam movement etc. I'll contribute to wikipedia, contribute significantly and then do this to have proper impact.
** References:
- [[https://meta.wikimedia.org/wiki/Abstract_Wikipedia/July_2020_announcement][Abstract Wikipedia/July 2020 announcement - Meta]]
- [[https://en.wikipedia.org/wiki/Semantic_MediaWiki][Semantic MediaWiki - Wikipedia]]
- [[https://arxiv.org/abs/2004.04733][{2004.04733} Architecture for a multilingual Wikipedia]]

* SEED Website Tour video:fun:
** Description:
- Like travel vlogging but here you surf the web and internet and vlog about it.
** References:
- [[https://www.youtube.com/playlist?list=PLEXbN99LY3OCarUeXcxWeZzOelXQvVdAA][Personal Website Tours - YouTube]]

* DIED Stones of Assam :assam:offline:fun:
** Description:
Not only stones but other things. need to think on this later.
** References:
- https://stonepages.com/

* SEED WhatsApp stats tools :fun:
** Description:
- Make a tool that has many other tools that can create different stats/visualization from whatsapp chat exports
  - eg.
    - by date who talked most
    - how many words everyday
    - who started the conversation first most of the time etc.
** References
- [[https://f-droid.org/packages/com.mileskrell.texttorch/][Text Torch | F-Droid - Free and Open Source Android App Repository]]

* SAPLING Personal Image Board :tool:fun:notetaking:
** Description:
- taggable
- post memes, screenshots
- write a short desc that can be used for fast lookup later.
- offline first, run ocr on it locally and maintain an index to be searched later.
- don't need a phone app, wpa will do
  - if not wpa must make use of telegram api somehow, but wpa preferred.
  - anonymous twitter account and use hashtags can be good for starters also
- no duplicate photos/memes
- issues
  - basically i need pinterest here, but the existing open source solutions suck balls
** References:
- [[https://github.com/funmaker/hybooru][hybooru]]
- [[https://hydrusnetwork.github.io/hydrus/][hydrus]]
- [[https://github.com/kennell/imageboards][img boards]]

* SEED Weird Skill list :education:
** Description:
- whistling, making bird sounds, making sounds with hands etc etc.
- Basically the idea is to enjoy life without tech and be back to  the 2000s
- This will have an experts video and a tutorial video(optonal) ppl can submit via github issue or email for non technical ppl.
- There shou ld be a website
- Once ppl link videos, they should   be automatically backed up to a peertube instance and uploaded and have a cached version
- can also be list of funny ppt presentation collection videos: https://www.youtube.com/watch?v=CXKQEqEgdug, this can be a subreddit and a website sourcing the info from somewhere.

* SEED Layman explains latest advancements in different domains :education:
** Description:
There was a golden age of science but every year we also have amazing people doing amazing things. Have a list of awards eg. fields medals etc and have a simplictic editorial which explains it to a layman.
** References:
- [[https://www.mathunion.org/imu-awards/fields-medal/fields-medals-2022][Fields Medals 2022 | International Mathematical Union (IMU)]]

* SAPLING Deathnote :fun:
I tried this idea with betterkeep.co, didn't work out as expected but will try again later.
** Description:
A personal page that people can manage to put all info related to their death.
- monie
  - limit no. of items
  - image support
  - private/public (watchdog timer)
  - support of entering list in formats more than wisgy
- print friendly
- cute designs
- public deathnotes can be seen by each other for whetever reasons
- what incentive do ppl have if they publish here vs publishing in their own platfoms
- nice to have will vbe the deceased user policy of diff companies as reference
- have good sense of humor
** References:
- [[https://thoughtscollected.tech/posts/for-when-im-gone/][Cheat Sheet For If I'm Gone]] See HN posts on this
- [[https://github.com/potatoqualitee/eol-dr][potatoqualitee/eol-dr]]
- [[https://www.betterplacewishes.com/][Better Place Wishes]]

* SEED Crowdfunding for toilets :social:assam:govt:
** Description
So the issue with pay and use toilets here is that, first of all it should be free and paid for by the government. And in India, someone would just pee on the street rather than may 5rs to pee. So there can be a pipeline of donation which already pays the toilet fee allowing these public toilets to be used for free when someone who doesn't have the money to pay but still want to use the public toilet.

* SEED Google Dictionary Spaced Repeat :webdev:fun:
** Description
This is Debanga's idea. MFr says, We search for meaning of words on google all the time. But there's no quick way to lookup all the words that we searched for. Moreover it would be super awesome to have all of this wrapped around with some spaced repetion magic. Can be an extension, can be an app. But how it work on mobile browsers is a challenge. * Cries *

* SEED PirateNewsletter :fun:
** Description
This is Srijan's idea. He has premium subscription to some bitchass newsletter services, being the agarwal that he is, he wants to re-sell those subscription to other people at a lower price. Just keep a eye on the feed, use the premium to get the contents. Put it behind your own paywall. Aye Cap'n.
** Reference
- [[https://12ft.io/][12ft Ladder]]
- Archive.org

* SEED Saparscribe :fun:webdev:
** Description
So i bought a domain out of enthu. saparscribe.today idk what to do with it, i have following ideas. If you have something else in mind, lmk.
- Can be an extension
  - face of that guy
  - saaprakaribe text
  - saparscribe text
- Can be a newsletter
  - can be a sub of list of list on it's own for things to subscribe on the internet. can be a weekly/fortnight newsletter too.
  - Eg. best of product hunt, best of youtube, best of twitter, best of crypto, best of hackernews, best of reddit etc.
- Marketplace
  - People give the price(subscription) they would pay for a newsletter subscription and what should the newsletter should offer. If other people like the idea, they can upvote the idea but paying whatever amount they would pay for this subscription. (Free is an option)
  - For the creators: You have paid customers and a idea before you even build the newsletter(the product)

* SEED Twitter link archive :social:bot:fun:tool:
** Description
- Signup using your twitter/social media account.
- Can link more syndication platforms/your own blogs later
- Bot crawls your existing account for all links and archives them, you can see them in the platform
- Bot keeps monitoring your account postings daily and if there is any link that you shared/retweeted, it'll make sure it's archived
- Can also do ad hoc archival of tweets for you account if you DM it to the bot. Rather than do shit like readwise.io
** Reference
- https://twitter.com/LinkArchiver

* SEED API Cred sharing SaaS :tool:
** Description
API&Cred sharing made easy and secure for freelancers and employers. E2E model. Not meant for programatic access etc, more like designed for handover of API keys for freelancers specifically. CLI+Web
** Reference
- https://tlr.dev/
- hashi corp vault
- https://www.envkey.com/
- https://www.doppler.com/partners/product-hunt

* SEED Audio edition of blogpost/newsletter of any content :webdev:tool:
** Description
- This is in risk of replaced by AI eventually
- Marketplace model
- Whole functionality is embed-able like soundcloud emnbed, except, instead of listen, you can record and get paid
- Points, use points to get free audio
- Get popular newsletter to use this
  - Indian languages
- Responder
  - Only one response at a time
  - Audio distribution can be in form of a podcast owned by the server or i can simply host it
  - Can use speech2text to verify that most things are correct or to detect if it's AI that's speaking
  - HN like extension to check if audio exists for certain page
  - 1st audio has to be free, which will verify them by the requester, so I don't have to verify shit
    - 1st he has to do work of $5 worth. Can be one, can be multiple that adds upto $5.
    - By doing this they'll prove to be actually helpful, cuz the requester has to approve that free money.
    - Later i can decide wherether to return or no
- Request
  - I am paying $5 for audio
** References
- [[https://curio.io/][Curio | Journalism, narrated | Download the app now]]
- [[https://blogreader.com.au/landing/][Blog Reader]]
- [[https://techcrunch.com/2020/03/23/the-new-york-times-company-acquires-audm-an-app-that-turns-longform-journalism-into-audio/][The New York Times Company acquires Audm, an app that turns longform journali...]]
- [[https://stanfordrewired.com/post/world-of-narrated-journalism][What’s Lost and Gained in the World of Narrated Journalism | Stanford Rewired]]

* SEED Website from Image :fun:tool:offline:hardware:
** Description
This idea came from this [[https://news.ycombinator.com/item?id=33055426][post]] and the idea is to combine https://pixspy.com/ and the following javascript into one so that generating websites from handrawings becomes ez and fun.
#+begin_src javascript
var [_, ix, iy] = $('.FileDetails-details')[0].textContent.match(/(\d+) x (\d+)/);
var [_, dx, dy, sx, sy] = $('.Selection-summary')[0].textContent.match(/(\d+) x (\d+) @ \((\d+), (\d+)\)/);
[ix, iy, sx, sy, dx, dy] = [ix, iy, sx, sy, dx, dy].map(x => parseInt(x));
console.log(`left: ${100 * sx / ix}%; top: ${100 * sy / iy}%; width: ${100 * dx / ix}%; height: ${100 * dy / iy}%;`)
#+end_src
** Reference
- [[https://paperwebsite.com/][Paper Website: Start a tiny blog from your journal]]

* SEED Send a digital gift :webdev:ecomm:product:
** Description
An easy way to send gift digitally. Amazon gift cards are boring. Here you can select gifts that they can use digitally/offline/close to their neighbourhood etc. Solves for sending birthday gifts are hard, you hardly get any good gifts < 500.
** References
- read dot gift
- That gift website from the two person company

* SEED Twitter follower categorization :tool:notetaking:
Basically just automate what I did with my twitter following with some AI or maybe just basic clustering. Build it into a plug n play product.
* SEED Offline collab store :offline:
** Description
- Instagram Creators(Offline products) x Offline store product. Subscription of a Dynamic store.
- This requires initial money.
- Rent a very tiny but cozy and situated at a prime location place. example could be zoord area.
- Set up a dynamic shop. artists alone or artists with collaborators can team up to have their sale offline in this shop.
- So it's like a pop up store but we have different locations across the city. so it's like  a subscription that you can do for a offline shop when you not sure if you can go for a offline shop.
- You can book the place for a week.
- Shop is dynamic so will adjust to your liking and colors. we will have our own sales person who'll be advertising your shit
* SAPLING Linkcheck Extension :browser_ext:
- Issue: https://github.com/geekodour/experiments/issues/7
- Basically what combination of the web archives ext, what hn says ext and reddit check ext. but simpler faster and more flexible.
* SEED Hear me speak :tool:offline:assam:
** Description
- Make a simple webapp where people can record an audio for non-living things. it'll save the audio and generate a nice qr code with helpful text.
- now user can print as many of this qr code and stick them up in public places where it makes sense to put the qr code.
- eg. could be a lamp post or a bench in the park. it'll be written "HEAR ME SPEAK"
- now when someone (someone other than the user who put the qr in the first place) uses their phone to scan qr code(we may or may not collect location info) they can now hear the audio of the park bench speaking to them
- we can not collect location data automatically. we can have
  - report here me speak (they have to enable location there)
  - help the community by adding its location to the map
- can use whisper to create the transcript so that even deaf ppl can use it
- Another idea would be to click a picture with the object and then post it. People can see the pictures later. Or when new people talk, they can see the pictures other people clicked.
- Update: This has become more cool now, can use LLM+TTS+STT combo for a whole actual thing
** Reference
- https://physical-web.org/
- [[https://www.abc.net.au/news/2018-12-12/people-are-emailing-trees/10468964][People from all over the world are sending emails to Melbourne's trees - ABC News]]
- https://www.instagram.com/reel/Ci70ZgHoQig/
- [[https://www.schrodie.com/][Schrödie - A Hidden Guestbook]] (by siliconjungle)
- [[https://www.rtl-sdr.com/tag/gps-spoofing/][GPS spoofing]]
* SEED GetPolledBy :fun:social:webdev:experiment:
** Description
- get a twitter poll done by a popular twitter account in your niche
- can be a very powerful tool for market research
- it's actual data gathering, no marketing fluff, helpful to all
* SEED Setup personal shop with descriptions in victorian english :fun:
** Description
- you can make a dummy/real ecommerce experience by selling eg. flags of memes
- use victorean engliash to descripbe the product and features
* SEED Travel Journal :offline:
** Description
I already have some references around how I want to document my travel, https://diary.geekodour.org/travel/travel_post_ideas/
I then saw vipul( an oss friend ) do his thiland trip. What that guy did was, he put like 100s of stories everyday documenting everything.
So I want something in the middle. Need to think more on this[[https://bogomolnyelad.substack.com/p/board-game][How I proposed with a board game I created - by Bogo]].
* SEED QRcode Puzzle
** Description
- An online QR code generator that lets you ship the generated QR code as a jigsaw puzzle to your house or to someone else's house.
- You can select whether the puzzle should be scrambled or fit in together.
- you control what links to the qr code from your account
- https://news.ycombinator.com/item?id=37155574
* SEED Genealogy of different things :fun:data:webdev:social:
** Description
- I like family trees and trees and graphs in general.
- Can make this nice UI and graphs for different , eg. for math genealogy project, all images for scientists can be generated with stable diffusion in the same style. Can also ge genealogy of govt orgs.
- This is complicated than humans though because these things change name etc.
  - Can totally avoid this as a problem if we use aliases by design) also see basically can be list of list but for geanology stuff
** References
- [[https://github.com/rstacruz/kingraph][GitHub - rstacruz/kingraph: Plots family trees using JavaScript and Graphviz]]
- [[https://abc17news.com/news/national-world/cnn-world/2022/09/08/british-royal-family-line-of-succession-whos-who/][British royal family line of succession: Who's who - ABC17NEWS]]
- [[https://news.ycombinator.com/item?id=32780490][Mathematics Genealogy Project | Hacker News]]
- [[https://www.palladiummag.com/2022/10/17/the-genealogy-of-chinese-cybernetics/][The Genealogy of Chinese Cybernetics]]
- [[https://fuzzing-survey.org/][Fuzzing Survey]]
- [[https://everynoise.com/engenremap.html][Every Noise at Once]]
  - [[https://news.ycombinator.com/item?id=37919241][Ishkur's Guide to Electronic Music | Hacker News]]
  - [[https://news.ycombinator.com/item?id=37923732][Psytrance Guide | Hacker News]]
- [[https://m.musicmap.info/][Musicmap | The Genealogy and History of Popular Music Genres]]
- [[https://web.archive.org/web/20090124101248/http://www.jodoro.com/2008/09/genealogy-ontological-problem.html][jodoro: Genealogy the Ontological Problem]]
- [[https://news.ycombinator.com/item?id=8551830][The Genealogy of Eliza | Hacker News]]
- [[https://news.ycombinator.com/item?id=5576051][Show HN: Phdtree – create and search your academic genealogy | Hacker News]]
- [[https://news.ycombinator.com/item?id=31889047][Ask HN: What are good genealogy&#x2F;family history&#x2F;immigration search e...]]
- [[https://news.ycombinator.com/item?id=33267346][My PhD Genealogy | Hacker News]]
- [[https://antigonejournal.com/2022/10/descendants-mark-antony/][Living Descendants of Mark Antony – Antigone]]
* SEED Build a card game or a card game making company
** Description
Whatever the title says
** Reference
-  [[https://bogomolnyelad.substack.com/p/board-game][How I proposed with a board game I created - by Bogo]]
* SEED Ahilapaati Revival
** Description
Make everything fresh, port old stories for Ahilapaati etyadi. get someone proper for Assamese and language.
** Reference
- [[https://onehumanrace.io/][One Human Race]]
* SEED Local Animal shelter data
** References
- [[https://github.com/lexiross/fattest-cat][lexiross/fattest-cat: Script to find fattest cat currently up for adoption]]
* SEED Humancalendar
** Description
- pay whatever you like once complete. 100 copies will be printed and no more/ threesixfive.shop/human
- once photo is submitted, conferreti + make a really nice frame and everything so that they can share the proof on social media
** Reference
- [[https://humancalendar.com/about][the human calendar®: about]]
* SEED Currency conversion WP plugin
** Reference
- [[https://nicolasbouliane.com/blog/currency-tooltips][How I built currency conversion tooltips - Nicolas Bouliane]]
* SEED Combination Art but Stamps
** Description
Basically notion avatar like thing but you can buy the physical set and physical set is a set of stamps. block stamp or acryl. or something
** Reference
- [[https://www.kickstarter.com/projects/freeasabird697/seal-printing-we-make-stamps][seal printing - we make stamps by Xiayi Shen — Kickstarter]]
* SEED Website to promote businesses by under-rep groups
** Reference
- [[https://www.shopwityopeople.com/][Find Black Chicago Businesses | Shop Wit Yo People]]
* SEED Movie location in city :movies:
** Description
Whenever you enter any city see all movie locations from that city.

* SEED TV Shows by year :data:
** Description
By each TV channel, show:
- which show was show shown each year (Useful to see, what all TV shows were there in the 80s and what all shows are there now)
- Shows the continuation of shows, shows which show ran the longest so far etc

* SEED Improve web-archive w a fork as unmaintained.
** Description
See https://github.com/dessant/web-archives
We have some nice links in the issues section, can be made robust. archive.is + archive.ph links etc.

* SEED Most complex hello world
** Description
Create a project like no code where we create a community project where we make the most complex hello world in the planet, ppl can add prs which complicate the app but the end result stays the same.

* SAPLING GH2HTML
- Issue: https://github.com/geekodour/experiments/issues/6
- Basically we sometimes be having HTML files in a github repo and github will not render HTML.
- We make some smol service which takes (url, token if private) and renders the HTML. This can be server side rendered or client side.
- Can also probably implement password protect? See [[https://news.ycombinator.com/item?id=36276710][How to password protect a static HTML page with no JavaScript]]

* SEED A levels blog series on how to protect application on the internet
figure out  a good way to share a html page secretly to some team.

eg. we made small webapp that we want to share with team internally what to do?

- basic auth
- use some premium feature by provider
- vpn
- anything else?
- what is the herarchy of security
- what would be best?

* SEED Pens of India with likes counter

* SEED A public web canvas from scratch

* SEED Rot link checker
** Description
- Should handle both offline documents and online websites
- HTTP + more protocol support?
- Should be very fast

* SEED img2HTML
Basically img2 ascii converter but in ascii
- https://pgl.yoyo.org/img2html/
- https://github.com/EtherDream/web2img

* SEED HTML Clock
- https://blog.barnettjones.com/2019/11/03/clock-clock-clock/

* SEED Jobdiff
A platform to put in different job roles and it automatically filters the same part of every job listing. Allowing you to make things happen faster.

* SEED Personal Essay to AudioPosts
- Convert all the essays I need to read to audioposts.
- [[https://podcasts.google.com/feed/aHR0cDovL2ZlZWRzLmZlZWRidXJuZXIuY29tL1BHQXVkaW8/episode/aHR0cHM6Ly9wb2RjYXN0LmFwcC9ob3ctdG8tdGhpbmstZm9yLXlvdXJzZWxmLWUxMjMwNTAxMzAv?ep=14][Paul Graham Essays (Audio) - How to Think for Yourself]]
- [[https://github.com/neonbjb/tortoise-tts][GitHub - neonbjb/tortoise-tts]]
- [[https://scribepod.substack.com/p/scribepod-1#details][Scribepod 1 - by Yacine - scribepod]]
- [[https://play.ht/pricing/][Play.ht Pricing - AI Voice & Text to Speech Rates Online | Play.ht]]
- [[https://beta.elevenlabs.io/pricing][ElevenLabs || Prime Voice AI]]

* SEED URL shortner
- URL shortner but make it a funny one liner
- [[https://news.ycombinator.com/item?id=34609461][A URL shortener not shortening the URL but makes it look very dodgy | Hacker ...]]

* SEED Favorite companies as GIFS
- Historical GIFS collection
- [[https://charlieharrington.com/your-favorite-homepage-as-a-gif/][Your Favorite Homepage as a GIF]]
- https://github.com/bevacqua/shots 🌟
- https://github.com/jsvine/waybackpack

* SEED Personal Macro Trends Tracker
** Description
A macro view of the world. I am not sure how exactly the outcome would be but since I do not read newspaper and I do not like common news source I want to source my own news for things I care about.
- top 3 headlines from top newspapers of all important countries and continents (of my interest)
- Also add trackers and notifications for mention of various words and things happening on the internet. Eg. Whenever Nomsky(Noam Chomsky) says anything on education.
- top 10 most views on wikipedia (pageviews.wmcliud.org) (of my interest)
- google trends (my interest)
- other macro trends (my interest)
- link to daily digest podcast(eg. changelog)
** Reference
- [[https://news.ycombinator.com/item?id=34731897][rebase searches, what it indicate]]
- [[https://dayder.thume.ca/][dayder]]
- [[https://www.macrotrends.net/][Macrotrends | The Long Term Perspective on Markets]]

* SEED Board Game Tablecloth
Make a table cloth with different board games and pockets to store toys for the games

* SEED Generate custom OG Image from URL
- eg. i write hh.com?text=apple
- It gives me a url with thumbnail(social banner) photo of the text apple..
- interesting thing to inspect as part of this project would be to see if your server sees a request from telegram.com or messgenger.com or instagram.com as you type that url in the text. (i think they should receive a request , because otherwise where will it get the image from anyway)

* SEED Toolchest Extension :experiment:
- I insert stuff into my toolchest manually or via the form. This is extra work, copy url, copy desc etc etc. Want this shit automated +  better storage support. Eg. either some github repo or airtable or baserow whatever.
- Make a browser extension for storing things into secondary toolchest. Works across different tools. Automatically format title to appropriate things etc. Open backend, can use airtable if you want to. Use baserow if you want to etc.

* SEED DNS based StumbleUpon :experiment:
- This will need a custom resolver with a custom ttl
- Also check if i can store my security keys as txt records on my website
- another ref but not directly related [[https://lobste.rs/s/cl7p8c/dnsocial][DNSocial | Lobsters]]

* SEED Dumb Metasearch Engine
** Description
Often times, I have to append reddit to by searches, sometimes I need to search something on google maps, sometimes inside comments only on hacker news etc. This will just prepare the URL that'll take me to those search directly.
** References
- [[https://news.ycombinator.com/item?id=35025535][Show HN: Tiny Metasearch Engine to Find Software Developers | Hacker News]]
- https://xframe.app

* GROWN Improvise Cheat
- See cheats.geekodour.org
- I like =cheat=, the cli app that I use. but it's difficult to use.
- I like it because it's cli based and lets me edit stuff quickly
- But it lacks organization and proper formatting
- Initially, I thought i'll build on top of =cheat= to make its output more readable but now I feel it's just better to make it from scratch, it's simple enough
- Can use glow+markdown for output maybe (we only need for nice cli output)
- Maybe embed a webserver to view them in web (have some way to exports, so that i can have c.geekodour.org for all that stuff)

* SEED Gift wrapping paper business
I hate the gift wrapping plastic papers that i get
- uses plastic yuck
- ugly designs
- very easy to make good designs and patterns
- very cheap to print
- sold at high price, ez monie
* SEED Custom Preview Image right from URL :experiment:
- Basically site.com?text=hello_sup should generate the preview image with hello_sup.
- I am not sure if chat systems will catch this immediate dynamic update but we'll see.
- See [[https://github.blog/2021-06-22-framework-building-open-graph-images/][A framework for building Open Graph images | The GitHub Blog]]
* SEED guitar fretboard stickers
Can think of other paper/sticker based learning tools and make a proper store/collection out of it and sell shit on the billionare's site

* SEED iptables rule explainer :tool:
- And we already moving to nftables and othe bpf stuff, but i think there's atleast 5-6 more years till iptables go fully irrelevant(i even doubt that, idk shit)
- I want to make a simple tool that makes it SUPER easy to understand all(atleat what the rule says) of iptables just by looking at the command.
- Like explainshell but optimized for iptables only. explainshell misses out on extensions etc. (you can input one line or file)
- Can be both a CLI and a webapp
- Imagine a proper diagram, whenever you input the rule, it shows where exactly in the diagram the rule is going in something like that
- Also a realtime debugger. We already know that perl script so cool, an improved version of that.
- This is not ufw, not trying to be a firewall at all(but i must try ufw and fireshore or whatever). Just trying to make iptables itself easier to interact w because feel the clis are not good enough for learning atleast.
- tabs: Table1(filter),table2(nat), netfilter hooks live etc.
  - going to that rule (jjjj vim bindings)
  - hit some key, bam rule disabled, hit some key rule enabled (this type of stuff requires running the command, using -X etc).
  - hit some key and it comes up with the complete description of the rule and what each part means and where exactly it applies

* SEED Zotero+Calibre alternative for pdf and ebook management :notetaking:
- I don't want to write anything. I don't understand why there are no better alternatives. Have to try to build one to understand.
- Zotero+AI
  - [[https://github.com/Frost-group/The-Oracle-of-Zotero?tab=readme-ov-file#where-do-i-get-papers][GitHub - Frost-group/The-Oracle-of-Zotero: LLM Chain querying a scientific Zotero library, with citations]]
  - [[https://github.com/lifan0127/ai-research-assistant][GitHub - lifan0127/ai-research-assistant: Aria is Your AI Research Assistant Powered by GPT Large Language Models]]
  - [[https://blog.elicit.com/living-documents-ai-ux/][Living documents as an AI UX pattern]]
- Others
  - https://www.zotero.org/support/sync
  - https://www.reddit.com/r/books/comments/bi3il9/desperately_seeking_app_for_organizing_and/
  - https://www.reddit.com/r/Calibre/comments/s0vh2g/how_do_you_organize_your_ebooks_and_calibre/
  - https://www.reddit.com/r/math/comments/3ywfbq/how_do_you_arrange_your_pdf_textbooks/
  - https://www.reddit.com/r/Calibre/comments/uww7mu/calibre_as_a_pdf_management_tool/
  - https://www.reddit.com/r/Supernote/comments/xn9bxg/questions_about_drm_free_ebook_reading_and_pdf/
  - https://www.reddit.com/r/PleX/comments/86em57/is_there_any_way_to_create_a_library_with_ebooks/
  - https://www.reddit.com/r/linux/comments/dpb8z/question_ebook_manager_for_linux/
  - https://www.reddit.com/r/humblebundles/comments/ksjuut/app_for_ebook_library/
  - https://www.reddit.com/r/DataHoarder/comments/9znmum/can_someone_who_uses_automatic_library_management/

* SEED Man Page Searcher :tool:
Doing good full text search on manpages is not super common. But sometimes I need it
** References
[[https://unix.stackexchange.com/questions/8982/full-text-search-for-man-pages][- Full text search for man pages - Unix & Linux Stack Exchange]]
[[https://askubuntu.com/questions/116112/how-do-i-perform-full-text-search-in-man-pages][- manpage - How do I perform full text search in man pages? - Ask Ubuntu]]

* SEED CLI for ASCII header for protocols :tool:
- Sometimes I want to quickly see what's the header of some protocol looks like.
- I can go to wikipedia but like having it in the cli that too in ascii would pass the real vibe check.
- This can also add support for a fake protocol server maybe like https://github.com/fofapro/fapro
  - Basically you can fill in stuff to create a TCP packet suppose and then simulate it etc.
** References
- [[https://news.ycombinator.com/item?id=26965186#26968283][Protocol – An ASCII Header Generator for Network Protocols | Hacker News]]
  - This is nice but not exactly what I want
- https://github.com/martinlindhe/feng

* SEED Make Go port of MapASCII :geo:
See https://github.com/rastapasta/mapscii

* SEED Generalize MetroGit to any data that can be represented that way :geo:
- See https://github.com/vbarbaresi/MetroGit
- Think of other software where we can hack around and do this kind of stuff

* SEED Becomecat :fun:
- An browser extension
- An window executable
- A linux executable (packaged for certain distro which has a name that starts with a)
- I want to try building a cross platform software basically, that's the main point.
- [[https://pulsar17.me/2023/09/keymapping][Having fun with keyboard mappings under Linux pulsar17's blog]]

Basically once activated, all keyboard strokes will be jumbled and when you tr to write normal things you'll be writing like a cat hence becoming a cat.

* SEED Styling and semantic changes to other web pages :webdev:
** SEED Ez stylize old webpages for better viewing :webdev:
- There are extensions such as Stylus but that need manual work
- [[https://ti.geekodour.org/tils/styling-websites-for-better-reading/][Styling websites for better reading - todayi]]
- This is not about slapping readability on any webpage. Unlike https://web0.cc/, this requires that style is specific to the webpage. (or even domain, which helps in stylus case. hmmmm, i see why stylus is useful now as i write this)
- I did not want this to be an extension but a website, or something that generates contents client side only, have to think
- Flow
  - just paste link to plain html website and automatically stylize it and make extra css changes/js changes to it (remove all css, add ur css etc.) and save all that changes as config(in the url) . so to share the modified page, all you need to share is share the url.
  - also add template js eg. to move toc to the side and make it sticky.
- Domain eg.
  - basically get a url like: poop.com
  - now to use poop.com
    - poop.com?u=anything.com?ww
    - poop.com?u=xx.anything.com/hu?ia=77
- This does not need you to install any extension or anything and will persist so you can share.
- Ref. storing state data in URL: [[https://news.ycombinator.com/item?id=34312546][How to store your app's entire state in the url | Hacker News]]
  - Others: https://goshify.tny.im/, https://github.com/alcor/itty-bitty, [[https://news.ycombinator.com/item?id=37408150][Show HN: Host a Website in the URL | Hacker News]]
** SEED TOC for any webpage
- Something like SmartTOC web extension but free.
- Add dark mode, resizable
- Instead of a sticky like a note, it can also a horizontal bar at the top or bottom etc, good when reading in small screens.
- Specify webpages(regex) where it should automatically turn itself on etc.
- Specify level of depth
** SEED Improve sites by semantic changes :tool:
- Certain sites need improvements beyond style and JS change.
- Eg. https://demonstrations.wolfram.com/ is so nice. But, if you just want to browse it, it's hell. Basically the catalogging sucks. Basically exploring UI/UX too bad.
- For this the final content can be in wolfram, but I can improve the catalogging.
- So what I want to do here is
  - Scrape the stuff, just get the hierarchy
  - Improve the UX and present it at ~whatever_name_i_keep.com?s=demonstrations.wolfram.com~
  - That's it.
  - Now we have to keep 2 things in mind when scraping, it should be updated on new changes automatically, if the whole site changes, the thing should have the ability to be rolled back and then freezed at that point.
** SEED github gist browser :webdev:
- current gist-ui in github.com is bulky and all, would be nice to have a better and simple ui
- Improvements
  - 1. have a sidebar with all the gist that i can click and just view on the side.
  - 2. the view pane will be markdown rendered and can have different themes like hugo.
    - basically any hugo theme should work out of the box. it'll use the post layout.
    - this way I won't have to design themes and ppl still will be able to share it that way
- see https://scribe.rip/

* SEED Make drawings/animations for Sync File versioning :education:
- Syncthing has this doc which describes various file versioning stratigies, I always forget them.
- https://docs.syncthing.net/v1.23.3/users/versioning
- Diagrams would help

* SEED An url things doer
- We can do a lot of things w an url
  - Based on the url structure alone
  - Based on the content the url provides
- Examples
  - Link with instagram in url
    - Action: Download the video and put it into my archive. Also keep a link to the original link along w the video. These actions each can take additional input variables, and will take in some default otherwise etc.
    - Action Filter: This action will show up on the filtered list only if regex or any other match matches the url
  - A link to a HN comment
    - Action: Copy text and put it into the file where I maintain a list of HN comments.
    - Match: A link in HN and comment look the same, so for this, open the link and check if it's a comment. If it's a comment show comment specific actions.
    - [[https://www.youtube.com/watch?v=-tJNxzH1zCA][Saving Hacker News Comments to Notado]]
- Execution
  - Actions would be self defined scripts. Its supposed to be used by programmers or people how know how to make the computer do things. i.e not a diy thing, more in the lines of tasker but also needs programmability. There can be open source action recipes but it's mostly to facilitate very niche custom user actions.
  - Would need a self hosted webapp
  - And would need a phone app with share to "this" app feature that fills the url and gives me a list of possible actions to execute on the url.

* SEED The website backup project
- I haven't explored webrecorder and archivebox fully yet but I think they are for personal use and stuff
- What I want to have is a community mirror of websites. (ifk if it's legal, easier to ask for forgiveness than to ask for permission in this case, it should be based on other things)
- What I mean is, suppose a website like endofline.date, hyperpolyglot.org etc solid good info. But that info is not just a page. Like what archive.is does. It's a whole website, the value of it is in having the whole website at your tips not just one page.
- So we want to backup the whole website, which is obviously possible and I do it myself w wget and httack and what not etc. But being able to do something like ~backedupwebsites.com?q=hyperpolyglot.org~ and see a list of public backup of the whole website will be awesome, if not being able to trigger your own backup would also be awesome. It doesn't have to be instantaneous or anything, just giving me a gurantee that if that domain ever goes of i'll still have access to this solid data.

* SEED Movie colors poster
- What I want to do differently:
  - I want to make the colors and the timestamp data public
  - I want to make the process opensource
  - I want to make the way for people to support the project through donations and by buying the prints.
- Steps
  - write a script that uses ffmpeg to export each frame of your video as an image ... f(movie) = images
  - write a script that reads a series of images, returning their average colors ... f(images) = colors
  - write a script that takes a series of colors, and outputs an image using imagemagick ... f(colors) = image
- References
  - [[https://thecolorsofmotion.com/][The Colors of Motion]]
  - [[https://zerowidthjoiner.net/movie-barcode-generator][Movie Barcode Generator]]
  - [[https://screenmusings.org/color/][The Movie Stills Color Database]]
  - [[https://github.com/SuziKim/ICMR2020-MovieColorSchemer][GitHub - SuziKim/ICMR2020-MovieColorSchemer: Automatic Color Scheme Extraction from Movies]]
  - [[https://moviesincolor.com/][Movies In color]]
  - [[https://moviebarcode.tumblr.com/page/15][moviebarcode]]
  - https://github.com/supergeniodelmale/Cinemetrica
  - https://dillonbaker.com/#/spectrum/
  - Not the same idea but similar
    - [[https://news.ycombinator.com/item?id=40166516][Show HN: Scenestamps – A website for sharing movie scenes with timestamps | Hacker News]]
    - trace.moe

* SEED Baked Design Ideas (Multiple)
There are some interesting ideas in baked design linear as well.
* SEED stackoverflow.js
- A JS library that offers various data structures that just overflows the stack.
* SEED Random Gift suggestion
- Stumbleupon for gifts + filters
- Crazy things on amazon
- Has to be very fun to use
- All links will be affiliate links
* SAPLING Napkin math CLI+Viz
- Issue Link: https://github.com/geekodour/experiments/issues/42
- napkin math cli + baked in html viz
- cli program to list out latency numbers on your machine by actually doing the numbers on your machine and network!
* SEED Run offline magazine/journal
See [[https://www.tradejournalcooperative.com/][The Trade Journal Cooperative]]

* SEED Make a tool to demo the curl sh thing :fun:
- similar to fillipo ssh thing
- [[https://news.ycombinator.com/item?id=36069024][Ask HN: Why is curl | sh so frowned upon? | Hacker News]]

* SEED Make a HTML
- Use the HTML energy to make a scavenger hunt game
- [[https://www.patrickweaver.net/blog/a-blog-post-with-every-html-element/][Patrick Weaver]]
- Steps
  - Open page: check title
  - Title: check html source for the tag footer
  - Footer tag: Check browser console (hmm, won't be mobile friendly then)
  - and so on. You get the idea. Final message should be interesting.
- Insp
  - [[https://www.youtube.com/watch?v=AbSehcT19u0][Hal fixing a light bulb (from Malcolm in the Middle S03E06 - Health Scare) - ...]]
  - Rube Goldberg machine

* SEED Make a Himesh Rashemia pw get
- Insp
  - https://www.kennylog-in.com/

* SEED Make something with HTTP Status codes
- https://github.com/3digitdev/Haiku-TTP-Codes
- [[https://httpstatusdogs.com/][HTTP Status Dogs]]
- [[https://httpraccoons.com/][TrasHTTPandas - Raccoon HTTP Responses]]

* SEED Make list of all emoji and their length
This is just and exercise/excuse in filtering logic in html tables w js + better understanding unicode
- [[https://evanhahn.com/utf-21/#introducing-utf-21][Introducing UTF-21, a toy character encoding]]
- See [[https://evanhahn.com/javascript-string-lengths/][Why does "‍🌾" have a length of 7 in JavaScript?]]
- [[https://news.ycombinator.com/item?id=36159443][It’s not wrong that length == 7 (2019) | Hacker News]]
- [[https://lobste.rs/s/vdj66z/is_this_emoji][Is this an emoji? | Lobsters]]
- [[https://sethmlarson.dev/utf-8][How does UTF-8 turn “😂” into “F09F9882”?]]
- [[https://lobste.rs/s/ql8goe/how_create_utf_16_surrogate_pair_by_hand][How to Create a UTF-16 Surrogate Pair by Hand, with Python | Lobsters]]
- https://ericandrewlewis.github.io/emoji-mosaic/
- [[https://news.ycombinator.com/item?id=36369553][Update: U+237C ⍼ &Angzarr; | Hacker News]]
* SEED Make a local storage filler :fun:webdev:
- Cookie, local storage, cache, session storage, indexdb, everything
- Basically, you open this webpage and it'll show you  all available storage and you can start filling them with random bytes.
- Interesting thing would be to detect all the storage features available in different browsers.
- See [[https://mmazzarolo.com/blog/2022-06-26-filling-local-storage-programmatically/][Using JavaScript to fill localStorage to its maximum capacity · mmazzarolo.com]]
* SEED CLI funny email reminder :fun:
- Get email setup same way as double confirm newsletter mechanism
- Set a reminder for something `remind "get choco's meds" -t today/next sunday`
  - Sends a http request to an open endpoint with to email id.
  - Take content and fabricate content with llm and add sd wifu image related to content
  - Validate email exists in db, send email, also attach events etc if date was mentioned.
- [[https://www.engadget.com/2010-09-30-captio-the-simple-app-that-just-might-change-your-life.html][Captio: The simple app that just might change your life | Engadget]]
* SEED Transcript mpv plugin
Create mpv plugin to generate lecture transcript for any video and show transcript in the web browser using websockets as done in this https://github.com/Sharrnah/whispering
* SEED CompSci Book Catalog w Wifu
- There was a github repo with anime girls holding comp sci books i can't recall
- [[https://news.ycombinator.com/item?id=37230995][Ask HN: Nicknames for Computer Science Books? | Hacker News]]
* SEED Crowdsourced+AI YT Vid transcription
- darrow type yt transcript/summarization community project
- whisper and yt captions can do the basics and now yt by default also would summarize i guess
* SEED Listen Poetry from other languages by words
#+begin_quote
This website is my answer to the question: “If I were an English speaker trying to get an idea of how Italian poetry sounds, what tool would I like to have?” - See https://italianpoetry.it/
#+end_quote
- Basically make a framework/tool that people can host themselves. Have the transcription, word level highlighting etc.
- This is more about data and the process than the styling. styling who'ver is making the website is doing. So in ways, this library/framework should provide the functional stuff from intilanpoetry.it
- See HN: [[https://news.ycombinator.com/item?id=37888606][Show HN: "Interactive" Italian Poetry for English Speakers | Hacker News]]
* SEED WooCommerce <> Telegram via CF workers
- Port this (https://github.com/mini-woo/mini-woo) to be able to run in CF workers
- I would want to write this in go and then put the wasm build to cf workers
* SEED Create a podcast about places
- Idea is:
  - Let people pick some local place(like real local locacl, like some gali in indiranagar types) on the map
  - Get a local person from that place, who knows history, culture, data around that place and then dig into that place and around places in the pod.
    - Outputs can be pod, blogpost, dataset, photos, what else
- [[https://news.ycombinator.com/item?id=37954321][Maps.fm: listen a podcast episode about that place on the map | Hacker News]]
* SEED Mood tracker based on vibes
- simple webapp, you can take a ball and drag it on top of one of these
- should record the mood at that time. my current mood tracker sucks, this could be fun
https://discord.com/channels/1142016455831978014/1142766572939784294/1166764490155634759
- It's so over
- it is what it is
- we're so back
- lfg
- fuckitweball etc
* SEED API for data for each state :geo:
Ashrish's idea of building a simple declarative api for data about each state
* SEED Assemble a team
- build a game/app w chad people on the internet and people can group them and create a fictional team out of them.
- Eg. zuck+karpathy+ambani = space fruits
- Idea from a tweet by some guy called arpitingle
* SEED Lobsters circle graph
- we can make a circle inside circle graph for this.
- user will be able to configure what to show for each user,.  eg. only username, github link, profile link? all of them? profile photo?
- we can use the tree to directory cli tool here
- https://lobste.rs/users
* SEED Movies by Timeline(Year) x Place (Depecting actual history of places)
- https://www.imdb.com/search/title/?title_type=feature&genres=history
- https://sites.google.com/site/mbondlamberty/movies
- We don't consider movie release date, we consider where the context of the year the content of the movie is set in. Eg. If we go (India x 1993), we see movies which are set in that place and time even if the movie was release in 2023
- i.e When was this movie set in(which context, which year, eg lagaan <1947)
- a list of movies by place and time. similar to that radiooo timeline thing but for movies from places
* SEED Movie get time-screen grabs
- i.e https://humanclock.com/ but for movie screengrabs where
- Taxi Driver 29th July scene but for all dates
* SEED Wikipedia Place History Coverage Report
- Data analysis of how much of history of each place is covered  by wikipedia. history coverage
* SEED Character emails
- Make a email service where we give fictional characters email address. You can email them anything and they'll reply back.
- Eg. email address of goku. email address of spiderman etc.
- See character.ai hype. Can cc multiple ppl from different universe.
- Ref
  - [[https://www.xomedia.io/a-deep-dive-into-email-deliverability/][A Deep Dive into Email Deliverability in 2024]]
* SEED Create animations w Manim for math/sci concepts
- [[https://blog.matthen.com/][blog.matthen.com]]
* SEED Comprehensive guide to assamese weddings
Jinty Aunty be the queen of the show!
* SEED Github URL > Video
Make a video generator from github url. contribution graph, github user best contribution, basically get all the stats data to get significant events from clickhouse wala github thing and get screenshots and show them in significant parts of the video. we can also use image gen, music gen etc, remotion will be the way to go
* SEED Pacman on Google map
ideas:
1. pacman on google maps/osm
2. highway.js (2 modes)
2.1 highway mode (the text width will be the road, side will be greens, can be birdeye or FPV, how much distance covered controlled in pref)
* SEED Slackbot
- Change slack messages to a differrent tone configurable by the user (paid)
- https://github.com/hmirin/SlackAutoCorrectionBot
- See [[*Setup personal shop with descriptions in victorian english][Setup personal shop with descriptions in victorian english]]
* SEED CLI TOPT that supports Aegis app export
- See [[https://news.ycombinator.com/item?id=39495378][TOTP Codes in the Terminal | Hacker News]]
- [[https://news.ycombinator.com/item?id=40855773][How random are TOTP codes? | Hacker News]]
* SEED Can I migrate my makerlog thing from discord to a fork of linen?
See https://github.com/Linen-dev/linen.dev
* SEED Make dynamic version of price of things using ai
https://github.com/eyeseast/price-of-things?tab=readme-ov-file
* SEED Discord Server Organizer
- See https://www.reddit.com/r/CommunityManager/comments/18e0m79/seeking_insights_how_do_you_organize_your_discord/
- See https://www.reddit.com/r/discordapp/comments/13tesj9/is_there_no_better_way_to_view_and_organize_the/
- See https://linen.team/
- See https://www.linen.dev/
* SEED reddit username to image gen
- I saw a reddit username with the username empathetic_asshole, i really wanted to know what that username would look like
- Think dalle and midjourney can help. There's a lot of funny usernames on reddit.
- We can also have a browser extension that attaches the image on hover of the username.
* SEED Proxy "Say It" Twitter account (Bad idea)
- A twitter bot account that people can use to anon reply to other twitter threads
- Eg. I see a tw thread, I want to reply but i don't want to reveal myself. So I use this service to <thread link> and my comment and the proxy account will post on the behalf.
- This has to be a verified service
* SEED A public sinage with a display and a camera
- Automatically detect person infront of the camera or person walking by. (Make sure to pick only the person)
- Quickly understand the visuals using something like GPT4o, automatically write something nice about their appearance or something. Eg. Nice blue hat sir!
- Quickly click a picture if they see it and smile
* SEED Music 2FA
- https://github.com/rsc/2fa
- https://blog.singleton.io/posts/2022-10-17-otp-on-wrist/
- https://github.com/cgzirim/seek-tune
- i am tired of copy pasting topt from phone. i can have have cli topt but music topt would be so awesome. to make it work with existing sites and otp stuff we can have a webext which translates music into numbers and fills the input field.
- music otp instead of topt using generative music
- basically the ideas will have OTP and there will be a seed so like when you can be a seed and that only that based on time as certain music will be played right so it will be pound of shit but when you play the music it will only play that music only and that time so you whatever the website is you have to just basically turn on the audio and new
* SEED Data viz/analysis from Video Link
- I saw this project stepify which does text guide from YT video links: [[https://news.ycombinator.com/item?id=40104641][Show HN: I made a website that converts YT videos into step-by-step guides | Hacker News]]
  - Nice usecase
- What we could do further though, is upload your youtube video/vlog footage etc. and then get data analysed out of it. could be fun.
  - eg. in this vlog how many cars were shown, how many birds were there etc.
  - LLMs have data viz and analyse capibilities, we can combine vision+data analysis capabilities and get out task done.
- Sometimes you go to places and record things but don't really understand the things you're recording. And you're too lazy to even ask. If you feed the video into this, you get more nerdy info about the video that you usually would not realize. Eg. the car that you just saw was a rare one etc.
- [[https://lobste.rs/s/z5karh/extracting_wisdom_from_conference][“Extracting wisdom” from conference videos | Lobsters]]
* SEED start a small initiative to provide better gear for masons(kamla)
safety equipment supplier ngo for local labours and
* SEED Archival format but format is Docker image
- like https://nixery.dev/ but you could run docker pull against any website and it'll archive the website as a OCI image
- [[https://news.ycombinator.com/item?id=40632533][Show HN: Crawl a modern website to a zip, serve the website from the zip | Hacker News]]
* SEED Instagram account & saved posts classifier
- I have too many interesting accounts that I follow but then all of them are clubbed together in the following list.
  - I want to see all the electronics ppl i follow
  - I want to see all the woodworking ppl i follow etc
- Same for saved reels/ other posts
  - Now for the reels/media part, if we allow chonky to get the media we're sorted. So for the media we'd want this shit to be part of chonky as of the moment.
- We can get the whole following list using download my data thing.
* SEED Build a fucking decent podcast player
- https://www.reddit.com/r/ObsidianMD/comments/16qodbp/now_that_snipd_is_no_longer_free_has_anyone_found/
- I just don't understand why there is no decent oss podcast playerr with automatic transcript generation and follow up on words as the podcast plays. This is super annoying.
  - https://anytimeplayer.app/
  - https://discuss.grapheneos.org/d/10148-best-foss-podcast-app
* SEED Place DNS
- Srijan's srijan.space thing but i guess u cant put cname in dns, so you'd need a html redirect.
- We make a service which gives custom subdomain(random) for any link like url shortner and then you can use it in ur dns
- https://github.com/captn3m0/redirects
* SEED Local place data Geo framework
- A ready to cook framework/(combination of software and other) things that can be applied to any place(big/small) eg. to narengi or to guwahati and then with it we'll have data collected which will tell us state of the place and ways we can improve it.
  - Eg. Say we name the framework X. When X is applied to place Y. We'd have answers such as:
    - How many trees are in Y. How many trees does Y actually need.
    - What kind of animals were here 10 years ago and not now
    - What do most people in this area do etc etc.
  - Some govt already collect this info and we can have that info sourced from there, otherwise we can manually have ways to source this data etc etc.
- Think this kind of framework will really help indiviual/community take better decisions around their surrounding and also will help new people joining the community/place
* SEED Discover Local "Made" Software
there are always this local applications are processes which are there to do like what big companies do like there believe there will be a local Guwahati specification which people from outside do not know because I distribution is not there The just know airbnb. another example would be they just now over but they don't know this local cab services that there are right so we need an overly application overlay something that's is okay for this specific location for this Pacific application disorder local alternatives and these are the things that you could use and they will have the reviews and then you can fill it out but it will always not be great but at least you will have some alternative
* SEED Asciify
convert any image in the body of the website into ascii form of the image, do it efficiently and before the first paint
