#+HUGO_SECTION: docs/updates
#+TITLE: Anti-Library

#+attr_html: :class book-hint info
#+begin_quote
an [[https://www.antilibrari.es/][antilibrary]] is that collection of books you know a bit about, but have not read, and the latent potential of all the wonders they may hold. We can extend the same idea to other media, too — essays, films, websites, and so on — anything you might learn from.
#+end_quote

#+begin_details
#+begin_summary
How is the anti-library populated?
#+end_summary
Anti-library sort of is just a fancy term for bookmarks in the way I am using it. It falls in the capture phase of my [[file:o.org::*Notetaking][notetaking]] process. I use =org-capture= to manage these notes and there's some custom css which help color the status of the items in this page.
The supported statuses can be found [[https://github.com/geekodour/dottedflies/blob/566aa2a3524f5b705cc9ce9a0564fc64e759decd/.config/doom/org-mode-config.el#L127][here]]. When making entry for [[file:o.org::*Monthly notes][monthly notes]], we shall discard =FINISHED= and =DROPPED= items from the anti-library. If I make any notes they'll be available in the [[https://mogoz.geekodour.org][wiki]]

I've exported this page just to have the information public, otherwise this page is managed and used inside emacs, i have =org-agenda= templates which picks things up from this list to put them in my agenda.
#+end_details


* Posts
** Un-categorized

*** TOCONSUME Srilanka and Farmimg
- [[https://agrowingculture.substack.com/p/going-organic?r=1ege7e&s=r][Going Organic - by A Growing Culture - Offshoot]]

** Lifestyle
*** TOCONSUME About the Elite
- [[https://aella.substack.com/p/learning-the-elite-class][Learning The Elite Class - by Aella - Knowingless]]
*** TOCONSUME Post about connecting devices
- [[https://shkspr.mobi/blog/2022/04/the-inevitability-of-connecting-everything/][The Inevitability of Connecting Everything – Terence Eden’s Blog]]
** Product
*** TOCONSUME Hill Charts
- [[https://jordankoschei.com/2019/02/12/the-problem-with-hill-charts/][The Problem with Hill Charts — Jordan Koschei]]
* Movies
** Un-categorized
* Videos
** Un-categorized
* Books
** Un-categorized
