#+FILE_NAME: history
#+HUGO_SECTION: docs/collections
#+HTML_CONTAINER: div
#+OPTIONS: broken-links:mark
#+HTML_CONTAINER_CLASS: smol-table
#+TITLE: History

#+attr_html: :class book-hint danger
#+begin_quote
This needs to be migrated to my tool logpad. Some texts have the BROKEN link, that's because by default pandoc does not translate markdown to org internal links correctly. All of this will be resolved by design when I migrate to logpad. For complete info, see org file itself.
#+end_quote


A lot of events in history are important, but some events are more important to me than others. If you want me to add some event to this list, then open a [[https://github.com/geekodour/wiki/blob/master/docs/notes/history.md][PR here.]]

#+begin_quote
Some of these are "first to invent" and others are "first to popularize". I've linked some keywords to their past/future but most of them are just plain facts.
#+end_quote

* 2024
- Your boy started building things again 👷
- 🇮🇳 Ram-mandir was inaugurated
- There are 2 big wars ongoing
* 2023
- Ask me about this period in my life when I am drunk
* 2022
- Ask me about this period in my life when I am drunk
* 2021
- Ask me about this period in my life when I am drunk
* 2020
- *Coronavirus* declared global health emergency by WHO
- Number of Internet users reaches [[#2005][4.5 Billion.]]

* 2019
- 🇩🇪 Yours Truly took his first international flight. 🛫
- Google claimed to achieve *Quantum supremacy*. (idk what that means doe.)
- [[#2003][NIXI]] appointed Neustar Data Infotech to manage [[#2004][.in]], they are starting to add Indian-language domains.
- The first ever image of a black hole was captured, using eight different telescopes taking simultaneous pictures, timed with extremely precise atomic clocks.
- *Y.3172*, an [[#1992][ITU-T]] Recommendation specifying an architecture for machine learning in future networks including 5G was released. It also mentions methods such as containers and orchestration.

* 2018
:PROPERTIES:
:CUSTOM_ID: section-2
:END:
- I was on a phonecall with [[#1985][RMS.]] (pretty big deal for me.)
- [[#1995][TLS 1.3]] was put out.
- [[#1911][IBM]] acquired [[#1993][Redhat]]

* 2016
:PROPERTIES:
:CUSTOM_ID: section-3
:END:
- 🇮🇳 *Jio* was launched in India by [[#1973][Reliance]]

* 2015
:PROPERTIES:
:CUSTOM_ID: section-4
:END:
- *ZeroNet* launched. (Combines NameCoin, Bittorrent and TOR somehow)
- *IPFS* initial release.
- Yours truly finally got proper internet connection. 🕸
- AlphaGo defeated a professional human opponent.
- *Caddy* was put out by Matthew Holt.
- *WebAssembly* was announced, it became a [[#1994][W3C]] recommendation in 2019.

* 2014
:PROPERTIES:
:CUSTOM_ID: section-5
:END:
- *Kubernetes* initial release.
- *VLANX* was introduced to deal with the scalability(only 4095 VLANS) issue of [[#2003][VLANS]] for large cloud deployments.
- *Raft* consensus algorithm was put out in a PhD thesis by Diego Ongaro.
- *Let's Encrypt* non-profit was founded by [[https://en.wikipedia.org/wiki/Internet_Security_Research_Group][ISRG]], it was finally launched in 2016. They also created the ACME protocol for this.
- *nftables* was added to the Kernel.
- *Heartbleed* a bug in [[#1998][OpenSSL]] was found.
- 512k day.

* 2013
:PROPERTIES:
:CUSTOM_ID: section-6
:END:
- *Aaron Swartz* left us. 🥀
- Netflix and YouTube account for over 50% of Internet traffic measured by bytes.
- 🇮🇳 IRNSS was launched because GPS is not controlled by the Indian govt.
- *etcd* was released.
- *Docker* was released.
- *TempleOS* was released. Davis started writing it around 2003. He passed away in 2018. RIP Davis 🥀

* 2012
:PROPERTIES:
:CUSTOM_ID: section-7
:END:
- English Wikipedia was blacked out for one day to protest the SOPA
- *Google Drive* was launched.
- *Raspberry Pi* was introduced to the world.
- *Coursera* was founded by Andrew Ng and Daphne Koller.
- *Edx* was launched by MIT and Harvard.
- *Prometheus* was developed at [[#2008][SoundCloud]] out of need.

* 2011
:PROPERTIES:
:CUSTOM_ID: section-8
:END:
- *Sci-Hub* launched by Alexandra Asanovna Elbakyan.
- *BYJU'S* was founded by Byju Raveendran.
- *Open Compute Project* was started at Facebook to openly share designs of data center products.
- *Apache Kafka* was made open source.
- *CRDT* concept was formally defined.
- *NVMe*, an open logical device interface specification for accessing non-volatile storage media attached via [[#2004][PCI Express]] bus was launched.

* 2010
:PROPERTIES:
:CUSTOM_ID: section-9
:END:
- *Instagram* was launched.
- *Unacademy* started as a [[#2005][YouTube channel]] by Gaurav Munjal.
- *Udemy* was founded.
- *PayTM* was founded.
- [[#1982][Sun]] was acquired by [[#1977][Oracle.]]
- *Apache Zookeper* paper published.
- *Rust* language was born.
- *Private Internet Access (PIA)* was founded. The founder seems interesting to me.
- *systemd* ‍was put out. ⚠️ ⚔️
- *RISC-V* an open standard instruction set architecture (ISA) was put out by [[#1986][David Patterson]]

* 2009
:PROPERTIES:
:CUSTOM_ID: section-10
:END:
- *Bitcoin* paper was published.
- *WhatsApp* was born.
- *Quora* was created by Adam D'Angelo.
- *Cloudflare* was started. It received media attention in June 2011 for providing security services to the website of LulzSec, a black hat.
- *SoundCloud* website was launched by Swedish sound designer Alexander Ljung and Swedish electronic musician Eric Wahlforss.
- *DNSSEC* becomes operational on .org
- =perf_event= was introduced to the Linux kernel. =ftrace= was added around the same time.
- *Go / Golang* programming language was born.
- *AppArmor* was added to Kernel.

* 2008
:PROPERTIES:
:CUSTOM_ID: section-11
:END:
- *DropBox* released to the public.
- First *Android* smartphone(HTC Dream) was released. [[#1996][*Google*]] acquired Android in 2004.
- *Library Genesis* was started after the downfall of [[#2004][Library.nu]].
- *Spotify* application launched.
- *cgroups* were added to the Linux Kernel, there was a rewrite of cgroups in [[#2016][2016]], *LXC* was released around this time aswell.

* 2007
:PROPERTIES:
:CUSTOM_ID: section-12
:END:
- *iPhone 1* came out.
- Apple opensourced *Clang* compiler.
- *SCTP* RFC was published.
- *KVM* was merged into kernel.
- *VirtualBox* was made opensource.
- *Btrfs‍* was demonstrated and was merged into the Kernel in 2009.

* 2006
:PROPERTIES:
:CUSTOM_ID: section-13
:END:
- *WikiLeaks* launched.
- *Twitter* was launched.
- John Resig wrote *JQuery*
- Apple switched to Intel x86 processors from [[#1994][PowerPC]] based processors.

* 2005
:PROPERTIES:
:CUSTOM_ID: section-14
:END:
- *Git* was made public.
- *FUSE* was merged into Linux 2.6.14
- *YouTube* was launched.
- *Reddit* was launched.
- *Atom* syndication format was published as an IETF proposed standard.
- Number of Internet users reaches 1 Billion.
- [[#1968][Intel]] joined to work on *UEFI* to replace [[#1975][BIOS]]
- *QEMU* paper was published.
- *ZFS* was merged into [[#1991][Solaris]].
- *Arduino* project was started, Arduino joined hands with [[#1985][ARM Holdings]] in 2017.

* 2004
:PROPERTIES:
:CUSTOM_ID: section-15
:END:
- *Facebook* was launched.
- *Library.nu* was launched. (Later taken down in 2007)
- *.in* TLD was registered.
- *Markdown* was released, [[#2013][Aaron]] and John gruber worked on it.
- *[[#1992][PCI]]-Express*/PCIe was announced, It has a point to point connection to other devices rather than the broadcast manner that PCI operated in.
- *Nginx* was released.
- *pfSense* project started.
- *LUKS*(Linux Unified Key Setup) was launched, it is based on *TKS1* paper that was also released along with it.
- *dm-crypt* merged into Kernel 2.6.4. It resides entirely in kernel space, needs tools like cryptsetup and cryptmount to operate.
- *Netlink* was added to the Kernel. [[https://lwn.net/Articles/109191/][*libnl*]] was also added during this time.
- *Ubuntu* released by Canonical.

* 2003
:PROPERTIES:
:CUSTOM_ID: section-16
:END:
- *Piratebay* launched
- *I2P* was launched.
- 🇮🇳 NIXI was founded.
- *NFC* was approved by [[#1947][ISO]].
- *Metasploit* was created.
- *DTrace* was created by Bryan Cantrill and friends for [[#1991][Solaris]].
- *VLAN/802.1Q* was introduced to extend [[#1973][Ethernet]].
- *XEN* type-1 hypervisor was released.
- *DragonFly BSD* was released.
- *Linux Security Modules(LSM)* was merged into Linux.
- *SELinux* originally developed by [[#1952][NSA]] was merged into Linux Kernel.
- *Athlon64* the *first 64bit processor* was released by [[#1969][AMD]]

* 2002
:PROPERTIES:
:CUSTOM_ID: section-17
:END:
- *Tor* was released.
- *Winny* was released.
- Having your own Blog becomes hip.
- *Arch Linux* (my fav distro) released. Fight me.
- *PIR (Public Interest Registry)* created by [[#1992][ISOC]] to manage the .org top-level domain.

* 2001
:PROPERTIES:
:CUSTOM_ID: section-18
:END:
- *Bittorrent* developed by Bram Cohen.
- *Wikipedia* was launched by Jimmy Wales.
- *WaybackMachine* was launched by [[#1996][InternetArchive]] calling it the three dimensional index.
- *GNUNet* was announced.
- Douglas Crockford specified and popularized the *JSON*
- *CreativeCommons* was founded.
- *ext3* was introduced with journaling to the Linux Kernel.
- *Advanced Encryption Standard (AES)* spec(published in 1998) was established by [[#1901][*NIST*]]. It superseeded [[#1977][DES]] and is a symmetric-key algorithm. It later became an [[#1947][ISO]] and [[#1905][IEC]] standard and was approved by the [[#1952][NSA]] publicly.
- *LSB(Linux Standard Base)* was formed to preserve ABI between diffeerent Linux distributions.

* 2000
:PROPERTIES:
:CUSTOM_ID: section-19
:END:
- *Gnutella* was launched.
- *LimeWire* was launched.
- *LLVM* project started.
- *BIRD* Internet routing daemon project was started.
- *Netfilter* project was added to Linux kernel mainline. *iptables*'s father and grandfather were ipchains and ipfwadm.
- *Freenet* was launched with a goal to provide freedom of speech through a peer-to-peer network which focuses on protecting anonymity.
- *Dot-com bubble* burst.
- *Y2K* problem.
- *Folding@Home* was launched for performing molecular dynamics simulations of protein dynamics. The exaFLOP barrier was broken in March of [[#2020][2020]] due to [COVID19][#2020].
- *USB Flash Drives* were being sold for the first time.
- *SATA* was announced in 2000, in order to provide several advantages over the earlier PATA interface.

--------------

* 1999
:PROPERTIES:
:CUSTOM_ID: section-20
:END:
- *Napster*, developed by Shawn Fanning while still a freshman at Northeastern University.
- *RSS 0.9* was released.
- Initial version of *GNOME* was released.
- *SETI@Home* launches on 17 May and within four weeks its distributed Internet clients provide more computing power than the most powerful supercomputer of its time. It has the investigation of phenomena in interstellar space as its primary purpose. It shuts down in [[#2020][2020]].
- *GnuPG/GPG* was developed based on [[#1997][OpenPGP]], for =key= it supports [[#1985][Elgamal encryption]] and [[#1977][RSA]], for =signatures= it supports [[#1991][DSA]]. It supports many other algorithms for each step of [[#1991][PGP]] aswell.
- Common Vulnerabilities and Exposures *(CVE)* system was launched by [[#1978][Mitre Corporation]].
- *SSL* renamed to *TLS*
- [[#1995][OpenBSD]] created *OpenSSH* and released it.

* 1998
:PROPERTIES:
:CUSTOM_ID: section-21
:END:
- *ICANN* was founded.
- 🇮🇳 *ICICI* Bank introduced Internet Banking in India.
- *PayPal* was founded.
- Nick Szabo "designed" *Bit Gold*, which is considered the direct precursor to [[#2009][Bitcoin]].
- *LVM* was written.
- *VMware* was founded.
- *ISS* was launched.
- 🇮🇳 *C-DAC* was founded, currently falls under MeitY.
- *IPv6* was presented as a draft by [[#1986][IETF]].
- *XML 1.0* was specified.
- *DMCA* was introduced.
- [[https://en.wikipedia.org/wiki/Intelligent_Platform_Management_Interface#Version_history][*IPMI*]] was introduced by [[#1968][Intel.]]
- *CAP Theorem* was published by Eric Brewer.
- [[#1982][*iSCSI*]] was pioneered by IBM and Cisco.
- *OpenSSL* project was founded. It contains an open-source implementation of the [[#1995][TLS]] protocols.

* 1997
:PROPERTIES:
:CUSTOM_ID: section-22
:END:
- 🇮🇳 *TRAI* was founded.
- *Netflix* was started.
- *cURL* was released.
- *OpenPGP* was standardized by IETF when Zimmermann became convinced that an open standard for [[#1991][PGP encryption]] was critical.

* 1996
:PROPERTIES:
:CUSTOM_ID: section-23
:END:
- Yours truly was born. 👶
- *Internet Archive* was founded.
- *Google*(then BackRub) was founded.
- *KDE* was founded.
- *UML* was standardized.
- *Crash Bandicoot*, first ever 3D platform game was released with the PS1.
- *.png* was specified and became a [[#1994][W3C]]

* 1995
:PROPERTIES:
:CUSTOM_ID: section-24
:END:
- 🇮🇳 Internet came to India.
- *Calm Computing* was first mentioned by [[#1988][Mark Weiser]].
- *Java* was released by [[#1982][Sun]]
- *JavaScript* was released.
- *PHP* was released.
- 🇺🇸 *GPS* became fully functional, it was started in [[#1973][1973.]]
- CPAN was announced
- *Apache HTTP Server* was released.
- *WikiWikiWeb (c2)* the first ever wiki was launched. Was based and built by the developer of [[#1987][Hypercard.]]
- *Windows95* was released.
- *OpenBSD* was released by Theo de Raadt after getting removed from the [[#1993][NetBSD project.]]
- *IPsec* was standardaized by [[#1986][IETF]],It was a joint effort of many parties including [[#1958][ARPA]] and [[#1952][NSA]].
- *3DES* was released as [[#1977][DES]] is no longer considered adequate, 3DES inturn later was considered inadequate in 2016 when [[#1998][OpenSSL]] stopped including it because it was a "weak cipher".
- *SSL 2.0* and *HTTPS* released by Netscape. [[#1985][Taher Elgamal]] is considered the father of SSL.
- 🇫🇮 *SSH-1* was released as a freeware.
- Linux added ELF support, The Linux ELF format was chosen at 86open as the standard for x86 arch in 1999.

* 1994
:PROPERTIES:
:CUSTOM_ID: section-25
:END:
- *Yahoo* was founded.
- *BGP* RFC released, it supported *CIDR* and *Supernets*, a year later IPv6 BGP was defined.
- *Yahoo! GeoCities* web hosting service was launched. (Yahoo acc. 1999)
- *QR Code*(Matrix Barcode) was designed in Japan.
- *W3C* was founded.
- *Netscape* was founded, *Cookies* were introduced for Netscape Navigator. 🍪
- Shopping malls arrive on the Internet.
- *Amazon* was founded.
- *CSS* was proposed to the W3C.
- Compaq, DEC, IBM, Intel, Microsoft, NEC, and Nortel started working on *USB*. The goal was to make it fundamentally easier to connect external devices to PCs.
- *Redhat* was founded with *REHL*.
- Apple switched mac series from [[#1984][Motorola to PowerPC]] based processors.

* 1993
:PROPERTIES:
:CUSTOM_ID: section-26
:END:
- *Mosaic* was created by Marc Andreessen.
- *DHCP* rfc was published.
- *DOOM* was released.
- *CIDR* was introduced and Classful IP address was kind of deprecated.
- *Slackware* was created. *Debian* was also created around this time by Ian. [[https://upload.wikimedia.org/wikipedia/commons/1/1b/Linux_Distribution_Timeline.svg][The map.]]
- *Infrared Data Association (IrDA)* was founded.
- *LDAP* was developed.
- *mp3* coding format was developed based on modifications to [[#1973][LPC]].
- *NetBSD* and *FreeBSD* were put [[#1991][out independently.]]
- [[#1985][*NSFNet*]] was dissolved into the [[https://en.wikipedia.org/wiki/Network_access_point][commercial Internet.]]

* 1992
:PROPERTIES:
:CUSTOM_ID: section-27
:END:
- *Internet Society(ISOC)* was founded to promote "Internet is for Everyone".
- *Plan 9* was released.
- First *ThinkPad* was announced.
- Intel began working on *PCI*.
- *Mbone* was put on to test by [[#1988][Van Jacobson]] and Steve Deering.
- initial version of *ANTLR*(a parser generator) was released.
- *.jpeg* was specified.
- 🇨🇭 CCITT was renamed to Telecommunication Standardization Sector *(ITU-T)*. This org is pretty sick, it did the standardization of legends like JPEG(T.80), X.500, X.25, H.265 etc.
- [[https://tools.ietf.org/html/rfc1335][RFC1335]] discussed the idea of *Private IP Address* and *NAT* as solution to IP Exhaustion.

* 1991
:PROPERTIES:
:CUSTOM_ID: section-28
:END:
- *Line Mode Browser* was made available by Tim Lee and Nicola Pellow.
- *arXiv* was launched.
- *Linux kernel* was born.
- *Solaris* was released based on [[#1975][BSD]], [[#1983][SysV]] and Xenix.
- *Gopher* protocol was released.
- *Berlin Wall* was demolished.
- *The first commercial flash-based SSD* was shipped by SunDisk/SanDisk
- *PGP* was created by Phil Zimmermann. When Zimmermann faced criminal charges about the distribution of PGP, he published the entire source code of PGP in a hardback book via MIT Press, which was distributed and sold widely because export of books was protected by the First Amendment.
- *RADIUS* was developed an access server authentication and accounting protocol.
- =Cold War Ended.=
- BSD released *Net/2* which removed all *AT&T* related code from BSD. Here a fork was made for [[#1985][Intel80386]] called 386BSD; which was the basis of *FreeBSD* and *NetBSD*
- [[#1901][NIST]] proposed *DSA(Digital Signature Algorithm)* which was based on [[#1985][ElGamal signature scheme]].
- *Asynchronous transfer mode* was really popular, some people said it would beat IP.

* 1990
:PROPERTIES:
:CUSTOM_ID: section-29
:END:
- *Haskell* was born.
- *GNU Hurd* development started.

* 1989
:PROPERTIES:
:CUSTOM_ID: section-30
:END:
- *HTTP, HTML, WorldWideWeb(first browser)* came to be.
- *Bluetooth* (prev. short-link-radio) was developed.
- *EFF* was founded. Wozniak was a founding member.
- *SANS Institute* was founded.
- *GPLv1* was written my [[#1983][RMS]].
- *NFSv2* (Network File System) was released, [[#1981][RPC]] was the basis of it.
- [[#1984][Lamport]] talked about *Paxos* and it was [[http://lamport.azurewebsites.net/pubs/pubs.html#lamport-paxos][taken as a joke]], it was finally published again in [[#1998][1998]].
- *GNU Bison* was made compitable with [[#1975][YACC]] by RMS.
- *Casio F-91W* was introduced. (my watch ⏲)

* 1988
:PROPERTIES:
:CUSTOM_ID: section-31
:END:
- *IANA*(Now a function of ICANN) was founded.
- *IRC* was the created by Jarkko Oikarinen.
- *tcpdump* was written by Van Jacobson and friends, *traceroute* was also written by Van around this time.
- *Password shadowing* [[#1987][first appeared]] in Unix systems with the development of SunOS.
- Mark Weiser coined the term *ubiquitous computing/pervasive computing*
- 🇺🇸 *Morris worm* entered the internet.
- The first direct IP connection between Europe and North America was made.
- First *POSIX* standard document put out.
- Wolfram Mathematica was released.
- *RAID* was published as a paper by [[#1986][David Patterson]] and friends.

* 1987
:PROPERTIES:
:CUSTOM_ID: section-32
:END:
- Apple *HyperCard* was launched, it was among the first successful hypermedia systems predating the WWW.
- *GCC* was released by RMS from MIT.
- *FLEX*, an open source version of [[#1975][LEX]] was released.
- *MINIX* (a unix like academic os) based on *microkernel* was released by Tanenbaum.
- The author of the original Shadow Password Suite], Julie Haugh, experienced a computer break-in and wrote the initial release of the Shadow Suite containing the *login, passwd and su* commands.
- *Unicode* was born.

* 1986
:PROPERTIES:
:CUSTOM_ID: section-33
:END:
- *IMAP* came to be.
- *IETF* was officially founded.
- *Chernobyl disaster* happened.
- *GDB* was first written by [[#1983][RMS]] modeled after DBX from the original [[#1975][BSD]].
- *MX records* were introduced to allow non-IP network hosts to have domain addresses.
- First *3D Printer* was released.
- Joe Armstrong released *Erlang*.
- *SPARC* was released by [[#1982][Sun]] based on *Berkeley RISC*(led by David Patterson), another early RISC project was *MIPS*.
- Markus Hess hacked into the Pentagon and through the Tymnet(a network that used [[#1981][X.25]]), his activities were discovered by *Clifford Stoll!* at [[#1929][LBNL]] 👾 , the author of *The Cuckoo's Egg.*

* 1985
:PROPERTIES:
:CUSTOM_ID: section-34
:END:
- *BOOTP* was defined.
- *NSFNet* was launched after [[#1981][CSNET]]. (backbone speed of 56Kbps) it used the DEC LSI-11 based fuzzball router, [[#1981][Mills]] was involved. The *Fuzzball* router was one of te first routers to implement *VLSM* for addresses.
- *FSF* was founded.
- *Desktop Publishing(DTP)* took off with the addition of PostScript in Apple LaserWriter.
- *Microsoft Windows* was released.
- RMS published *GNU Manifesto* and mentioned the concept of *Copyleft*
- [[https://tools.ietf.org/html/rfc968][RFC968: 'Twas the Night Before Start-up']]
- Symbolics.com *the first domain* was registered.
- [[#1958][mitre]].org was the first .org domain name registered.
- Xilinx put out the first commercially available *FPGA*
- First *NUMA* based system was the XPS-100 by Dan Gielan. AMD added NUMA support in 2003 and Intel in 2007.
- [[#1968][Intel]] released the 80386 / i386, *the first x86 microprocessor* with a 32-bit instruction set and a memory management unit with paging.
- *ElGamal encryption system*(asymmetric key encryption algorithm) was defined by Taher Elgamal. It is based on the [[#1976][Diffie--Hellman]] key exchange.
- *ElGamal signature scheme* (a digital signature scheme) was also released during this time by Taher Elgamal.
- IEEE 754 standard for Floating-Point Arithmetic was established.

* 1984
:PROPERTIES:
:CUSTOM_ID: section-35
:END:
- *POP1* came to be.
- *BIND*(First Unix name server) was written by 4 UC Berkeley students, *DNS* was introduced. The =CLASS= record in DNS can be =IN=(for Internet), =HS=(for Hesiod from [[#1983][Project Athena]]) and =CH=(for [[#1975][Chaosnet]])
- *X Window System* idea was introduced.
- *Apple Macintosh* was released with "System 1"(MacOS) operating system(a GUI OS) with Motorola 68000.
- *MATLAB* was released.
- *Cisco* was founded.
- *LaTeX* was created by Leslie Lamport when working with [[#1978][TeX]].

* 1983
:PROPERTIES:
:CUSTOM_ID: section-36
:END:
- RMS announced his intent to start coding the *GNU Project* in a Usenet message.
- FidoNet(BBS software) developed by Tom Jennings.
- *Project Athena* a joint project of MIT, Digital Equipment Corporation, and IBM to produce a campus-wide distributed computing environment for educational use was launched.
- SysV(Unix System V) was released.
- 4.2BSD was released with *Berkeley sockets.*, the networking library was made opensource in [[#1989][1989]].
- *CeePlusPlus* was released.
- BBC started the *Computer Literacy Project* with Acorn Computers.
- Acorn Computers developed the the *first ARM chip*, currently "Arm Holdings" designs ARM processors. It was inspired by [[#1986][Berkeley RISC]].

* 1982
:PROPERTIES:
:CUSTOM_ID: section-37
:END:
- *SMTP* came to be.
- 🇬🇧 First Online banking service was launched.
- Sun Microsystems was co-founded by [[#1975][Bill Joy]].
- *ARPANET* switched from [[#1969][*NCP*]] to *TCP/IP*, [[#1981][IPv4]] was live.
- [[#1918][ANSI]] developed the initial *SCSI* spec. Boucher intended to be pronounced "sexy", but Dal Allan pronounced the new acronym as "scuzzy" and that stuck.
- *Commodore 64*(8bit home computer) was launched. It has been listed in the Guinness World Records as the highest-selling single computer model of all time.
- *EGP*(an obsolete routing protocol) was specified. [[#1981][Mills]] was involved. Exterior gateway protocols are also a type of routing protocols, hence the confusion.

* 1981
:PROPERTIES:
:CUSTOM_ID: section-38
:END:
- Internet Protocol [[https://tools.ietf.org/html/rfc791][RFC791]] was published.
- *ICMP* rfc was published, became part of the internet protocol suit.
- *CSNET* was launched.
- *NTP* (Network Time Protocol) was designed by David L. Mills.
- Osborne 1, first ever laptop was released.
- Flash Memory was invented based on [[/docs/notes/study/memory#eeprom][EEPROM]]
- More and more implementation of *RPC* were starting to show up.
- *X.25* one of the oldest packet-switching communication protocols was released. Early ATMs were using it. *X.25* was used up to [[#2015][2015]] (e.g. by the credit card payment industry) and is still used by aviation, purchasable from telecoms companies. It was standardadized by [[#1992][ITU-T]]. It was later replaced by *Frame Relay* which eventually was replaced by [[#1982][*TCP/IP*]]

* 1980
:PROPERTIES:
:CUSTOM_ID: section-39
:END:
- [[https://wiki.c2.com/?OnHolyWarsAndaPleaForPeace][On Holy Wars and a Plea For Peace]] was put out by [[#1973][Danny Cohen]] which introduced the terms *LittleEndian* and *BigEndian*
- *UDP* was designed by David P. Reed.
- [[https://en.wikipedia.org/wiki/IEEE_802][*IEEE802*]] a standard for networks carrying variable-size packets was introduced by [[#1964][IEEE]], it mapped to layer 1 and 2 of the [[#1978][OSI model.]], infact it divided Layer2 into LLC and MAC sublayers.

* 1979
:PROPERTIES:
:CUSTOM_ID: section-40
:END:
- *Usenet* (a semi p2p distributed messaging system using newsgroups) with [[#1976][UUCP]] was idealized. Usenet was the mom who birthed terms such as "FAQ", "flame", sockpuppet, and "spam". You know Usenet was the main deal.

* 1978
:PROPERTIES:
:CUSTOM_ID: section-41
:END:
- *Communicating sequential processes(CSP)* was described by Tony Hoare.
- *Introduction to [[#1964][VLSI systems]]* book was published which kicked off the [[https://en.wikipedia.org/wiki/Mead_%26_Conway_revolution][Mead & Conway revolution.]]
- *TeX* was developed by [[#1958][Donald Knuth.]]
- /Time, Clocks, and the Ordering of Events in a Distributed System/ was published by [[#1984][Lamport.]]
- *OSI Model* was first defined.
- Mitre Corporation (a non-profit) was founded, it contributed to the [[#1969][ARPANET]] and the National Airspace System(NAS).

* 1977
:PROPERTIES:
:CUSTOM_ID: section-42
:END:
- *Oracle* was founded.
- First *ACM ICPC*
- *DES*(symmetric-key block cipher) as approved as a federal standard though the controversies by [[#1901][NIST]], it was superseeded by [[#2001][AES]]
- Rivest after getting drunk, spent a night formalizing *RSA*(a asymmetric algorithm). /(Hope this is true story!)/
- Xerox Network Systems(XNS) was running, plausible competitor to IP was running. IEEE802 *MAC* addressing scheme comes from it.

* 1976
:PROPERTIES:
:CUSTOM_ID: section-43
:END:
- 🍎 *Apple* was founded, *Apple I* was on sale.
- 🇮🇳 *NIC* was founded.
- UUCP (Unix-to-Unix CoPy) developed at AT&T Bell Labs and distributed with UNIX.
- *vi* text editor was written by [[#1975][Bill Joy.]] and was added to 2BSD in [[#1979][1979]].
- *Diffie--Hellman key exchange* one of the first public-key protocols was published, but they left open the problem of realizing a one-way function, possibly because the difficulty of factoring was not well-studied at the time which was later resolved by [[#1977][RSA]].

* 1975
:PROPERTIES:
:CUSTOM_ID: section-44
:END:
- *Microsoft* was founded.
- *1BSD* was being worked on as an add-on to Version 6 Unix by Ken Thompson and Bill Joy.
- *Lex*(a lexer generator, proprietary) was released. It even became part of [[#1988][POSIX]] standard later.
- *YACC*(a parser generator, proprietary) was also released during this time and it became part of POSIX later.
- *CSMA* was put out based on [[#1970][previous work.]]
- *BIOS* first appeared in the CP/M operating system.
- Chaosnet was first developed by Thomas Knight and Jack Holloway at MIT's AI Lab.

* 1974
:PROPERTIES:
:CUSTOM_ID: section-45
:END:
- *TCP/IP* was birthed by Bob Kahn and Vint Cerf; The initial docs contained the first attested use of the term Internet, as a shorthand for /internetworking/.
- *Altair 8800*(microcomputer) was designed based on the [[#1970][Intel8080]], the differentiating factor with Kenbak-1 might have been the extensibility of the Altair. Gates and Allen started working on the interpreter. *S-100 bus*, the first industry standard expansion bus was designed for it aswell.
- *Arecibo message* was sent by Frank Drake and Carl Sagan.
- Foxconn was founded in China.

* 1973
:PROPERTIES:
:CUSTOM_ID: section-46
:END:
- 📱*First mobile phone* call made by Martin Cooper of Motorola.
- *Reliance* was started as a textile company. 🇮🇳
- First real-time two-way [[#1966][LPC packet speech communication]] was accomplished, the basis of *VoIP*, Danny Cohen was involved.
- [[#1970][Xerox]] came with the *first computer with a mouse and gui: Xerox Alto*.
- *C Programming Language* was [[#1969][birthed]] by [[#1969][Dennis Ritchie.]]
- *Community Memory (CM)* the first BBS was built.
- *Ethernet* idea was outlined by Robert(Bob) Metcalfe.
- *Actor Model* was defined by Hewitt.

* 1972
:PROPERTIES:
:CUSTOM_ID: section-47
:END:
- Alan Kay put out the idea of the *Dynabook.*
- Alan Kay released *Smalltalk*, the language that popularized the idea of OOP.

* 1971
:PROPERTIES:
:CUSTOM_ID: section-48
:END:
- First email was sent by Ray Tomlinson.
- First online transaction happened MIT/Stanford 🍀
- First commercially available *Floppy Disk* was released.
- *Intel4004* - First commercially available microprocessor.
- The *first handheld calculator* was made with the designs of 4004 by Intel and Busicom. People now no longer need to use [[#1614][log tables]] to do huge multiplications!
- *Creeper the first virus*, met the internet.
- *Project Gutenberg* is started by Michael Hart with the purpose of making copyright-free works electronically available.
- *Unix* was born, witten in assembly with three parts assembler, [[#1969][editor]], and shell.
- *CYCLADES* project was launched.

* 1970
:PROPERTIES:
:CUSTOM_ID: section-49
:END:
- *Datapoint 2200* came out, which inspired the design of the Intel8080.
- Edgar F. Codd(IBM) proposed the *relational model* and relational algebra.
- *B-tree* datastructure was described.
- *Xerox* was founded.
- ALOHAnet, the *first packet radio network* was announced.
- *ISBN* was standardized by [[#1947][ISO]]
- *B-trees* was invented.

* 1969
:PROPERTIES:
:CUSTOM_ID: section-50
:END:
- *ARPANET*, the first wide-area packet-switching network came to be. It originally used *NCP(Network Control Protocol)*.
- *Ed* text-editor was put out by Dennis Ritchie and Ken Thompson at [[#1925][Bell Labs]].
- *TELNET* was released.
- 🇮🇳🚀 *ISRO* was founded.
- 🌔 *Commander Neil Armstrong* and lunar module pilot Buzz Aldrin landed on Moon.
- 🇺🇸 *AMD* was founded.

* 1968
:PROPERTIES:
:CUSTOM_ID: section-51
:END:
- 🇺🇸 *Intel Corporation* was co-founded by [[#1959][Robert Noyce]].
- *Software Crisis* term was coined.
- *EP-101*, the first printer invented by Japanese company Epson.
- *oN-Line System(NLS)* was developed by Douglas Engelbart. It can be considered a precursor to the [[#1989][WWW]].
- *The Mother of All Demos* by Douglas, He demonstrated almost all the fundamental elements of modern personal computing: windows, hypertext, graphics, efficient navigation and command input, video conferencing, the computer mouse, word processing, dynamic file linking, revision control, and a collaborative real-time editor (collaborative work).
- 🇮🇳 *RAW* was founded.

* 1966
:PROPERTIES:
:CUSTOM_ID: section-52
:END:
- *Flynn's taxonomy* were stated by Michael J. Flynn.
- *linear predictive coding (LPC)* introduced by Fumitada Itakura.

* 1965
:PROPERTIES:
:CUSTOM_ID: section-53
:END:
- 🇺🇸 Vietnam War
- Edsger Wybe Dijkstra introduced *concurrency* is when stating the mutual exclusion problem.
- Gordon Moore stated *Moore's Law.* 2x Transistor/Chip every 1.5 years.

* 1964
:PROPERTIES:
:CUSTOM_ID: section-54
:END:
- *Quark Model* was introduced to the world.
- *IEEE* was founded.
- *IBM System/360* mainframe computer was announced, Fred Brooks coined *computer architecture*. Used design features from the Stretch.
- *Dartmouth Time-Sharing System (DTSS)* the first successful large-scale time-sharing system was built.
- *BASIC* was released, BASIC had a bigger social impact. It brought programming to households, kids especially. It was initially built for the DTSS.
- Sketchpad computer program was written by Ivan Sutherland on [[#1956][TX-2]] with a LightPen. Computers were still mostly using punched cards or magnetic tape for batch job. This is considered as the *birth of GUI.*
- General Microelectronics(GMe) introduced the first commercial [[#1959][MOS integrated circuit]], this *paved the way for VLSI.*

* 1961
:PROPERTIES:
:CUSTOM_ID: section-55
:END:
- *Berlin Wall* was built.
- *CTSS*, the first time sharing operating system was built, DTSS followed soon.
- *Spacewar!*, the first computer game was run on a [[#1957][DEC PDP-1]].
- Paul Baran, Donald Davies, independently kind of put out the idea of *packet-switching*. Leonard Kleinrock establish a mathematical theory of packet networks using [[#1909][queuing theory]]
- IBM 7030 Stretch was launched which *standardized on an 8-bit byte and power-of-two word length*, before which byte referred to the group of bits encoding a character, even if it [[https://www.reddit.com/r/askscience/comments/3b6lkz/why_is_it_that_the_de_facto_standard_for_the/][wasn't 8 bits.]]

* 1960
:PROPERTIES:
:CUSTOM_ID: section-56
:END:
- *SI Unit System* was born.
- *ASCII* was initially used.
- *COBOL* was released, shaped by the business/science split in computing.
- *ALGOL* was released, the committee wanted to make a good language for researching algorithms.

* 1959
:PROPERTIES:
:CUSTOM_ID: section-57
:END:
- 🇨🇺 *Fidel Castro* became PM of cuba.
- 🇮🇳 [[#1927][Television]] came to India.
- The *MOSFET* (metal-oxide-semiconductor field-effect transistor) was invented.
- 🇺🇸 Robert Noyce invented the first *monolithic IC chip.*
- The term *Machine Learning* was coined.

* 1958
:PROPERTIES:
:CUSTOM_ID: section-58
:END:
- 🇺🇸🚀 *NASA* was founded.
- *DARPA* was founded.
- [[#1956][John McCarthy]] developed *Lisp.* It was the *first language to have a garbage collector*. It was the first to have a REPL. And it was the first to support dynamic typing.
- Donald Knuth coined the term *coroutine*.

* 1957
:PROPERTIES:
:CUSTOM_ID: section-59
:END:
- 🇷🇺 World's first artificial Earth satellite, *Sputnik 1* was launched by USSR.
- *FORTRAN* was written at IBM.
- *DEC* the minicomputer maker company was founded. They made *PDP* and *VAX*, later acc. by Compaq in 1998.
- *First hard disk drive(HDD)* shipped by IBM; in succession to [[#1951][tape drives]].

* 1956
:PROPERTIES:
:CUSTOM_ID: section-60
:END:
- John McCarthy coined the term *Artificial Intelligence*
- 🇮🇳 *TIFRAC*(vacuum tube), the first computer developed in india.
- 🇺🇸 *TX-0*(transistor) computer was released, it and its decendents became platforms for pioneering computer research and the development of what would later be called computer "hacker" culture.
- Noam Chomsky described the *Chomsky hierarchy*

* 1955
:PROPERTIES:
:CUSTOM_ID: section-61
:END:
- *HEC 2M* was the first computer bought by [[#1953][Indian Statistical Institute, Kolkata]].
- *Magnetic-core memory* [[#1947][RAM]] was introduced, it was part of a family of related technologies which *bridged the gap between vacuum tubes and semiconductors.*

* 1954
:PROPERTIES:
:CUSTOM_ID: section-62
:END:
- *CERN* was founded. 🌠
- *TRADIC*, first transistorized computer was completed.

* 1953
:PROPERTIES:
:CUSTOM_ID: section-63
:END:
- ISI, Kolkata developed an Analog Computer, probably the first ever in India.
- *Karnaugh map(K-map)* was introduced to as a method of simplifying [[#1855][Boolean algebra expressions.]]

* 1952
:PROPERTIES:
:CUSTOM_ID: section-64
:END:
- 🇺🇸 NSA was founded

* 1951
:PROPERTIES:
:CUSTOM_ID: section-65
:END:
- *IIT Kharagpur*, first IIT was setup.
- Stephen Kleene described *regular languages and regular expressions.*
- *Barcode* was patented, it was base on [[#1837][Morse Code.]]
- *First computer tape drive*, Remington Rand was put out.

* 1950
:PROPERTIES:
:CUSTOM_ID: section-66
:END:
- Bertie the Brain was one of the *first game playing machines* developed.

* 1949
:PROPERTIES:
:CUSTOM_ID: section-67
:END:
- [[#1948][Shannon]] published "A mathematical theory of cryptography", starting point of *modern cryptography*.

* 1948
:PROPERTIES:
:CUSTOM_ID: section-68
:END:
- [[#1945][John von Neumann]] put down the first academic work on [[#1971][self replicating programs]].
- *The Shannon-Hartley Theorem* was stated by Claude Shannon. If I need to go faster, I need more bandwidth.
- *World Health Organization* was founded.
- 🇬🇧 *Manchester Baby* world's first electronic *stored-program computer* to test [[#1947][Williams Tube]]
- 🇺🇸 First commercial *PCB(Printed Circuit Board)* was made.
- *RFID* idea was first written about, first actual demo was in 1973.

* 1947
:PROPERTIES:
:CUSTOM_ID: section-69
:END:
- 🇮🇳 *India* is finally Independent of British rule.
- *Transistor* was invented in [[#1925][Bell Labs]].
- =Cold War Started.=
- First practical form of *random-access memory*, Williams tube based on cathode-ray tubes was invented.
- 🇨🇭 *ISO*(International Organization for Standardization) was founded.
- *ACM(Association for Computing Machinery)* was founded.

* 1946
:PROPERTIES:
:CUSTOM_ID: section-70
:END:
- 🇺🇸 *ENIAC*(used vacuum tubes, turing complete) the first electronic general-purpose digital computer was built.
- 🇮🇳 *Indian Standards Institution(ISI)* was founded which was later rebranded into Bureau of Indian Standards in [[#1986][1986]]

* 1945
:PROPERTIES:
:CUSTOM_ID: section-71
:END:
- =☮️ WW-II Ended.=, 50-80mn died. U.S.S.R. declares victory over Nazi Germany.
- =Fat Man= and =Little Boy= were dropped.
- Korea divided into North Korea and South Korea.
- *United Nations* was formed.
- *World Bank* was formed.
- *UNICEF* was founded.
- 🇺🇸 The idea of the *memex*(a proxy for our human memories) was introduced by [[#1942][Vannevar Bush]] which influenced the [[#1989][WWW]].
- 🇺🇸 John von Neumann introduced the *von Neumann architecture* in the first draft of EDVAC.

* 1944
:PROPERTIES:
:CUSTOM_ID: section-72
:END:
- *IBM Harvard Mark I*(electromechanical computer) was introduced. It stated the *Harvard Architecture*, [[#1945][John von Neumann]] ran one of the first program on it.

* 1942
:PROPERTIES:
:CUSTOM_ID: section-73
:END:
- 🇺🇸 *Manhattan Project* was started, [[#1945][Sir John]] was working on it aswell.
- Enrico Fermi let the team for the first artificial [[#1933][nuclear reactor]], Chicago Pile-1.
- 🇩🇪 Z4, arguably the world's first commercial digital computer was built. Also the first commercial computer with floating-point hardware.

* 1941
:PROPERTIES:
:CUSTOM_ID: section-74
:END:
- 🇩🇪 The first general-purpose non-electronic computer *Z3* was actually built based on the design of the [[#1837][Analytical Engine]], it was destroyed during *WW-II*

* 1939
:PROPERTIES:
:CUSTOM_ID: section-75
:END:
- =🔫 WW-II started= by Germany in an unprovoked attack on Poland.

* 1938
:PROPERTIES:
:CUSTOM_ID: section-76
:END:
- 🇺🇸 *Molecular biology* term was coined.
- Carl Adam Petri invented *Petri Net* at the age of 13.

* 1937
:PROPERTIES:
:CUSTOM_ID: section-77
:END:
- [[#1948][Shannon]] formalized the application of [[#1855][Boolean algebra]] to [[#1835][Electromagnetic Relays]]. Eventually, vacuum tubes replaced relays for logic operations.

* 1936
:PROPERTIES:
:CUSTOM_ID: section-78
:END:
- Alan Turing invented the *Turing Machine.* It suggested that a machine, by shuffling symbols as simple as "0" and "1", could simulate any conceivable act of mathematical deduction.

* 1934
:PROPERTIES:
:CUSTOM_ID: section-79
:END:
- NEC engineer Akira Nakashima's introduced *switching circuit theory.*

* 1933
:PROPERTIES:
:CUSTOM_ID: section-80
:END:
- Hitler was made chancellor of Germany.
- *Neutron* was discovered by James Chadwick.
- Idea of *Neuclear Reactor* came to Szilárd's mind.
- *lambda calculus* was invented by Alonzo Church.

* 1929
:PROPERTIES:
:CUSTOM_ID: section-81
:END:
- *The Great Depression* beginning in the United States.
- Ernest O. Lawrence built *Cyclotron* and founded the Lawrence Berkeley National Laboratory(LBNL) commonly known as the Berkeley Lab.

* 1927
:PROPERTIES:
:CUSTOM_ID: section-82
:END:
- 🇺🇸 Television was invented
- 🔅 *LED* was invented.

* 1926
:PROPERTIES:
:CUSTOM_ID: section-83
:END:
- Erwin Schrödinger described the *quantum mechanical model of the atom* based off [[#1925][uncertainty principle]]

* 1925
:PROPERTIES:
:CUSTOM_ID: section-84
:END:
- 🇺🇸 AT&T Bell labs was founded.
- Heisenberg's put out his *Uncertainty principle*

* 1924
:PROPERTIES:
:CUSTOM_ID: section-85
:END:
- Stallin takes over the USSR.
- de Broglie discovers *matter waves*.
- Idea of Galaxy was introduced.

* 1923
:PROPERTIES:
:CUSTOM_ID: section-86
:END:
- Hitler joined/formed Nazi Party, inspired by [[#1922][Benito]].

* 1922
:PROPERTIES:
:CUSTOM_ID: section-87
:END:
- 🇮🇹 Benito Mussolini became PM and formed National Fascist Party.

* 1921
:PROPERTIES:
:CUSTOM_ID: section-88
:END:
- 🇨🇳 Inspired by the Russian Revolution, *The Communist Party of China* is formed.

* 1918
:PROPERTIES:
:CUSTOM_ID: section-89
:END:
- =☮️ WW-I Ended.=, 17mn died, 20mn wounded.
- The *first flip-flop* was invented and consisted of two vacuum tubes. It is a circuit that has two stable states and can be used to store state information.
- *ANSI* was founded.

* 1917
:PROPERTIES:
:CUSTOM_ID: section-90
:END:
- The Russian Revolution began, Vladimir Lenin(The Red Army) at the helm, the Bolsheviks, ascribing to Marxism, seize power during Russia's October Revolution and become the *first communist government.*

* 1916
:PROPERTIES:
:CUSTOM_ID: section-91
:END:
- *Chemical Bondings* were explained.
- *General Relativity* was explained by Einstein.

* 1914
:PROPERTIES:
:CUSTOM_ID: section-92
:END:
- =🔫 WW-I started.= because of assassination of the Archduke Franz.

* 1913
:PROPERTIES:
:CUSTOM_ID: section-93
:END:
- *Isotopes* were discovered.
- *Bohr Model* of an Atom was proposed by Bohr(student of [[#1909][Rutherford]]).
- Ramanujan wrote to G.H Hardy.

* 1912
:PROPERTIES:
:CUSTOM_ID: section-94
:END:
- Idea of *continental drift* was proposed by Alfred Wegener. (Pangea)

* 1911
:PROPERTIES:
:CUSTOM_ID: section-95
:END:
- *IBM*(International Business Machines) was founded.

* 1909
:PROPERTIES:
:CUSTOM_ID: section-96
:END:
- 🇬🇧 Ernest Rutherford discovered the *nucleus and proton* with the goldfoil experiment.
- Agner Krarup Erlang published first piece on *Queueing theory.*
- 🇬🇧 MI5 was founded.

* 1905
:PROPERTIES:
:CUSTOM_ID: section-97
:END:
- *Special Relativity* and *Photoelectric effect* were introduced by Einstein.
- 🇬🇧 International Electrotechnical Commission(IEC) was founded.

* 1903
:PROPERTIES:
:CUSTOM_ID: section-98
:END:
- 🛬 The Wright Brothers did their thing.

* 1901
:PROPERTIES:
:CUSTOM_ID: section-99
:END:
- 🇺🇸 Institute of Standards and Technology (*NIST*) was founded. From 1901--1988, the agency was named the *National Bureau of Standards.(NBS)*

* 1900
:PROPERTIES:
:CUSTOM_ID: section-100
:END:
- Max Plank laid foundation of *Quantum Theory*.

--------------

* 1898
:PROPERTIES:
:CUSTOM_ID: section-101
:END:
- Marie curie discover *radium.*

* 1897
:PROPERTIES:
:CUSTOM_ID: section-102
:END:
- 🇬🇧 Following up on [[#1803][Dalton]], J.J Thompson discovered *electron* using the Cathod Ray tube experiment.

* 1895
:PROPERTIES:
:CUSTOM_ID: section-103
:END:
- *Lorentz Force* is defined.
- *X-ray* was discovered.
- Guglielmo Marconi developed the first practical *radio transmitters*
- *Millimetre wave communication* was first investigated by Jagadish Chandra Bose.

* 1891
:PROPERTIES:
:CUSTOM_ID: section-104
:END:
- *Stanford* was founded.

* 1887
:PROPERTIES:
:CUSTOM_ID: section-105
:END:
- Hertz produced [[#1855][*radio waves*]] for the first time, giving bith to Electromagnetic radiation.

* 1885
:PROPERTIES:
:CUSTOM_ID: section-106
:END:
- 🚗 First Car

* 1884
:PROPERTIES:
:CUSTOM_ID: section-107
:END:
- Alexander Graham Bell, Chichester Bell and Charles Sumner Tainter recorded sound on a glass disc using a beam of light.

* 1879
:PROPERTIES:
:CUSTOM_ID: section-108
:END:
- 🇺🇸 Thomas Edison was finally able to produce a reliable, long-lasting electric light 💡 in his laboratory.

* 1876
:PROPERTIES:
:CUSTOM_ID: section-109
:END:
- 🇺🇸 Telephone call by Alexander Graham Bell.

* 1874
:PROPERTIES:
:CUSTOM_ID: section-110
:END:
- 🇩🇪 *Set Theory* was introduced by Georg Cantor.

* 1869
:PROPERTIES:
:CUSTOM_ID: section-111
:END:
- 🇷🇺 Dimitri Mendeleev developed the *Periodic Table.*

* 1861
:PROPERTIES:
:CUSTOM_ID: section-112
:END:
- 🇺🇸 William Barton Rogers founded *MIT*

* 1859
:PROPERTIES:
:CUSTOM_ID: section-113
:END:
- *Theory of Evolution* was stated by Darwin.

* 1856
:PROPERTIES:
:CUSTOM_ID: section-114
:END:
- *ETH Zurich* was founded.

* 1855
:PROPERTIES:
:CUSTOM_ID: section-115
:END:
- *Maxwell equations*([[#1671][differential eqns]]) somewhat came into existence influenced by [[#1831][Faraday's work]], it also predicted the possibility of *Radio Waves.*
- *Boolean Algebra* was described by George Boole.

* 1843
:PROPERTIES:
:CUSTOM_ID: section-116
:END:
- Augusta Ada Lovelace transcribed the Analytical Engine and she is now termed as the *first programmer ever*. She met Babbage when she was 17. She was 23 when she did this.

* 1848
:PROPERTIES:
:CUSTOM_ID: section-117
:END:
- Karl Marx and Friedrich Engels publish *The Communist Manifesto*

* 1845
:PROPERTIES:
:CUSTOM_ID: section-118
:END:
- 🇩🇪 Kirchhoff's circuit laws were defined.

* 1844
:PROPERTIES:
:CUSTOM_ID: section-119
:END:
- First Morse code message with the telegraph was sent, /"WHAT HATH GOD WROUGHT"/

* 1840
:PROPERTIES:
:CUSTOM_ID: section-120
:END:
- *Industrial revolution* ends.

* 1837
:PROPERTIES:
:CUSTOM_ID: section-121
:END:
- 🇬🇧 *Analytical Engine* was designed by Charles Babbage. Babbage was never able to complete construction of any of his machines due to conflicts with his chief engineer and inadequate funding.
- 🇺🇸 Morse developed an early forerunner to the modern *International Morse code.*
- Morse ft. [[#1832][Henry]] and Vail patented the *electronic telegraph.*

* 1836
:PROPERTIES:
:CUSTOM_ID: section-122
:END:
- Farady constructed *Faraday cage.*

* 1835
:PROPERTIES:
:CUSTOM_ID: section-123
:END:
- [[#1832][Henry]] invented the *Electromechanical Relay.(EMR)*

* 1832
:PROPERTIES:
:CUSTOM_ID: section-124
:END:
- 🇺🇸 Joseph Henry discovered *electromagnetic induction* independent of Faraday.

* 1831
:PROPERTIES:
:CUSTOM_ID: section-125
:END:
- 🇬🇧 Michael Faraday discovered *electromagnetic induction.*

* 1827
:PROPERTIES:
:CUSTOM_ID: section-126
:END:
- 🇩🇪 Georg Ohm wrote about *Ohm's Law*, the [[#1820][galvanometer]] helped him.

* 1825
:PROPERTIES:
:CUSTOM_ID: section-127
:END:
- *Camera* was invented.

* 1824
:PROPERTIES:
:CUSTOM_ID: section-128
:END:
- William Sturgeon invented *electromagnets*.

* 1823
:PROPERTIES:
:CUSTOM_ID: section-129
:END:
- Berzelius discovers *silicon (Si)*, It being a semiconductor is a critical element for fabricating most electronic circuits.

* 1822
:PROPERTIES:
:CUSTOM_ID: section-130
:END:
- Joseph Fourier laid the foundations of *Fourier transform* when exploring the Heat Eqn.

* 1821
:PROPERTIES:
:CUSTOM_ID: section-131
:END:
- 🇬🇧 Michael Faraday showed continuous *electromagnetic rotation* based on work of [[#1819][Ørsted]] and [[#1820][Ampere]]

* 1820
:PROPERTIES:
:CUSTOM_ID: section-132
:END:
- 🇫🇷 André-Marie Ampère put together *Ampère's law* (a single mathematical form to represent the magnetic forces between current-carrying conductors), influenced by [[#1819][Ørsted's work.]]
- Followed by [[#1819][Ørsted's work]], *galvanometer* was invented.

* 1819
:PROPERTIES:
:CUSTOM_ID: section-133
:END:
- 🇩🇰 *Electromagnitism*(i.e e-current produce magnetic fields) discovered by Hans Christian Ørsted

* 1804
:PROPERTIES:
:CUSTOM_ID: section-134
:END:
- 🚃 First steam locomotive railway known as Penydarren was built, it was possible because of the expiery of the patent on the [[#1775][Watt steam engine.]]

* 1803
:PROPERTIES:
:CUSTOM_ID: section-135
:END:
- 🇬🇧 John Dalton proposed the idea of the *Atom.*
- *Wave theory of light* was introduced with the double-slit experiment.

* 1800
:PROPERTIES:
:CUSTOM_ID: section-136
:END:
- 🇮🇹 Alessandro Volta invented the *Voltaic pile*. 🔋 (First electric battery)

--------------

* 1789
:PROPERTIES:
:CUSTOM_ID: section-137
:END:
- The first modern list of chemical elements -- containing 33 elements was put together by A. Lavoisier.

* 1785
:PROPERTIES:
:CUSTOM_ID: section-138
:END:
- 🇫🇷 *Coulomb's law* was stated.

* 1775
:PROPERTIES:
:CUSTOM_ID: section-139
:END:
- Watt worked on the *Watt steam engine*, really gave some boost to the IR.

* 1760
:PROPERTIES:
:CUSTOM_ID: section-140
:END:
- 🇬🇧 *Industrial revolution* starts.

* 1752
:PROPERTIES:
:CUSTOM_ID: section-141
:END:
- 🇺🇸 *Benjamin Franklin* flew a kite in a stormy night and stored electricity in Leyden jar from lightning.

* 1746
:PROPERTIES:
:CUSTOM_ID: section-142
:END:
- The first ever *capacitor*, Leyden Jar was developed.

* 1739
:PROPERTIES:
:CUSTOM_ID: section-143
:END:
- [[#1736][Leonhard Euler]] applied binary [[#1614][logarithms]] to music theory.

* 1736
:PROPERTIES:
:CUSTOM_ID: section-144
:END:
- Leonhard Euler published *Seven Bridges of Königsberg*.

* 1710
:PROPERTIES:
:CUSTOM_ID: section-145
:END:
- 🇬🇧 *Statute of Anne/Copyright Act 1710* was enacted, which other countries later copied.

* 1705
:PROPERTIES:
:CUSTOM_ID: section-146
:END:
- *Binary Number System* was redefined by [[#1675][Leibniz]]

--------------

* 1686
:PROPERTIES:
:CUSTOM_ID: section-147
:END:
- Newton's law of *universal gravitation* was described.

* 1676
:PROPERTIES:
:CUSTOM_ID: section-148
:END:
- *Speed of light* was determined.

* 1675
:PROPERTIES:
:CUSTOM_ID: section-149
:END:
- 🇩🇪 Leibniz introduced the *Integral sign ∫*

* 1671
:PROPERTIES:
:CUSTOM_ID: section-150
:END:
- *Differentail Equations* were first mentioned Method of Fluxions by Newton.

* 1669
:PROPERTIES:
:CUSTOM_ID: section-151
:END:
- *Phosphorus*, it was the first element to be discovered since ancient times.

* 1666
:PROPERTIES:
:CUSTOM_ID: section-152
:END:
- *Laws of Motion* were introduced by 23y/o Issac Newton.

* 1665
:PROPERTIES:
:CUSTOM_ID: section-153
:END:
- 🇬🇧 *Calculus* was introduced by Issac Newton.
- Robert Hooke coined the term *cell* for describing biological organisms in his book Micrographia.

* 1647
:PROPERTIES:
:CUSTOM_ID: section-154
:END:
- *Pascal's Law* was stated.

* 1636
:PROPERTIES:
:CUSTOM_ID: section-155
:END:
- *Harvard University* was founded.

* 1621
:PROPERTIES:
:CUSTOM_ID: section-156
:END:
- *Snell's law*, law of reflection was described.

* 1614
:PROPERTIES:
:CUSTOM_ID: section-157
:END:
- John Napier introduced *Logarithm* as a means of simplifying calculations.

* 1600
:PROPERTIES:
:CUSTOM_ID: section-158
:END:
- William Gilbert discovered *Earth's magnetic field.*

--------------

* 1582
:PROPERTIES:
:CUSTOM_ID: section-159
:END:
- 🇮🇹 *Gregorian calendar* was introduced.

* 1545
:PROPERTIES:
:CUSTOM_ID: section-160
:END:
- *Complex numbers* were discovered by Gerolamo Cardano.

--------------

* 1440
:PROPERTIES:
:CUSTOM_ID: section-161
:END:
- 🇩🇪 *Gutenberg* invented the Printing press.

--------------

* 499 CE
:PROPERTIES:
:CUSTOM_ID: ce
:END:
- Aryabhatta existed.

--------------

* 5 CE
:PROPERTIES:
:CUSTOM_ID: ce-1
:END:
- Pāṇini formulated the grammar of *Sanskrit* in 3959 rules known as the Ashtadhyayi.

--------------

* 250 BCE
:PROPERTIES:
:CUSTOM_ID: bce
:END:
- Archimedes was alive and calculated the value of *π.*

--------------

* 300 BCE
:PROPERTIES:
:CUSTOM_ID: bce-1
:END:
- *Euclid of Alexandria*, the father of geometry was alive and kicking.

--------------

* 2700 BCE
:PROPERTIES:
:CUSTOM_ID: bce-2
:END:
- Abacus was developed in Sumer(Iraq)

--------------

* Links
- [[https://www.zakon.org/robert/internet/timeline/#1970s][Long Internet History Timeline]]
- [[http://ascii.textfiles.com/][ASCII by James Scott]]
- [[https://github.com/watson/awesome-computer-history][Awesome Computer History]]
- [[https://news.ycombinator.com/item?id=39185933][Pub400.com – Your public IBM I 7.5 server | Hacker News]]
- [[https://jeffreykegler.github.io/personal/timeline_v3][Parsing Timeline]]
- [[http://atariemailarchive.org/][Atari Email Archive - A collection of messages sent at Atari from 1983 to 1992.]]
- [[https://www.lesswrong.com/posts/vfRpzyGsikujm9ujj/a-brief-history-of-computers][A brief history of computers — LessWrong]]
- [[https://www.filfre.net/2017/10/a-net-before-the-web-part-1-the-establishment-man-and-the-magnificent-rogue/][A Net Before the Web, Part 1: The Establishment Man and the Magnificent Rogue]]
- [[https://en.wikipedia.org/wiki/Timeline_of_the_far_future][Timeline of the far future]]
- [[http://museum.ipsj.or.jp/en/computer/index.html][Historical Computers in Japan]]
- [[http://blogs.perl.org/users/jeffrey_kegler/2014/09/parsing-a-timeline.html][Parsing Timeline]]
- https://computer.rip/
- https://buttondown.email/hillelwayne/archive/oracle-testing/
- https://lobste.rs/s/ovjvzl/babbage_was_true_genius
- http://exple.tive.org/blarg/2020/11/26/punching-holes/
- https://obsoletemedia.org/
- [[https://samthursfield.wordpress.com/2020/10/27/tracker-3-0-how-did-we-get-here/][Tracker 3.0: How did we get here? – Sam Thursfield]]
- https://wiki.archiveteam.org/index.php?title=Main_Page
- https://worldwideweb.cern.ch/worldwideweb/
- https://www.hanselman.com/blog/i-miss-microsoft-encarta
- https://bits.ashleyblewer.com/halt-and-catch-fire-syllabus/
- http://www.zonicweb.net/badalbmcvrs/index.htm
- https://archive.org/details/consolelivingroom
- http://www.dansmc.com/MC_repaircourse.htm
- https://www.msgroup.org/
- https://archive.org/details/softside-magazine-59/page/n9/mode/2up
- https://webdevelopmenthistory.com/index/
- [[https://www.folklore.org/StoryView.py?project=Macintosh&story=Apple_II_Mouse_Card.txt][Folklore.org: Apple II Mouse Card]]
- https://compositor.bham.ac.uk/
- http://hccc.org.uk/retro/retro.html
- http://cyber.dabamos.de/88x31/ nice
- https://github.com/bagder/irchistory
- https://lobste.rs/s/ow3nhn/what_is_your_oldest_living_presence_on
- https://www.pldi21.org/prerecorded_hopl.11.html
- https://liam-on-linux.livejournal.com/81341.html
- [[https://thehistoryoftheweb.com/a-fun-list-of-browsers-youve-never-heard-of/][A Fun List of Browsers You’ve Never Heard Of - The History of the Web]]
- https://webdevelopmenthistory.com/
- https://www.cpushack.com/
- https://bytecellar.com/
- https://www.os2museum.com/wp/
- https://obscuritory.com/
- https://news.ycombinator.com/item?id=28280051
- http://webseitz.fluxent.com/wiki/HistoryOfThe21stCenturyIn100Objects
- https://www.historyofinformation.com/index.php
- https://twitter.com/jschauma/status/1480391335634997248
- https://twitter.com/krishashok/status/1475009729726349312
- https://github.com/simh/simh
- https://github.com/JesseKPhillips/USA-Constitution
- https://github.com/2d-inc/HistoryOfEverything
- https://github.com/worrydream/EarlyHistoryOfSmalltalk
- https://github.com/mraible/history-of-web-frameworks-timeline
- https://github.com/michael-lazar/finger2020
- http://www.uchronia.net/ (alternate hstory genere books)
- https://tiemoko.com/blog/vintage-tech-books/
- https://patrickcollison.com/svhistory
- http://www.eightyeightynine.com/culture/80susenet.html
- https://www.flashgamehistory.com/
- https://www.glitchwrks.com/vintage.html
- https://peabee.substack.com/p/15-mafatlal-and-the-early-indian
- https://www.livinginternet.com/
- https://gracesguide.co.uk/Main_Page
- https://dfarq.homeip.net/how-much-did-vhs-tapes-cost-in-the-80s/
- https://github.com/watson/awesome-computer-history
- https://codewords.recurse.com/issues/seven/a-history-of-storage-media
- https://daniel.haxx.se/irchistory.html
- https://webaim.org/blog/user-agent-string-history/
- https://segment.com/blog/a-brief-history-of-the-uuid/
- [[https://ploum.net/2022-12-03-reinventing-how-we-use-computers.html][Reinventing How We Use Computers]]
- [[https://en.wikipedia.org/wiki/List_of_Internet_pioneers][List of Internet pioneers - Wikipedia]]
- [[https://eylenburg.github.io/browser_engines.htm][History of Web Browser Engines from 1990 until today]]
- [[https://worldradiohistory.com/Byte_Magazine.htm][BYTE MAGAZINE: Early computer publication]]
- [[https://news.ycombinator.com/item?id=34557611][Show HN: Military History Visualized | Hacker News]]
- [[https://computeradsfromthepast.substack.com/p/org-systems-multilingual-word-processor][ORG Systems&#x27; Multilingual Word Processor]]
- [[https://sr.ht/~icefox/oorandom/#a-brief-history-of-random-numbers][oorandom: A simple, robust PRNG in Rust]]
- [[https://www.pcjs.org/blog/2023/02/16/][Is the Living Computer Museum Dead? | PCjs Machines]]
- [[https://news.ycombinator.com/item?id=34929638][Paper Models of Vintage Computers | Hacker News]]
- [[http://keithlynch.net/timeline.html][Keith Lynch's timeline of net related terms and concepts]]
- [[https://news.ycombinator.com/item?id=35227600][Previous: A NeXT Computer Emulator | Hacker News]]
- [[https://news.ycombinator.com/item?id=35208286][PLATO: An educational computer system from the 60s shaped the future]]
- [[https://news.ycombinator.com/item?id=35190971][The early 90s tech scene that created L0pht, the legendary hackerspace]]
- http://vtda.org/ 🌟
- [[https://news.ycombinator.com/item?id=35310336][Ruffle – Flash Emulator – Progress Report | Hacker News]]
- [[https://news.ycombinator.com/item?id=35303220][British PCs of the 1980s | Hacker News]]
- [[https://lwn.net/SubscriberLink/928581/841b747332791ac4/][The early days of Linux {LWN.net}]]
- [[https://news.ycombinator.com/item?id=35404275][The Joy of Computer History Books | Hacker News]]
- [[https://resourceforks.com/][Resource Forks]]
- [[https://pavellaptev.github.io/web-dark-ages/][Dark Ages of the Web]]
- [[https://benjaminreinhardt.com/wddw][Why does DARPA work?]]
- [[https://www.kickscondor.com/things-we-left-in-the-old-web/][Things We Left in the Old Web]]
- [[https://technicshistory.com/2020/06/25/the-era-of-fragmentation-part-4-the-anarchists/][The Era of Fragmentation, Part 4: The Anarchists – Creatures of Thought]]
- [[https://archive.is/o10Kr][what was web2.0 lol]]
- [[https://news.ycombinator.com/item?id=35856276][Are sockets the wave of the future? (1990) | Hacker News]] (See 1st comment)
- [[https://news.ycombinator.com/item?id=35955062][Early Computer Art in the 50s and 60s | Hacker News]]
- [[https://kristenroos.ca/timeline][timeline — Kristen Roos]]
- [[https://equalitytime.github.io/FlowersForTuring/][Flowers for Turing]]
- [[https://manchesterhistory.net/manchester/tours/tour13/area13page9.html][Sackville Gardens]]
- [[http://www.typewritten.org/Media/][Retrotechnology Media - Typewritten Software]]
- [[https://news.ycombinator.com/item?id=36237731][The History of VisiCalc | Hacker News]]
- [[https://scenelist.org/][SCiZE's CLASSIC WAREZ COLLECTION]]
- [[https://news.ycombinator.com/item?id=36264744][The computer graphics industry got started at the university of Utah]]
- [[https://news.ycombinator.com/item?id=36283473][The Food Timeline – A history of all foods | Hacker News]]
- [[https://darkmentor.com/timeline.html][Low Level PC/Server Attack & Defense Timeline]]
- [[https://news.ycombinator.com/item?id=36303955][Vintage National Geographic Photos (1888-1999) | Hacker News]]
- [[https://www.tvstudiohistory.co.uk/][History of Television Studios in London - TV Studio History]]
- https://worldintimelines.com/ (https://worldintimelines.com/software-and-programming-languages/)
- [[https://betawiki.net/wiki/Main_Page][BetaWiki]]
- [[https://www.youtube.com/watch?v=hGY3uBHVVr4][Lets LISP like it's 1959 - YouTube]]
- [[https://news.ycombinator.com/item?id=36455697][History is just one damn thing after another | Hacker News]]
- [[https://buttondown.email/linotypebook/archive/lbp-issue-no-5-digging-through-a-morgue/][LBP - Issue № 5 - Digging Through a Morgue • Buttondown]]
- [[https://people.idsia.ch/~juergen/deep-learning-history.html][Annotated history of modern AI and deep neural networks]]
- [[https://tcrf.net/The_Cutting_Room_Floor][The Cutting Room Floor]]
- [[https://ounapuu.ee/posts/2023/09/19/trip-to-communication-laptop-museum/][My trip to the Communication and Laptop Museum in Estonia — Ramblings of a tech enthusiast.]]
- [[https://mollymielke.notion.site/Computing-History-Hub-be72f307fc2e4b05abe3dc67eb937521][Notion – The all-in-one workspace for your notes, tasks, wikis, and databases.]] ⭐
- [[https://archive.ph/hWKgL][The Long Boom: A History of the Future, 1980–2020 | WIRED]]
- [[https://www.folklore.org/][Folklore.org: The Original Macintosh]]
- [[https://news.ycombinator.com/item?id=38013477][Internet Artifact Museum | Hacker News]]
- [[https://www.historyofphilosophy.net/all-episodes][All Episodes | History of Philosophy without any gaps]]
- [[https://www.pictorial64.com/][The Pictorial C64 Fault Guide]]
- [[https://news.ycombinator.com/item?id=38075973][A new view of the Manchester Computer | Hacker News]]
- [[https://news.ycombinator.com/item?id=38083825][History of the Enigma | Hacker News]]
- [[https://github.com/Porges/programming-history][GitHub - Porges/programming-history: Inspired by Cajori’s A History of Mathem...]]
- [[https://www.neversaw.us/2023/06/30/understanding-wasm/part2/whence-wasm/][Understanding Wasm, Part 2: Whence Wasm - Chris Dickinson]] : Good summary of Java and Smalltalk
- [[https://news.ycombinator.com/item?id=38759057][Retro-Computing Society of Rhode Island | Hacker News]]
- [[https://news.ycombinator.com/item?id=38785317][Web Development History – Internet history for the technically curious | Hacker News]]
- [[https://news.ycombinator.com/item?id=39219322][Ask HN: What are good books on Computer History/Lore/Iconic figures in Computing | Hacker News]]
- [[https://thehistoryofhowweplay.wordpress.com/2023/10/23/smart-terminals-personal-computings-true-origin/][Smart Terminals: Personal Computing’s True Origin? – The History of How We Play]]
- https://www.ultratec.com/about/timeline/
- https://github.com/nakst/ui-museum
- [[https://arstechnica.com/gaming/2024/06/from-infocom-to-80-days-an-oral-history-of-text-games-and-interactive-fiction/][From Infocom to 80 Days: An oral history of text games and interactive fiction | Ars Technica]]
- https://news.ycombinator.com/item?id=40960128
- [[https://news.ycombinator.com/item?id=40789179][Living Computers Museum to permanently close, auction vintage items | Hacker News]]
- [[https://news.ycombinator.com/item?id=40899411][A brief history of liquid computers (2019) | Hacker News]]
- [[https://netsettlement.blogspot.com/2024/07/social-computing-before-internet.html][netsettlement: Social Computing, before the Internet]]
- [[https://news.ycombinator.com/item?id=41400639][What we can learn from vintage computing | Hacker News]]
- [[https://news.ycombinator.com/item?id=42102761][Nixie Tubes (2015) | Hacker News]]
- [[https://twobithistory.org/2021/03/08/arpanet-protocols.html][How the ARPANET Protocols Worked]]
- [[https://news.ycombinator.com/item?id=42418982][IRATA.ONLINE: A Community for Retro-Computing Enthusiasts | Hacker News]]
- [[https://news.ycombinator.com/item?id=42649340][How Britain got its first internet connection (2015) | Hacker News]]
- [[https://news.ycombinator.com/item?id=42497148][Manx – a catalog of manuals for old computers | Hacker News]]
- https://news.ycombinator.com/item?id=42926076
- [[https://news.ycombinator.com/item?id=43053248][Ask HN: Any good examples of multimedia local history web sites? | Hacker News]]
- https://x.com/SchmidhuberAI/status/1952007922721919219
- [[https://news.ycombinator.com/item?id=46176905][Screenshots from developers: 2002 vs. 2015 (2015) | Hacker News]]
