* Colophon
:PROPERTIES:
:EXPORT_FILE_NAME: colophon
:EXPORT_HUGO_SECTION: docs
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 1
:END:

#+attr_html: :class book-hint info
#+begin_quote
This website be my homepage and this page is sort of like its [[https://hacdias.com/colophon][colophon]]. I've listed why the homepage is the way it is, it's structure and some ideas behind it here. Check [[*Locus 🌊][Locus 🌊]], if you're looking for an overview of all the personal things I host publicly.
#+end_quote

** Why have a homepage?
I have absolute zero game on words but I consider myself an opsimath and autodidact. I have an extremely bad memory and my knowledge about most things is pretty shallow because I never really threw myself into the deep end of things.

But I am changing that, the homepage(and my wiki) are core part of my thinking process. They help me clear random things off my mind and let me focus on what's important, the moment. It really works! The chaos has reduced by significant amount after I started writing out documents for silly things that occupy my mind.

The way I organize, use and consume digital information, I need some place where I can host notes about things that I want to take a look at some later point in time, /organized in specific ways/. A simple homepage was the perfect fit for my needs, a wiki would have been too dynamic. It is also useful to present a cached/discounted version of me.

Also, I know it's stupid but like I cannot be fully me in social media, but here? this is my space i'll say whatever i want, one can judge me all they want, but it does not matter to me. I can wriTe like This? don't care. i can also write like this? also don't care. I CAN WRITE LIKE THIS TOO? NOT A CARE IN THE WORLD. i rite liek dis? do not fucking care. I swear a lot? [[https://www.reddit.com/r/effinbirds/][yes please]].

** Site Structure and Organization
The [[https://github.com/geekodour/o][source is hosted on GitHub]]. It's a couple of org files exported to markdown with awesome =ox-hugo=. The site is then pushed to the forge and netlify picks it up from there. I love my current workflow the most compared to all the other previous blogging workflows.

I can’t claim to have originated many of the ideas [[https://alexvermeer.com/wp-content/uploads/8760-hours.pdf][here]]. It builds off many hours of reading many articles and blogs and other things, which are attributed when possible.

** Things I want to add later
*** General Ideas
- [[https://hacdias.com/guestbook][Guestbook]] : It's something where you site visitors can leave a feedback.
- Currently this webpage is served over HTTP, and [[/index.xml][feeds(/index.xml)]]. Want to host it and make it available in more funky platforms like Gopher, [[https://brainbaking.com/post/2021/04/using-hugo-to-launch-a-gemini-capsule/][Gemini]], IPFS, tor etc.
- Add a [[https://github.com/XXIIVV/webring#join-the-webring][webring]] to this [[https://github.com/lawik/beambloggers][page]]
- [[https://indiewebify.me/][IndieWeb support]]
- [[https://www.brendanschlagel.com/canon/][Canonize: Personal Canon]] : A pills page
- Website stats
  - [[https://www.lkhrs.com/stats/][Stats - Luke's Wild Website]]
  - [[https://roytang.net/page/stats/site/][Stats : Website · roytang.net]]
*** Quantification Ideas
I plan to quantify a lot of things. I only want to quanify things I can act upon, so I'll not just quanify anything for the sake of quanitifying. Following is a badly formatted idea dump related to quantification that I would like to explore sometime in the future.

#+begin_details
#+begin_summary
Ugly list of Quantification ideas
#+end_summary
- Meta
  - [[https://github.com/seanbreckenridge/HPI#readme][GitHub - seanbreckenridge/HPI: Human Programming Interface - a way to unify, ...]]
  - https://github.com/woop/awesome-quantified-self
- Meta
  - [[https://github.com/seanbreckenridge/HPI#readme][GitHub - seanbreckenridge/HPI: Human Programming Interface - a way to unify, ...]]
  - https://github.com/woop/awesome-quantified-self
- 3D
  - [[https://gyrosco.pe/aprilzero/helix/mind/][Anand Sharma on Gyroscope]]
  - [[https://github.com/brunosimon/my-room-in-3d][brunosimon/my-room-in-3d]]
- Life graph
  - https://busterbenson.com/the-life-of/buster/
  - https://github.com/lord/mortalical
  - https://github.com/cheeaun/life
  - https://github.com/KrauseFx/FxLifeSheet
  - https://github.com/AnandChowdhary/life-data
- Software/Tool
  - data extractors
    - [[https://github.com/seanbreckenridge/google_takeout_parser][GitHub - seanbreckenridge/google_takeout_parser: Parses data out of your Goog...]]
    - https://jeffhuang.com/extracting_data_from_tracking_devices/
    - [[https://github.com/MasterScrat/Chatistics][GitHub - MasterScrat/Chatistics: 💬 Python scripts to parse Messenger, Hangout...]]
    - [[https://github.com/seanbreckenridge/HPI#readme][GitHub - seanbreckenridge/HPI: Human Programming Interface - a way to unify, ...]]
  - activity trackers
    - https://activitywatch.net/
    - https://github.com/TailorDev/Watson
    - https://github.com/phiresky/timetrackrs
    - https://github.com/larose/utt
    - https://github.com/nikolassv/bartib
    - https://github.com/heedy/heedy
    - https://github.com/almarklein/timetagger
    - https://github.com/samg/timetrap
    - https://github.com/sourcegraph/thyme
    - https://github.com/wtfutil/wtf
  - running
    - https://github.com/alex-hhh/ActivityLog2
    - https://github.com/yihong0618/running_page
    - https://github.com/tmcw/running-for-nerds
  - others
    - https://showcase.metamate.io/hackernews-user-activity
    - https://github.com/lowlighter/metrics
  - analytics
    - https://github.com/getredash/redash
    - https://github.com/metabase/metabase
    - https://github.com/mr-karan/swiggy-analytics/tree/master/swiggy_analytics
  - CRM
    - https://github.com/monicahq/monica
    - https://github.com/JacobEvelyn/friends
- Experiments
  - https://github.com/turbomaze/28-hour-day
  - https://github.com/schollz/howmanypeoplearearound
- HW
  - https://github.com/davidhampgonsalves/life-dashboard
- Setup of other people
  - https://github.com/thesephist/sounds
  - https://github.com/mholt/timeliner
  - [[https://julian.digital/2020/02/23/my-quantified-self-setup/][My Quantified Self Setup « julian.digital]]
  - https://aaronparecki.com/
  - https://github.com/nicbou/timeline
  - https://github.com/zuchka/grafana-docs-exporter
  - https://www.swarmapp.com/user/50413849/year-in-review/2021?s=rzsi5V-Vav1VXSTIKrLHEDor8UQ
- Self
  - how much time i spend on the internet and how much time i spend in life in general.
  - make the year diary digital
  - metrics of how long the laptop was on over days etc
  - visualization of linux home directory etc
- 3D
  - [[https://gyrosco.pe/aprilzero/helix/mind/][Anand Sharma on Gyroscope]]
  - [[https://github.com/brunosimon/my-room-in-3d][brunosimon/my-room-in-3d]]
- Life graph
  - https://busterbenson.com/the-life-of/buster/
  - https://github.com/lord/mortalical
  - https://github.com/cheeaun/life
  - https://github.com/KrauseFx/FxLifeSheet
  - https://github.com/AnandChowdhary/life-data
- Software/Tool
  - data extractors
    - [[https://github.com/seanbreckenridge/google_takeout_parser][GitHub - seanbreckenridge/google_takeout_parser: Parses data out of your Goog...]]
    - https://jeffhuang.com/extracting_data_from_tracking_devices/
    - [[https://github.com/MasterScrat/Chatistics][GitHub - MasterScrat/Chatistics: 💬 Python scripts to parse Messenger, Hangout...]]
    - [[https://github.com/seanbreckenridge/HPI#readme][GitHub - seanbreckenridge/HPI: Human Programming Interface - a way to unify, ...]]
  - activity trackers
    - https://activitywatch.net/
    - https://github.com/TailorDev/Watson
    - https://github.com/phiresky/timetrackrs
    - https://github.com/larose/utt
    - https://github.com/nikolassv/bartib
    - https://github.com/heedy/heedy
    - https://github.com/almarklein/timetagger
    - https://github.com/samg/timetrap
    - https://github.com/sourcegraph/thyme
    - https://github.com/wtfutil/wtf
  - running
    - https://github.com/alex-hhh/ActivityLog2
    - https://github.com/yihong0618/running_page
    - https://github.com/tmcw/running-for-nerds
  - others
    - https://showcase.metamate.io/hackernews-user-activity
    - https://github.com/lowlighter/metrics
  - analytics
    - https://github.com/getredash/redash
    - https://github.com/metabase/metabase
    - https://github.com/mr-karan/swiggy-analytics/tree/master/swiggy_analytics
  - CRM
    - https://github.com/monicahq/monica
    - https://github.com/JacobEvelyn/friends
- Experiments
  - https://github.com/turbomaze/28-hour-day
  - https://github.com/schollz/howmanypeoplearearound
- HW
  - https://github.com/davidhampgonsalves/life-dashboard
- Setup of other people
  - https://github.com/thesephist/sounds
  - https://github.com/mholt/timeliner
  - [[https://julian.digital/2020/02/23/my-quantified-self-setup/][My Quantified Self Setup « julian.digital]]
  - https://aaronparecki.com/
  - https://github.com/nicbou/timeline
  - https://github.com/zuchka/grafana-docs-exporter
  - https://www.swarmapp.com/user/50413849/year-in-review/2021?s=rzsi5V-Vav1VXSTIKrLHEDor8UQ
- Self
  - how much time i spend on the internet and how much time i spend in life in general.
  - make the year diary digital
  - metrics of how long the laptop was on over days etc
  - visualization of linux home directory etc
#+end_details

* Locus 🌊
:PROPERTIES:
:EXPORT_FILE_NAME: locus
:EXPORT_HUGO_SECTION: docs
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 2
:END:
#+attr_html: :class book-hint info
#+begin_quote
This page is an overview of all the personal things I host publicly. If you're looking for info about my homepage see [[*Colophon][colophon]]
#+end_quote

These things that I host publicly might be an overkill or maybe not the right way of doing things for some but this is going in the right direction for me, if not perfect. I need external systems and processes in place to help me get the most out of my life.

** Static pages
- [[/][homepage]] : This website
- [[https://mogoz.geekodour.org][mogoz]] : The wiki, some people call it digital garden, evergreen notes etc.
- [[https://diary.geekodour.org][diary]] : The public journal and travel diary
- [[https://ti.geekodour.org][todayi]] : The place to keep my TILs and TIFUs.
- [[https://blog.geekodour.org][blog]] : The blog

* Now
:PROPERTIES:
:EXPORT_FILE_NAME: now
:EXPORT_HUGO_SECTION: docs
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 3
:END:

#+attr_html: :class book-hint info
#+begin_quote
relatives and friends be like, /kar kya rahe ho life mein?/ and I just feel like respoding with /chal bhagg/ but ultimately end up saying something like [[https://www.youtube.com/watch?v=v4GaJS1C8o4][/matlab aisa bilkul immediate nahi soche hai but sochenge/]]. Now that I have a now page, I'll be able to point them to it.
#+end_quote
** What are you doing?
I am in Guwahati, Assam and currently working on building a couple of personal frameworks and working on my homepage. Not really spending a lot of time with friends and family. Plan to get started on couple of personal projects pretty soon. It's the summers and sometimes it gets difficult to work during daytime because of it, I am thinking of getting an air conditioner.
** What are you studying?
Not studying anything at the moment except the basics of music theory because I started learning the guitar.
** What are you thinking about these days?
I catch myself doubting my ideas and goals as I am re-writing them when creating my framework and goals. I start questioning things like, would working in academia or a research lab is where I want to be, but I quickly shrug it off because clearly it's my mind playing with me.
** What did I do this time?
Man, I again told someone that I'll pick their project when I don't have the energy to do so. But I guess, I'll just put the deadline for next month so then the ball is on their court if they want to take my offer.

* Masterplan/Roadmap/Goals
:PROPERTIES:
:EXPORT_FILE_NAME: masterplan
:EXPORT_HUGO_SECTION: docs
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 4
:END:

#+attr_html: :class book-hint warning
#+begin_quote
🍜💰 Contents of this page sort of describes how I plan to [[https://www.daemonology.net/blog/2020-09-20-On-the-use-of-a-life.html][use my life]]. It's both personal and public. Personal because it lists all my desires which I really want to make happen. Public because it also lists in ways I relate to this world and the ways I want to contribute to it.

I have spun myself 25 times around the sun at the time of this writing and tbqh, I am the dumbest mf I know and I do not have a [[https://dkb.show/post/life-is-not-short][lot of time]]. I cannot be the baddest-X on the planet, cannot work/research on something that will revolutionize some domain, the trade-offs will not be worth it for me. I've been lost in life before and I do not want to be lost again. This document is sort of like the reference I plan to keep coming back to, to iterate, to extend, to modify.

Motivations behind:
- Outsource planning and thinking of goal/purpose/direction to my past self.
- Planning is important, prioritization is importanter, I cannot get shit done otherwise. We plan because we have shit we want to do with our lives. So plan.
- Humans do not think strategically by default, more so for long term goals and on top of that I have =0IQ= and =0EQ=. So this document is sort of necessary for me to be even functional.
#+end_quote


** Master Plan
Our ancestors and fellow humans did a lot for us. The infrastructure we have today is nothing less than magic to me. But there's always something to do, something important to work on. Some of these blue-sky goals are overly ambitions but these give growth to secondary goals which are less ambitions and if I happen to solve for the secondary goals, I ultimately end up solving for the main goal. Not true for all.
#+attr_html: :class book-hint info
#+begin_quote
My ultimate goal is to leave this planet better than I found at my capacity and live a life I am proud of. For that as mere mortal, I'll have to play my part. Since I cannot encompass the whole of things, I have spent time thinking about:
- What are the areas I can make the most impact in?
- What are the areas that I really want to contribute to?

The intersection of these two is what comprises this section. Most of these ideas are humanitarian. I do not understand all the critical analysis people do. If someone is able to create happiness and satisfaction for themselves in a sustainable way so that all the entities around are also happy. That's the life I want to live. I apply this to myself and want to scale it.
#+end_quote

https://www.effectivealtruism.org/

I was once discussing my ideas with a [[https://twitter.com/neilshroff][galaxy brained friend]] and he was like "bro, you probably just want to start a religion". It's funny because it's true. I have no clue about what I am doing but I am having fun,

why after so much of philanthrophy, so many social institutes, so many engineering places around the world, big big donations, basic problems are not solved. why the fuck.

Building blocks:
- *Quality of life* : Improve quality of life by improving it at individual and community levels. Changes probably need to be at social fabric level by raising the lowest common denominator directly.
- *Curiosity, Freedom and Creativity* : Allow people to take creative risks. Freedom and curiosity is precursor to doing great work. Most people don't know what price they paid for freedom. Pay the price for who can't pay.
- *Beautiful imagination that works* : Beautiful imagination is important, beautiful things happen when people contribute beautifully at their individual levels.
- *Proper resource allocation* : Allocate the right resource to the right thing at the right time. Do we allocate things to problem spaces or solution spaces. I think most problems we face today is because we fucked this up.
- *Common knowledge* : Make common [[https://en.wikipedia.org/wiki/Cultural_universal][knowledge]] actually common. We have this wealth of human knowledge and history that we're not able to pass down to the next generation effectively. Education should automate this. Education will not solve everything but I'll be damned if I do not try.

I've divided these goals into buckets of 5, 10 and 15 years. What's mentioned below is just the outline. In other words, they are just [[https://www.youtube.com/watch?v=2_O5YHX4urE][ifs, buts and maybes and not absolutes.]] I am constantly dreaming, thinking, experimenting and learning more about these spaces. We'll figure out the actual implementation in due course of time. This plan itself should be in a better shape(more precise, proper estimations) in a year. What matters is only often clear in hindsight, so do lot of shit.

*** 5 Years
- [ ] *Helping* : Be in a position where I can help myself and others easily
- [ ] *Brain* : Brain capabilities maxxing (calculation, memory etc). I am dumb, i just want to be a smarter dumb.
- [ ] Hyperlocal movement
- [ ] *Library* :
  - [ ] A physical library in Guwahati. Lack of good libraries here.
  - [ ] It should be open 24x7
  - [ ] Start a night school in it
  - [ ] More focus on adult education
  - [ ] More than just books. All kinds of artifacts about speculative futures. Maps, events, film screenings, public lectures, sponsorships. A home and anchor for promoting discussion of the futures we want, and how we might achieve them.
- [ ] Schools:
  - [ ] Contribution to Wikipedia or to broader human knowledge rather than stupid projects
  - [ ] More focus on communication. After growing up, area that I neglected the most in school happened to be the most important. Think of a world people can communicate better. Build tools around this.
  - [ ] Microgrants and Scholarships
  - [ ] Book press
- [ ] *Capital* : Generate enough capital so that I can go on for the next 10 years without having to look out for a fund to support myself.
- [ ] *Education* :
  - [ ] There was a golden age of science but every year we also have amazing people doing amazing things. Have a list of awards eg. fields medals etc and have a simplictic editorial which explains it to a layman.
  - [ ] By default archival. Making archival mainstream than ever.
  - [ ] More people doing experiments
  - [ ] Research be less dependent on institutions
  - [ ] Define the problem of education (indian education system)
  - [ ] Monitor the state of the education system and see what is making things worse, what is making things better etc. Build systems and frameworks.
  - [ ] Lobby the government to change the systems to improve the lives of students and teachers in true sense.
  - [ ] Build an evergreen system that catalogues everything education, with proper taxonomy.
  - [ ] what kind of people i'll be able to help. what i am going to do will absolutely not matter to many. how so many people are doing so much more than me.
- [ ] Archival and data hoarding:
  - [ ] Political posters
  - [ ] Music
- [ ] *Climate change* :
  - [ ] Proactive work on areas
  - [ ] Since I most probably won't be able to directly work on the issues. Work on ways how I can channel funds etc.
  - [ ] A book/website that contains simple guidelines on how to design buildings that are climatically appropriate for different parts
  - [ ] Help in conducting surveys, help in linking edge research to places that need that research now
*** 10 Years
- [ ] Urban planning, community design
  - [ ] Have proper analysis around, is it even wise to move to a city with all the conditions it has
  - [ ] Heavily write about architecture of Guwahati buildings and why it sucks so much
- [ ] *Library* :
  - [ ] if we are able to successfully run one in the ways we want, can we run more?
- [ ] *Education* :
  - [ ] Start a education research lab
  - [ ] build a whole alternative education system
  - [ ] Being a nerd should be cooler than being a movie star or youtuber for the average Indian kid
*** 15 Years
- [ ] Make the world into a desired alternative state.  Don't like how it is; are you driven to make it into something better?
- [ ] Build a system around which problems faced by humans can be examined and fixed now irrespective of the political/cultural system they are surrounded by.
- [ ] Fuck the narrative of you can't help everyone. there are people who don't need help that's fine, but if there are people who need help it's our collective responsibility as humans to put them in the right path and provide a kickstart
- [ ] Since people don't directly seek mental health help, there should be more organizations which can get involved with organized and non-organized bodies and help talk to people about their issues and not just deliver workshops etc.
- [ ] Kids are taught nice skills like drawing etc when growing up but they are never taught to make use of it or market it (debatable). All the potential hard work they did when they were teenagers just vanish as they grow up. There should be something with which fruit of that hardwork can be used by their adult versions
- [ ] fast science : https://kk.org/thetechnium/what-everyone-knows/
- [ ] people should feel comfortable where they are, know how to create happiness for themselves, they should know how to satisfy their needs. identify their needs. basically living life is a solved problem, why ppl be facing so much issue then.
- [ ] know what 'students' in the traditional education system are thinking about their future -> exact data points
  - [ ] human allocation is super important
  - [ ] education should teach all kinds of war tactics etc. but at the same time it must be taught that the collective responsibility is that carry the human race forward
- from bret
  - revolutionize how ppl learn, understand and create
  - give scientists the tools to diagnose and cure world's ills
  - give artists the tools to create and share beauty in ways currently impossible
  - reform our infrantilzed society
  - give people tools to resist and destroy consumer culture
  - give people tools to resist and destroy the corporation's oligarchical control over employment, enternatinment and creativity
  - return power, dignity and responsibility to the individual

about humans(🐦):
#+begin_quote
Till the time we don't create strong communities, we will always feel alone. It is just mind tricking us in believing that 'I' is the most powerful entity in our best/worst moments. To create strong communities, we must accept that humans comes in different shades/color/psyche
#+end_quote
** Operation plan
This is about how I plan to execute all of this.

I spent time understanding how my brain works and how can i make it do what i want.
I plan to work on both the personal goals and public goals using two frameworks.

two frameworks
- one to implement things at scale (technical), infra, tools
- one to organize information and help me think (pipelines of different things, automatically organizing)
** Personal
*** Travel goals
- [ ] 🇮🇳 Take a picture infront of Gateway of India
- [ ] 🇺🇸 Attend a John Mayer concert
- [ ] 🇺🇸 Sit in the middle of times square
- [ ] 🇮🇳 Take a picture infront of Taj Mahal (fall in love first)
- [ ] 🇧🇷 Visit Christ the Redeemer early in the morning
- [ ] 🇮🇳 Visit all states in NE
- [ ] 🇮🇳 Visit Majuli, sneak KF ultra
- [ ] 🇲🇹 Sunset in Malta
- [ ] 🇮🇹 Stay 1 week in Italy
- [ ] 🇯🇵 Visit japan as a tourist
- [ ] 🇦🇶 See penguins
- [ ] 🇳🇱 Visit Tulip fields
- [ ] 🇳🇴 Northern lights
- [ ] 🌍 Visit all computer science museums on the planet
*** Long-term stretch goals
- [ ] Become a massage specialist 💆🏽
- [ ] Learn the guitar 🎸
- [ ] Learn to dance 💃🏽
- [ ] Publish a real book 📖
- [ ] Do Vipassana Meditation (10 days)
- [ ] Become a champion in understanding "anything". Exaggerated, but in other words, learn how to process complex information and how to deal with different kinds of information.
- [ ] Build a treehouse 🌴
- [ ] Get a diploma in cartography 🐣
- [ ] Learn 10 magic tricks ✨
- [ ] Start a duck farm 🦆
- [ ] Become part time data journalist and internet detective 🔍
- [ ] Start a:
  - [ ] Computer Science Museum
  - [ ] Education Research Lab
  - [ ] Library
  - [ ] Summer School for kids in a farm
- [ ] Keep a coin with two heads inside my purse 👛
- [ ] Open a small corner light shop 🎊

** How to approach mentioned goals
Since the mentioned [[*Master Plan][master plan]] is just a rough outline. When working on something or picking anything up, I need to at-least answer these questions in truthfully.
- What exactly do I want to achieve?
- How can I measure success?
- Am I actively seeking out information about this?
- Can I break this down into more manageable parts?
- Is this really my goal? Or is it just some projection, am I constrained by fears or uncertainties?
- What's awesome/dope about this?
- What would this look like if it was perfect?
- What is that you want to add/change here?
- What are some questions I return to related to this area?
** Links
- [[https://www.quartey.com/goals#library][Emmanuel Quartey | Writing]]
- [[https://www.lesswrong.com/posts/ZJJH45J6eF2JCSQhW/list-of-common-human-goals][List of common human goals - LessWrong]]
- Teslas master plan
- 8000 hours
- Visa's friendly abs nert meme


* 🌿
:PROPERTIES:
:EXPORT_FILE_NAME: _index.md
:EXPORT_HUGO_SECTION: docs/collections
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 5
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookFlatSection true
:END:
* List of lists
:PROPERTIES:
:EXPORT_FILE_NAME: list_of_lists
:EXPORT_HUGO_SECTION: docs/collections
:END:
** Personal
*** Personal Personal
- [[file:personal_lists.org::*Values][VaLuEs]] : Things that sort of shape who I am
- [[file:personal_lists.org::*Beliefs][Beliefs]] : If I wrote the bible
- [[file:personal_lists.org::*Won't Do][Won't Do]] : Things that I'll never ever, ever ever, attempt in this lifetime
- [[file:personal_lists.org::*Would do again][Would do again]] : Things i want to do again, spend more time doing
- [[file:personal_lists.org::*Lies][Lies]] : Lies that i keep telling myself
- [[file:personal_lists.org::*Can speak on][Can speak on]] : Things that I can talk about for 30mins straight, without prep
- [[file:personal_lists.org::*Angels][Angels]] : List of people without whom i would be more nobody than the nobody i am today
- [[file:personal_lists.org::*Wrong Deals][Wrong Deals]] : Deals that went wrong in my life or my unfair expectations
- [[file:personal_lists.org::*Don't like it][Don't like it]] : Things that i do not like
- [[file:personal_lists.org::*Conversations dump][Conversations dump]] : Absolute chaos
*** Semi Personal
- [[file:personal_lists.org::*My delusions][My delusions]] : Things that I see that I think others don't, but they probably do
- [[file:personal_lists.org::*What if][What if]] : Just letting my imagination run wild
- [[file:personal_lists.org::*Predictions][Predictions]] : things that i have 100% conviction will happen, inevitable forces. Also bets.
- [[file:personal_lists.org::*Communities][Communities]] : Ah! Humans.
- [[file:personal_lists.org::*sElF hElP][sElF hElP]] : Self help blogposts that sort of actually helped me.
- [[file:personal_lists.org::*Apologies][Apologies]] : things that i want to publicly apologize about
- [[file:personal_lists.org::*Jargonfile][Jargonfile]] : Words!
- [[file:personal_lists.org::*Thankful][Thankful]] : I have a lot to be thankful about.
** In my radar
List of things that are in my radar along with the reason why interested
- [[file:non_personal_lists.org::*Interesting People][Interesting People]] : People I found on the internet that I find interesting
- [[file:non_personal_lists.org::*Interesting Organizations][Interesting Organizations]] : Organizations I found on the internet that I find interesting
- [[file:non_personal_lists.org::*Dem Comments][Dem Comments]] : collection of comments across different forums on the internet
** Cool list
collection of things that I think are cool one way or the other.
- [[file:non_personal_lists.org::*Bots][Bots]] : Insects and bugs i want to be friends with
- [[file:non_personal_lists.org::*Portfolios][Portfolios]] : Personal homepages/wikis/portfolios that I like
- [[file:non_personal_lists.org::*Websites][Websites]] : Random websites that I think are cool
** Random lists
- [[file:non_personal_lists.org::*Manifestos][Manifestos]] : Collected manifestos
- [[file:non_personal_lists.org::*Copy pastas][Copy pastas]] : Collected copy pastas
- [[file:non_personal_lists.org::*Challenges and Sports][Challenges and Sports]] : Various challenges
** Useful lists
- [[file:non_personal_lists.org::*Things to say when][Things to say when]] : Things that I can say at different situations.
- [[file:non_personal_lists.org::*Digital Warrior][Digital Warrior]] : Guides and references to be more aware digitally
** Lists elsewhere on the internet
- [[https://news.ycombinator.com/item?id=11860496][100 things that are broken, according to HN]]
- [[https://www.evernote.com/shard/s204/client/snv?noteGuid=6ca15c53-0981-4e4a-ac7e-3871947c7414&noteKey=154edd1559be9188a589c6713b4b7ae8&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs204%2Fsh%2F6ca15c53-0981-4e4a-ac7e-3871947c7414%2F154edd1559be9188a589c6713b4b7ae8&title=Travel%2BPacking%2BList][Travel Packing List]]
- [[https://www.hella.cheap/unpopular-opinions/][Unpopular Opinions]]
- [[https://thume.ca/2020/07/19/my-youtube-tier-list/][My tier list of interesting YouTube channels - Tristan Hume]]
- [[https://mason.gmu.edu/~rhanson/altinst.html][Alternative Institutions]]
- [[https://github.com/thehandsomepanther/cool-sites][thehandsomepanther/cool-sites]]
- [[https://matthewmcateer.me/blog/under-investigated-fields/][Under-Investigated Fields List (Version 1.0) - matthewmcateer.me]]
* Idea Monkeysphere
:PROPERTIES:
:EXPORT_FILE_NAME: monkeysphere
:EXPORT_HUGO_SECTION: docs/collections
:END:

This is not a syllabus and learning things is not so linear as presented here but I just wanted to lay out an outline for reference if I ever get lost again. Of-course I am not pressuring myself to learn all this and there's no priority here, these are general subjects that i am interested in.

** Computer Science/Software Engineering
 | Topic                          | Why                                                                                                              | Depth(1-5) |
 | Computer Networks and Security | understand my network, debug network problems, better threat model.                                              |          3 |
 | Network Programming            | Contribute to the networking subsystem and important for when I would want to actually implement dist sys things |          3 |
 | Systems Programming            | Be able to performance test things, finetune stuff, Understand underlying things for all things systems          |          4 |
 | Databases                      | write a toy DB and understand parts, contribute to some open source relational db                                |          2 |
 | Data structures and algorithms | Be able to follow any algorithm that's laid out given enough time and convert it into a program                  |          3 |
 | Distributed Systems            | Be able to plan things better and more precisely also to understand how systems work together                    |          4 |
 | Compilers                      | When stuck with a parser/interpreter problem i am scared + idk what to do or expect. Get rid of the fear         |          2 |
** Electronics
 | Topic                   | Why                                                               | Depth(1-5) |
 | Electronics Engineering | Want to play around with the pi(s) and duinos but don't know shit |          1 |
 | Computer Arch           | Just curious                                                      |          1 |
** Science
 | Topic     | Why                                                                                         | Depth(1-5) |
 | Physics   | I loved physics in school, college made me hate it, think I'll love it if i get to it again |          2 |
 | Mechanics | I want to understand how some machines work                                                 |          1 |
** Math
 | Topic           | Why                                                              | Depth(1-5) |
 | Statistics      | I do not understand data, need to understand data                |          4 |
 | Number Theory   | Need help with thinking when dealing with algorithms             |          3 |
 | Complex numbers | Scared. Don't want to be scared of myself(i)                     |          1 |
 | Discrete Math   | Need to write proper proofs, also interesting                    |          3 |
 | Category Theory | Just because it sounds so cool and idk what the fuck it is       |          1 |
 | Calculus        | Keeps coming back                                                |          1 |
 | Diff. Eqns      | Keeps coming back also interesting                               |          2 |
 | Linear Algebra  | Need to be clear about some numbers, I have forgotten the basics |          3 |
 | Real Analysis   | Want to understand numbers better                                |          1 |
** Data, Thinking and Information management
 | Topic                    | Why                                                                                                                                                                       | Depth(1-5) |
 | Writing                  | i suck at writing, i don't want to suck at writing because it's the only way I like communicating in                                                                      |          4 |
 | Cartography              | i love maps, they are pretty cool, think this will also help so many of my projects that I have in mind                                                                   |          3 |
 | Data analysis            | real deal shit, whatever I do, i cannot escape this                                                                                                                       |          4 |
 | Data vis                 | I am a very visual learner so I need to know what are my options when I have some data and I want to visualize it                                                         |          3 |
 | Information theory & HCI | Want to better understand how information is structured and how humans perceive it                                                                                        |          3 |
 | Thinking                 | Be a more clear thinker. I need to be a better thinker every year. Introduce new ideas, be clear about my intentions when I speak. Improve the search engine of my brain. |          4 |
 | Philosophy               | Become unhinged and antifragile                                                                                                                                           |          2 |
** Web
 | Topic           | Why                                                          | Depth(1-5) |
 | Web-development | Build things quickly                                         |          4 |
 | Web-hacking     | most of the things i want to build need some sort of fuckery |          4 |
** Education
 | Topic                         | Why                                                                                                                                              | Depth(1-5) |
 | Education system of the world | Really do not want to re-invent the wheel, It's important to see do case studies and research                                                    |          5 |
 | Education system of India     | /Parhega India Tabhi toh Barhega India/                                                                                                            |          5 |
 | Real world situation          | Lot of my projects are related to education so I will have to have systems in place which feed me infomation about what's going on in the system |          5 |
** World
 | Topic     | Why                                                                     | Depth(1-5) |
 | Economics | Need to understand how world works                                      |          3 |
 | Finance   | Need to make some monie and manage my own money                         |          3 |
 | Business  | Need to start own business and help in businesses of friends and family |          4 |
 | History   | I like to pretend I like history. just kidding, i like it v much.       |          3 |

* Food/Drinks
:PROPERTIES:
:EXPORT_FILE_NAME: food_drinks
:EXPORT_HUGO_SECTION: docs/collections
:END:
** 🍹 Drinks I enjoy (ranked)
I am super non-fancy.
- Amla Juice (rare)
- Lime juice (sweet)
- ORS Liquid (Orange flavour)
- Kingfisher Ultra
- Banana shake
- Kingfisher Premium
- Electral Powder drink during summers 💏
** 🍸 Cocktail recipes
none yet but check [[https://github.com/balevine/cocktails][this]]
** 🍲 Food recipes
none yet
** 🏃 Places
Recommendations of different places in different places.
- [[https://www.google.com/maps/d/edit?mid=1QvCvZS2U1sv3ADrnOhIXKz7OCxrYU3h2&usp=sharing][Pondicherry and Auroville]]
- Guwahati
- Bangalore
- Shillong


* 🌲
:PROPERTIES:
:EXPORT_FILE_NAME: _index.md
:EXPORT_HUGO_SECTION: docs/others
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 9
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookFlatSection true
:END:
* Asset Allocation
:PROPERTIES:
:EXPORT_FILE_NAME: asset_allocation
:EXPORT_HUGO_SECTION: docs/others
:END:
#+attr_html: :class book-hint warning
#+begin_quote
I am the last person to take any financial advice from. Everything under this page is only for me based on the risks I can take and how stupid I can get. If you have any suggestions on how I can allocate my assets better, please feel free to ping me about it. Always happy to learn.
#+end_quote
** Background Notes
- Focus on what can go wrong and take care of it first.
- By hook or by crook, I should be making at-least 20L a year for the next 5 years from next year.
- It's important to do financial planning and goal setting so that you can stop thinking about money and focus on learning, building things and career growth. This will lead to satisfaction as I gain satisfaction from learning things and at the same time, it will help maximize my income.
- Having too many options will cause analysis paralysis.
- Equity investments can be also be compared with growing gardens and trees. You can either acquire that skill or you can hire a gardener to do that for you. They key point is to have patience.
- Learn when and how to exit, setup watchers for exit. Not knowing how and when to exit is like having the best water bottle in the world with a small hole. Asset allocation strategy is closely linked to withdrawal strategy.
- Savings does not mean putting that money into your bank account, it could also mean investing it somewhere etc. creating assets that can give you direct value when needed.
- Build the life of your dreams and then save for it.
- Lifestyle inflation refers to the common phenomenon of increasing spending shown by people as their income increases.
- Time billionaire : One billion seconds is 31 years (a career). If you have 31 years time of life, you're a time billionaire. I am 25 now, I am currently a time billionaire if not a money billionaire.
** Allocation
*** General Notes
- I'll try to save 75% of my primary monthly income for the next 5 years.
- With better incomes, lesser spending and more focus, the rate of savings will increase. Earn more, spend less. Most basic rule of saving.
- If you have an impulse to buy something online, put a pause of 72 hours before you place the order. If you want to buy things you want, you have to save.
- It's always good to start early, in my first year of job because I had no one telling me what to do with my money, I managed money very bad. It becomes, since I don't know what to do, I will do nothing. It was very stupid of me to do nothing.
- For the dumbass that I am, the only formula I use to plan anything is the [SIP formula](https://cred.club/calculators/sip-calculator). There are three variables, =p=, =r= and =t= . As mere mortals, with hard and smart-work we can change the value of =p= . =r= and =t= are up-to sky homie. So I'll try to optimize =p= and make sane and safe decisions for =r= to be decent.
- The biggest factor for financial independence is not your income, it is **a sustainable savings rate**.
- Ideal portfolio should be diversified not just asset-wise but also geographically.
*** Distribution
- 60% defensive stocks (Diversified Indexes, Bonds, Debt)
- 25% slightly aggressive stocks (Picked Equity)
- 5% Crypto
- 10% build hedge (Cash, FD, Gold, Silver, Bitcoin)
- Emergency Funds
  - 1L Immediate support fund
  - 5L kit-kat break from life support fund
**** Why hold some liquid debt funds
- FDs are safe, but you can't pull the money out if you need it immediately.
- Equity can be volatile, but you can pull out the money. If there is an emergency someday, based on the nature of the emergency you might have to sell things at a loss because you need the money, even if you know for a fact that the stock will be going up sometime in the future.
- Holding some money in a debt mutual fund allows you to always have certain amount of liquid money as they allow you to get your money back quickly. Liquid debt funds are also less volatile compared to equity, so chances that you'll be at a loss is probably less.
*** Savings Buckets
**** Bucket Instant Gratification (0-5 years)
Money that is needed in 0-5 years goes here
- Aim for 8-9% returns on these.
- When subscribing, make sure to check for taxation and exit load etc.
- These money go into liquid funds and FDs
**** Bucket Delayed Gratification (>5 years)
Money that is needed in 6-7 years goes here
- Aim for >10% returns on these in the long term.
- Since this is long term, subscribing for tax benefit plans can come here.
- We can go aggressive here, because it's long term and we don't care if things do down in recent times. It's the long game. We can take big bets about the future.
** Insurance
- Always buy pure health insurance and pure life insurance, never go for the combo ones.
- Prefer direct plans over going through some agent.
- Take the terms up-to 60 years, because after 60 years, your investments and your savings should cover your ass, otherwise you might as well die.
- Health: This should be more correctly called sickness insurance.
- Life: This is more of a income replacement insurance and not a life insurance. i.e. When you die and your income stops, this will supplement your income for your family.
** FIRE
How much money you need to retire is called your FIRE portfolio
- I'll be going with **SWR(Safe Withdrawal Rate)** : Estimated percentage of savings you're able to withdraw each year throughout retirement without running out of money.
- It only includes invested assets that generates income. It is not your net worth.
- If annual expenses(tax incl.) = 12L (Monthly 1L)
  - WR(withdrawal rate of 4%) = 12/0.04 = 300L = 3Cr
  - 3Cr/12L = 25 years, with 3Cr, I'll be able to live a 12L/y lifestyle for 25 years.
- If annual expenses(tax incl.) = 9L (Monthly 75k)
  - WR(3%) = 9L/0.03 = 300L = 3Cr
  - 3Cr/9L = 33 years, with 3Cr, I'll be able to live a 9L/y lifestyle for 33 years.
- 3% WR is considered safe and my expense rate should be around 9L/y
- So **3Cr is my FIRE portfolio**, whenever I hit 3Cr, I can quit my job and working anymore for good. While talking to some people I realized that 3cr is nothing for them but it's more than enough for me.
- I plan to save 75% for the next five years. But to stay safe, I've put 60% savings in the following screenshot.
** Tools and resources
- [[https://networthify.com/calculator/earlyretirement?income=50000&initialBalance=0&expenses=20000&annualPct=5&withdrawalRate=4][Early Retirement Calculator]]
- [[https://www.reddit.com/r/FIREIndia/][Financial Independence/Early Retirement India]]
- [[https://www.reddit.com/r/IndiaInvestments/][A place for Indians to discuss and evaluate Investments]]
- [[https://www.reddit.com/r/personalfinance/][Personal Finance]]

* Agenda:2022
:PROPERTIES:
:EXPORT_FILE_NAME: agenda_2022
:EXPORT_HUGO_SECTION: docs/others
:END:
** Introduction
what the year is *not* about:
- not about doing a lot of research.

what the year is about(ordered by priority):
- about making your mind and body healthy
- about building pipelines for inspiration, planning, execution and money
- about going back to the fundamentals
- about taking long term bets
- about fixing human relationships
- about putting myself in a position where i can help myself and others if required

All of this is also based on the fact that accomplishing my goals in "certain
ways" will bring me true joy(i am pretty sure about this one). 2023 should be
the year when the research finally starts happening, where the real money
starts flowing in. In this process there will be a lot of study, practice,
failures, experimentation, careful operation and ruthless prioritization.

** Why?
April'22, got diagnosed of adhd. writing this in June'22 and still
haven't got my meds. It's that bad. But what I ultimately realized is that my
strongest issues are with:
- *retention of information*: do not retain shit, recall seems fine
- *extreme procrastination*: will tell you someday later
- *extreme dependence on mood for productivity*: dependence on things that i do not have complete control over yet
- *quickly getting overwhelmed*: terrible management of energy and time

based on my quirks and specifics all of the above can be addressed with proper
note-taking(at-least it'll be a sensible start)

Last year('21), i watched a [[https://www.youtube.com/channel/UCVCldvV9TWPPGM0kRB91G7w/featured][lot of videos by Russell Barkley]] on adhd, which
made me doubt if i am a goat here. Based on recent diagnosis, information i
gathered from the videos and past experimentation/experiences i have decided
that i need to change certain things so that i do not face such difficulty in
doing simple day to day tasks.

This document essentially documents that way of life, some principles, some
rules for myself and how i plan to spend rest the year. In other words, this
document is simply a manual for an year long experiment.

#+begin_quote
  i am writing this in June'22, but the year still ends for me in Dec'22.
#+end_quote

** About existence
#+begin_quote
 - > be me
 - > good enough kid in school
 - > 23, realize been living life on absolute autopilot
 - > two years of realizations passes by
 - > 25, code monki wagecuck
 - > quit job for mental health reasons
 - > decide that need to touch grass
 - > invent own meaning of life: live for others, catch is i need to fix myself first.
 - > fixing self is important
 - > other things will follow

#+end_quote
other things:
 - I am no longer going to spend my time and energy revolving around other things.
 - I am focusing on myself, and people i care about. Once that's taken care of we'll move up.
 - I tried my best to carefully craft my environment this time, it’s not perfect but good enough. I have optimized my environment for:
   - happiness : so that i can get into a good mood as fast as possible.
   - peace of mind: taking care of my family so they can take care of themselves and it'll not be a constant worry in my tiny head.
 - This time it probably should work, I have been consistently failing at this goal thing since 16-17. My wins should be spectacular for myself and nobody else.

I found this [[https://twitter.com/shreyas/status/1223792859469320192][awesome table by shreyas on twitter]], i found it very relatable to how i am trying to fix my life, so i wrote a slightly modified version of it for me:

| conventional wisdom            | real wisdom                                                   |
|--------------------------------+---------------------------------------------------------------|
| deal with mental health issues | face it, prevent these issues by understanding the root cause |
| focus on strengths             | also fix your weaknesses                                      |
| always put in best effort      | seek leverage                                                 |
| become president of country    | be strategic, don't chase titles                              |
| make logical decisions         | explore psycho-logical solutions                              |
| market things                  | build a good thing first                                      |


about lifestyle(🐦):
#+begin_quote
The preferred lifestyle should dictate your business decisions, not vice versa.
- Work is something you do that lets you earn minimum necessities
- Your business should improve your life
- Variable income is a good stressor
- Try different things & find out your preferences
#+end_quote

** Moats
- *Friends:* Make friends in general. Make friends with people you’d generally not hangout with. Make friends with people all around the world, with people from cities you want to visit. learn how to effortlessly take care and nurture friendships.
- *Fixes:* Fixes need to be internal rather than external. Not leaving any thought unaddressed.
- *Balance:* Do not seek work life balance, seek something you would happily sacrifice work life balance for. You won’t need balance that way, you’re the balance mfr.
- *Execution:* Under promise and over deliver. Create value for myself and for other people.
- *Uncomfortable with self*: Imposter syndrome is subjective and manifests itself differently for different people, for me it's what @hillelogram mentioned on the bird site. It's stupid but I feel like an imposter because I never was able to transform the cool side project ideas into reality.
- *To think:*
  - [ ] Identify my craft, it's definitely not programming. Maybe it's a lot of things.
  - [ ] Start becoming so good at "something" that you can teach people about it.
  - [ ] Define my worth
- *To improve:*
  - [ ] Analytical abilities
  - [ ] Creative abilities
  - [ ] Execution abilities
  - [ ] Competitive abilities
  - [ ] Attention to detail
** Goals
These are my goals for 2022:
*** Basic Human Goals
I basically checked myself into Maslow's hierarchy of needs, my actions need to align with my needs:
- [ ] *Health*: Get yourself checked, check off possibility of any immediate danger
- [ ] *Personal security*: Add security cameras at home
- [ ] *Emotional security:* Fuck emotions, become god
- [ ] *Financial security:* Make enough so that I can buy a car without a loan
- [ ] *Family/Friendship/Intimacy/Trust/Acceptance:* Be real, be around real
- [ ] *Cognitive needs*: Individuals who enjoy activities that require deliberation and brainstorming have a greater need for cognition.
- [ ] *Aesthetic needs*: Humans must immerse themselves in nature's splendor while paying *close attention to and observing their surroundings in order to extract the world's beauty*. This higher level need to connect with nature results in an endearing sense of intimacy with nature and all that is endearing. (bro wtf?)
- [ ] *Self-actualization:*  What a man can be, he must be. Utilizing and developing talents and abilities. Pursuing goals, Partner acquisition(bro wtf? 2).
- [ ] *Transcendence needs:* one finds the fullest realization in giving oneself to something beyond oneself.
*** Better Person Goals
These are things I’ll not be deliberately practicing, these are things that changes me as a person so I just need to be aware of these things.
- [ ] Gratitude
- [ ] Discipline
- [ ] Active listening
- [ ] Anger control
*** Mental Habit Goals
- [ ] *Document:* Journal/Document everything including mood. (Self Quantification)
- [ ] *Reading:* Read books/papers/blogs, take notes.
- [ ] *Sleep fix:*
  - [ ] 8 Hour sleep
  - [ ] Offline, 1 hour before bed and 2 hours after waking up.
  - [ ] Wake-up with a mission, go to sleep with a plan for the next day and the mission. Clear your mind and body once you wake up.
- [ ] *Understand perspective:* Look at anything from at-least 3 different perspectives.
- [ ] *Hard things:* Do hard things daily, learn to use my tools(including phone) to the fullest.
*** Physical Habit Goals
- [ ] Get Fit
- [ ] Fix posture
- [ ] Quit smoking
*** Skill Goals
- [ ] Learn
  - [ ] Swimming
  - [ ] CPR, Basic first aid
  - [ ] Guitar
  - [ ] Whittling
  - [ ] Pixel Art, Basic drawing
  - [ ] Lockpicking and stealing
  - [ ] How world works(economics), Business, valuation.
- [ ] Improve
  - [ ] Math
  - [ ] DS & Algo
  - [ ] General programming practices
  - [ ] Security posture
  - [ ] P2P, Dist Sys
  - [ ] Shipping shit
*** Whole Goals
These goals are vaguely defined by intent, these does not corelate to doing some task or doing a set of tasks. When these things will be done, i;ll know and then i can check them off. Here I mention of building two frameworks, one for ideation and one for execution.
- [X] Write the masterplan. Have only one plan, no backups. Roadmap it 5 years, 10 years, 15 years. (starting: 25yo, ending: 40yo). After 40 you should not be worrying about planning things.
- [ ] Build pipelines for inspiration, planning, people and money. More like the eudaimonia machine but for your mind to work on different things. Includes self quantification.
- [ ] Build a framework where I can test/execute my prototypes in a safe, sandboxed manner. This framework should have good observability. It must have a fast feedback loop.
- [ ] Practice progressive iteration, create a safe ground so that you can inexpensively re-iterate. be willing to put out a half-baked idea into the world, and use the responses and feedback to continue iterating.
- [ ] Build a whole social media mafia thing, MLM of pages across social media. need distribution.
*** Income Goals
- [ ] Introduce money plugs, making money should be a side-effect of what you do
- [ ] Start passive income, become a passive income mafia
- [ ] By year end, I should be making 7L a month
- [ ] Monetize every skill possible, become a whore for next 2-3 years. Study different markets.
- [ ] Build random things and then sell them. Make toys and sell [[https://www.instagram.com/reel/CXgkFf0FgOp/][toys like this]]. Learn toy product design.
- [ ] Do lot of Kickstarter kind of projects eg. ergonomic stand for computer table. lightweight and good looking whiteboard, with magnetic box holder in one corner etc.
*** Random Stupid Goals
Just like a kid.
- [ ] Place “hooks”, make friends with dogs from different localities, make friends with birds and crows. Matrix shit.
- [ ] Get driving license
- [ ] Start some satirical movement like birds aren't real
- [ ] Learn Dad skills (umm, cooking, how to tie knots etc)
- [ ] Become a storyteller, make people excited about your story. Create a narrative, break the narrative.
- [ ] Make eye patch, make pirate cosplay.
- [ ] Solve crime as a detective. Read books on criminal psychology and how to become a real detective etc. Up your reasoning skills.
- [ ] Do 100 random little things and pay attention to how you feel - visa
- [ ] Generate a wild thought pool
** Agenda
*** Meta ideas
- *Right mindset:* instead of saying "i'll solve this task today", put your best effort for a period of time continuously over the days.
- *Practice:*
  - Deliberate practice is what helps the average brain lift into the realm of those naturally gifted.
  - Practicing certain mental patterns deepens your mind.
  - Do mixed practice instead of block practice. i.e practice after finishing the book vs practicing after finishing the chapter. This way we use much more cognitive power.
- *Be real*:
  - Don’t fool yourself. Don’t blindly believe in your intellectual abilities.
  - Having a team can bring those projections down.
- *Pomodoro:* In the sessions where it's pure learning, make sure to use pomodoro.
- *No snooze:* if possible, never postpone what's on agenda, never snooze
- *0 days:* if it's a habit, no zero days
- *Hard things:*
  - Do hard things daily so that hard tasks become regular task. break things down.
  - If something seems too hard, create a simpler version of the problem.
- *Build/Apply:*
  - If learning, build something out of it. A product, a poem, whatever.
  - At the least, list 2 things that can be built with the new knowledge.
  - Chunking is the act of grouping concepts into compact packages of information that are easier for the mind to access. Apply chunking.
- *Procrastination:* It's a habit that affects many areas of life. Just start, that's the trick.
- *Complex things:*
  - Often helpful to pretend that you are the concept you’re trying to understand.
  - You learn complex concepts by trying to make sense out of the information you perceive. Not by having someone else telling it to you.
- *Sleep:*
  - Sleep is part of the learning process. Consume new information and let your brain rest on it, so that you can learn on top of it. Don't fuck w it.Incremental learning, otherwise it's like building a wall without letting it dry.
  - Sleep also affects my mood, so it's extremely important for me to get right amount of sleep.
- *Habit:*
  - Habit is an energy saver! no need to focus when performing different habitual tasks.
  - Once your brain starts expecting a reward only then will the important rewiring takes place that will allow you to create new habits.
*** Daily agenda
- Reminders:
  - consume: because the list of capture keeps growing, remind self to consume something everyday.
  - recall:
    - remind self to do spaced repetition. when coming back to some info, try recalling it without looking at it, re-read only after you recall. Recall references too.
- *Meetings:*
  - only happens if they are on agenda
  - try keeping less meetings either way
  - Tune people out if they try to demean too much of my efforts. feeling not so good about it? cancel it.
- *Entry:*
  - plan next day at the end of the *evening of the working day* (easier to disconnect, be present)
  - plan next week on *friday evening*, go into weekend with a clear mind
  - set both starting time and finishing time of tasks if possible
  - make changes throughout but make commit to notes at time of night journal entry only.
- *Notebook:*
  - Keep a agenda ideas document, keep note of what works and what does not.
*** Weekday
| Duration | Task                        | Time split |
|----------+-----------------------------+------------|
| 02h      | workout + bath + meditation |      90+30 |
| 07h      | study/build/hack            |      3+2+2 |
| 02h      | math/formal methods/thinkin |        1+1 |
| 01h      | Consume new information     |          1 |
| 08h      | Sleep                       |          8 |
| 04h      | Chores                      |          4 |
*** Weekend
| Duration | Task                        | Time split |
|----------+-----------------------------+------------|
| 02h      | workout + bath + meditation |      90+30 |
| 01h      | study/build/hack            |          1 |
| 08h      | Sleep                       |          8 |
| 13h      | whatever the fuck           |         13 |
* Deathnote
:PROPERTIES:
:EXPORT_FILE_NAME: when_i_die
:EXPORT_HUGO_SECTION: docs/others
:END:
This page contains information that can be useful if I fall in love with death.
** Passwords and Physical Access
- Bitwarden Emergency Access
- 2FA : On my phone
** Songs to be played
- [[https://www.youtube.com/watch?v=WTJSt4wP2ME][K'NAAN - Wavin' Flag (Coca-Cola Celebration Mix)]]
** Wishes
- When I am dead, just throw me in the trash
** Helpful links
- [[https://github.com/potatoqualitee/eol-dr][potatoqualitee/eol-dr]]

* 🌱
:PROPERTIES:
:EXPORT_FILE_NAME: _index.md
:EXPORT_HUGO_SECTION: docs/documents
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 6
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookFlatSection true
:END:
* Notetaking
:PROPERTIES:
:EXPORT_FILE_NAME: notetaking
:EXPORT_HUGO_SECTION: docs/documents
:END:

#+attr_html: :class book-hint warning
#+begin_quote
I've [[https://www.youtube.com/watch?v=j_DshRUOm-o][a huge memory problem]], i forget everything eventually so to retain information, note-taking is essential. This is a real problem for me, on top of that, years of constant use of social media has affected me in ways that i do not like.
#+end_quote

Some random quotes on memory and notetaking that I like:
#+begin_quote
- /So much of what we call creativity and intelligence is just memory. - Unknown/
- /Notes aren’t a record of my thinking process. They are my thinking process. – Richard Feynman/
- /What information consumes is rather obvious: it consumes the attention of its recipients. Hence a wealth of information creates a poverty of attention, and a need to allocate that attention efficiently among the overabundance of information sources that might consume it. ~ Herbert Simon/
#+end_quote


** CCES Loop
Let me introduce my very own CCES loop. tbqh, i just put that abbreviation to sound cool, it's absolute shit. It is specific to how i function. On a regular day, this is happening to me in all kinds of ways so i decided to sort of formally define it here. It's a set of actions that can be applied to certain entities. Part of the reason this works for me is probably because I enjoy using it.

| Action  | Example entities                                              |
|---------+---------------------------------------------------------------|
| Capture | Link, Feeling/Moment, Idea/Suggestion/Project, Task, Question |
| Consume | Link, Idea/Suggestion/Project, Question                       |
| Execute | Idea/Suggestion/Project, Question, Task                       |
| Share   | Idea/Suggestion/Project, Feeling/Moment                       |

This by definition does not have a start and or end and can occur while reading some section in a book or while taking a shower. One is free to use any technique/tool to do the action on any of the entities.

*** Capture
Because we want to make unified operations, we will avoid application level capture. In other words, we want to *avoid* using twitter bookmarks, HN saved, browser bookmarks etc. Capture most of the time would be a secondary activity when you're doing something else. We would also want to link new captures to existing notes. When we take notes, we should ask: /“In what context do I want to see this note again?”/ when setting *tags*.
- 🖥 : org-capture, org-mode notes, org-roam.
- 🏃 : telegram dump channels, camera, screenshots
- 🐉 : multimedia into respective google drive
- 🔔 : prioritize at entry

#+attr_html: :class book-hint info
#+begin_quote
note: plan to make a hybrid-image-board which should move my dependency on google drive
#+end_quote
*** Consume
Before consumption it is important to re-organize/re-order information for consumption. When consuming, it should be the primary activity. We also re-prioritize things at this step because it's the only sane way to decide what to work on.
- 📅 : periodically re-view, re-think, re-organize, re-prioritize captures.
- 🐝 : place information where it will be easily accessible while executing. eg. put things into anki.
- ⚒ : build tools to help re-organize captures.
- 🍲 : actually consume, study, think, summarize. recurse.
*** Execute
Execution is the most important part. Creating content out of your notes is natural spaced repetition.
- 🍎 : apply what you consumed to something useful
- 👉 : take it the next level/form of it. write that post, ask that question, ship that project.
*** Share
Sharing is caring, share the good energy as much as you can.
- 🎷 : talk to people about what they are doing, learn from them. share your ideas.
- 📜 : share what you feel freely in which ever medium you prefer.
* Collaborate
:PROPERTIES:
:EXPORT_FILE_NAME: collaborate
:EXPORT_HUGO_SECTION: docs/documents
:END:
#+attr_html: :class book-hint info
#+begin_quote
I am comfortable living with myself and spending time alone and I try to create an environment for myself where I can thrive. I've been through some shit and I am still recovering, so I am not yet available for everything and everyone but I plan to be more social eventually. From past experiences, things usually go south when I step out of my bubble and interact with the world. So I've listed things I know about myself that are helpful when working with me, both for myself and others. These are [[*Why?][important for me]] so that I can keep being functional. I took +inspiration+ copied shit from amazing [[https://manfred.life/howto-manfred][manfred]] and nice [[https://www.brendanschlagel.com/collaborate/][brendan]] while creating this page.
#+end_quote

I don't have a full time job and not looking for one /as of the moment/. My ideas about creating money are listed at [[*Gandhi ₹][Gandhi ₹]]. In certain cases, I plan get some bread though collaborations. *I am open to all kinds of collaborations*, specially crazy ones. I like juggling hats but also big fan of going down the rabbit hole and not returning to the surface for weeks. I've listed some thoughts below which might help you decide if you'd want me to collaborate with you/your team.

Additionally, if you just want to have a casual chat about something we both are interested in or just want to tell me that I am full of shit, I always appreciate those conventions.

** Strengths and Specialties
This list is volatile, I'll keep updating this frequently.
- *Data* : In my past, I've solved problems related [[https://www.kalzumeus.com/2011/10/28/dont-call-yourself-a-programmer/][to data wrangling]], In other words extracting data out of some source and putting it somewhere and in some way where it makes more sense.
- *Tools* : Building tools and automation, big fan of building custom tools. Be it woodwork or writing set of shell scripts to do taxes for your brother in law which also collects metrics about his kitchen garden.
- *Right thing* : Extreme focus on doing the right thing vs doing the thing that gets the job done now. I picked this up while working at [[https://clarisights.com/][Clarisights]] and still improving at it.
- *No bloat* : Figuring out no bloat solutions to problems related to content management and knowledge management. I have special interests in proper organization, using the right tool for the job, building new tools if things don't fit the exact requirements, delivering the most upto-date information to the consumer and having proper archival mechanisms.
- *Writing* : I am actually pretty bad at writing but the love for writing is so much in me that I totally consider it a strength. I am actively learning to write better.
- *Research* : I have never actually done any research for anyone else but I happen to figure out whatever I need, whenever I need it. I plan to have a more proper way of thinking about this so that I can do the same for others.
- *No knowledge, no worries* : If I am interested, even if I do not know anything about your domain or stack, I'll quickly pick things up and get myself upto speed so that I can compliment what I have to offer, but now specific to your domain.
** What I absolutely cannot contribute to
These are things I do not wish to delve into in near future, but might in the far future.
- If your project involves AI/ML. I probably would have no idea about how I can make any contribution to that area.
- If it involves hardcore embedded development and electronics. I probably would have no idea about it and would probably have somewhat of a hard time figuring things out.
** Interest Inventory
This body of interests also indicates a [[https://www.infraculture.org/2021-12-30-an-inventory-of-interests/][path of discovery]] which has been found and promises a lively time in the future. The things that I keep coming back to most of the time revolve around education, humor, social issues, climate issues, optimizing things for happiness and stability, making regular things suck a little less, things that need solving now, total re-thinking of how something is done. I have varying amount of knowledge in the areas and every experiment is a new learning opportunity. :)

#+attr_html: :class book-hint info
#+begin_quote
There is more to be done in the following up of these interests than can be accomplished in a lifetime. So I keep track of all [[file:projects.org::*Directory][my ideas in public]] and am open to collaborating with teams doing similar things. The internet is a serendipity machine and if sharing things publicly helps me find the right people to work with, it's a win. I like small teams who work on specific things to accomplish [[https://patrickcollison.com/fast][ambitious]] goals that work. If you or your team is working on anything related to the my interests and is looking for someone to collaborate with, I am very much willing to be an active participant.
#+end_quote

- *Local* : Projects related to Guwahati/neighboring places, which aim to make the city better in small ways. Also open for classes, workshops and other local events(doesn't necessarily have to be technical).
- *Data* : Data gathering, analysis and visualization. Specially geospatial, time-series and social data.
- *Writing, Archival and Curation* : Writing content specific to my interests, curating lists and libraries, for everything from independent curricula to businesses. Building proper archival and backup systems for the same.
- *Small Tech/Low tech/Small data/P2P* : Boring, small and offline first technologies and standards, I am interested both in the development of these standards and extending the usecases. Possibly, things where a person can easily fit everything about it in their head. I really like the [[https://indieweb.org/][indieweb]] and what the folks at [[https://small-tech.org/research-and-development/][small-tech]] are doing.
- *Cybernetics, creative tooling and communication* : I am interested in how we can help make our communications better using new mediums.
- *Consulting* : I love collaborating on fun, ambitious, random experiments on the internet and offline. I try to understand the experiment and then let you know how I can be helpful and then go ahead contribute to the areas I can contribute to.
- *Education* : I am a [[https://en.wikipedia.org/wiki/Aaron_Swartz#Open_Access][big proponent of open access]] to learning resources and an outright hater of the evil edtech giants and flop traditional institutions in India which manufacture depressed kids every year here in the country straightup leading to misery. I am willing to work on this area in all fronts, be it calling out bad actors, creating new information products, researching how we can learn better, experimenting with custom learning tools, campaigning, indexing research for other researchers, you name it. I have a lot of respect for [[https://www.khanacademy.org/][KhanAcademy]].
** Communication
I like interacting with people but I like it more when they get to the point right away. In other words, not a small talk enjoyer. I am a big fan of humor and total believer in being serious without a suit. So cut the formal shit, just get to the point, If there's something I can help you with, I will do everything in my ability to be helpful to you because I just want to be somewhere where I can help and my help is needed.

*** 101 ways of contacting me(ranked)
#+attr_html: :class book-hint warning
#+begin_quote

1. Twitter DMs
2. Sending me a collaborative document like google doc
3. Email
4. Other asynchronous instant messenger (Discord, Signal, Telegram, etc).
5. Video call (Scheduled) + A Document to discuss throughout the call
6. Video call (Scheduled)
- ...
7. [@99] Wake me up from my sleep and tell me about it
8. Morse code
9. A voice call on my phone

#+end_quote
*** Communication Style
- I have a problematic communication style where I simply do not respond to messages unless I have the answer or something that'll help get the answer. I am trying to improve on it. Please don't take it personal.
- If whatever you sent me made me feel overwhelmed in any way (happy/sad/confused), I'll let it sit with me for a while and only respond when I feel that I am ready to respond to it. This is in [[https://en.wikipedia.org/wiki/Value_pluralism][contrary]] to how much I enjoy fast feedback loops.

** Roads that lead to me
*** Handles
- Email: hrishikeshbman@gmail.com
- @geekodour (GitHub, Twitter, Matrix)
*** Security
- PGP and SSH
* Gandhi ₹
:PROPERTIES:
:EXPORT_FILE_NAME: gandhi
:EXPORT_HUGO_SECTION: docs/documents
:END:

file:cn.jpg

I don't care if this sounds stupid but look at the above image and just recall how insignificant we are. Humans created something called money and started valuing it, making it way of communication, creating economies around it, making it the way how research gets done, making it the driver of showbiz and what not. It really be just something humans believe in and built overlay products, instruments and theories on top. I don't think money is bad or anything, but like it's just as real as our imagination.

You can technically decide to not believe in god because you can exist without it as your life is not run by god. But if I live in this economy and tell I don't believe in money, I'll become what they call broke. Simply because money runs it. I already have this life that's mine and I constantly feel like the world is trying to sell my own life to me. My dog once ate a ₹2000 note and then started smiling at me.

But now I am addicted to it, I cannot go back to the jungle and become unalive the next day when the friendly noodleboi decides to kiss me. So it's apparent that I have to play the money game whether I like it or not. So, if I am going to play and I know there are no rules, I can decide how I want to play. I do not have to select a template, I can create customized gameplan that fits my needs. So that's what this page is about. It's not unique but it's custom, and boi do I love me some customizations. I have a feeling that after a while, I'll be like fuck this customization just give me a template, but at this moment and I am excited and [[https://www.youtube.com/watch?v=RLhuPD2ASKE][we roll]] till that happens.


** Why do this?
Discovering new ways to make money is fun, particularly when it comes to building sustainable revenue streams for creative work. There are few folks I found on the internet who create money in their own way and they seem to be really enjoying it (atleast from the outside). I might not have 1% of the talent as [[https://daniellebaskin.com/][this person]] but I really like what they do and how they be making money out of it, they basically sell products and experiences to people around the world, nothing too fancy but pretty cool.

If we talk about mantras and shit, I understand that marketing plays a huge role but I am slightly more inclined towards the just do good work and people will start noticing school of thought. One of the core ideas is that making money should be a side-effect of what I do.

So let's see how this goes, I am going to experiment this for the next 3-4 years and if nothing works out, I can confirm that I was a mega stupid(which I am) when I was 25.

** Economics
I have to study economics. I have 0 knowledge in the area but the way I am planning to work around this area is better described by Andy Matuschak in his homepage:
#+begin_quote
/My methods meander between academia and Silicon Valley: I explore theories by expressing them in real-world systems, which produce insights I use to improve the theories, which I use in turn to improve the systems, and so on./
#+end_quote
So once I have a better idea of the following and things start rolling, I'll extend this section with more formal details about how everything is working together.


Following are the hats/feathers/badges(🎩,🐦,📛) that I plan to work with. With a scattered brain and such optionality, I myself can see that is the perfect recipe for disaster but honestly do not have a lot to lose. On top of that I'll be extensively documenting everything so at the least a stupid case study will come out in the end. Funny thing is I have not started working on any of this, but I guess some planning was necessary If I plan on doing so many things, these things align with the [[*Masterplan/Roadmap/Goals][masterplan]].

- *Builder* : Build [[https://www.reddit.com/r/Artisan/][anything]] and try to monetize it if possible. This will probably be my primary source of income as of the moment. From what I see, it's not easy at all but should be worth it.
- *Independent researcher:* R&D on tools for thought and the Indian education system
- *Internet writer:* Writing regularly in areas of interest
- *Data journalist and Internet Detective:* Churning out data and presenting them in a more accessible manner if I come accross any such cases
- *Activist and Social worker:* Active Activist in areas I care about. I feel like Activism is effective in certain areas that I'll be working on but lot of it is done in in-effective ways or maybe too late or something. Also all humans should be social workers, like you're responsible for keeping your room clean, not sure why we made it a tag.
- *Business owner:* Not trying to be the cool entrepreneur here. Pure baniya style businesses just to undertand how things work around here. I think there's not too much risk in this.
- *Collaborations:* Collaborations are pretty cool way to make money I think, you meet new people, have fun and also make money in the end. I've written extensively about [[*Collaborate][how I want to collaborate here]].
- *Local information curation* : I do not know how I can describe this role well enough but it's basically collecting local and geographical data and making it useful for people who can benefit from it directly, now.
- *Occasional House cleaner:* I think cleaning is my true passion but apparently not a lot of money in cleaning. But I still can do it for relatives and friends.

Even though I am concern about making money here. I am ready to trade money with anything else which will help me reach my goals.

** Fund me
I will probably keep some fund me links here if I ever feel like the work I do is giving back or it is creating significant value. Till then here's my [[https://www.amazon.in/hz/wishlist/ls/H8N5KHWU23K3][Amazon wishlist]] if you're feeling generous.
** My donations
I am currently [[https://internetfreedom.in/][donating to the IFF]] and would urge you to donate as well. Other than that, most of my donations are ad hoc. Going forward, I would like to use this section to keep proper track of all of my donations.
** Resources
*** General Funding
- [[https://github.com/ralphtheninja/open-funding][ralphtheninja/open-funding]] : A guide for researching ways of funding
- [[https://github.com/jamesmunns/yogslaw][jamesmunns/yogslaw]] : An idea regarding non-commercial open source licensing
*** OpenSource Funding
- [[https://github.com/nayafia/lemonade-stand][nayafia/lemonade-stand]] : A handy guide to financial support for oss
- [[https://github.com/beeware/paying-the-piper][beeware/paying-the-piper]] : A project for discussing ways to fund oss
*** Grants
- [[https://github.com/nayafia/microgrants][nayafia/microgrants]] : A list of microgrant programs for your good ideas
- [[https://www.ogrants.org/grants-01-all.html][Grants (all) · Open Grants]]
*** Others/Random Ideas
- [[https://webmonetization.org/][Web Monetization]] : A JavaScript browser API that allows the creation of a payment stream from the user agent to the website
- [[https://ipaidthemost.com/][I Paid The Most]] : Stupid little site that lets people put money just to get their message out. Basically YT super-chat feature as a website.
* 🎄
:PROPERTIES:
:EXPORT_FILE_NAME: _index.md
:EXPORT_HUGO_SECTION: docs/updates
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 7
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookFlatSection true
:END:
* Monthly notes
:PROPERTIES:
:EXPORT_FILE_NAME: monthly_notes
:EXPORT_HUGO_SECTION: docs/updates
:END:
Extending the [[https://nintil.com/categories/links/][lists]] idea by nintil, I have decided to publish monthly summary of everything I did in that month. This will be useful for me in various ways because I have an extremely fragile memory and this should probably help me re-organize things better in my head also probably easier recall, who knows.

#+attr_html: :class book-hint info
#+begin_quote
It's just be a work of re-organizing and summarizing. Sources for summarizing are as follows:
- =org-journal= or travel entries for the month from [[https://diary.geekodour.org][diary.geekodour.org]]
- links that were finished/dropped from [[file:anti_lib.org::*Posts][anti-library]]
- look at all the commits done to [[https://mogoz.geekodour.org][mogoz]] for the month and summarize learnings
#+end_quote
* Library
:PROPERTIES:
:EXPORT_FILE_NAME: library
:EXPORT_HUGO_SECTION: docs/updates
:END:
Whenever I have to review something or take note about something that I am consuming from the [[file:anti_lib.org::*Posts][Anti-library]], those notes go in [[https://mogoz.geekodour.org][mogoz(my wiki)]]. Following are some selected pages from my wiki which should have relevant backlinks.
- Books
- Movies
- Series
- Music
- Posters
- Paintings

* Changelog
:PROPERTIES:
:EXPORT_FILE_NAME: changelog
:EXPORT_HUGO_SECTION: docs/updates
:END:
** June 2022
- 25th
  - Started working on the homepage
** July 2022
- 13th
  - Finished the structure of the homepage. Filling in manual contents
- 15th
  - I have to finish this homepage today no matter what.
* 🌴
:PROPERTIES:
:EXPORT_FILE_NAME: _index.md
:EXPORT_HUGO_SECTION: docs/tools
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 8
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookFlatSection true
:END:
* Gears
:PROPERTIES:
:EXPORT_FILE_NAME: gears
:EXPORT_HUGO_SECTION: docs/tools
:END:
** Who am I?
I am a developer with a wide variety of interests. I am trying to build a large volume of things and also get my fundamentals right. Unfortunately after all these years, I still am in the discovery phase and I guess that's alright.

I am trying to build a large volume of things not because I want to see what sticks on the wall but because I think that's a good way to discover and experiment in the respective domain and I get to have ton of fun along the way. I'll also be actively studying and researching these areas.

** Working Setup
#+attr_html: :class book-hint info
#+begin_quote
I am feeling particularly lazy as I write this. will come back later someday and fill things in.
#+end_quote

*** Hardware
My primary development machine is ThinkPad E480 with some customizations, I've been using it for the last 3 years without any hardware issues. Recently I built my PC and bought a monitor so that it increases my productivity. The monitor is definitely helping but I am not sure about the PC. I planned to game on it but have not started gaming yet.
*** Software
I use arch btw. See [[*Primary tool-chest][primary tool chest]] for list of packages.
*** Security
I carry a picture of a knife on my phone with me all the time. robbers be-aware. For password management, I used to use pass but then I switched to bitwarden. I am planning to move to selfhosted one soon. I need easy access to my password from my phone, atleast
at the moment.
*** Phone
I use an one plus 9. It's been a good phone to me so far. I'll probably fill more details later.
** Know more about my system
I run my systems, but i hardly have scrached the capabilities of my system, I shall dump relevant links which will help me undertand my systems better here. Make sure to clean up this list and summarize the learnings in some way.
- [[https://betterprogramming.pub/save-your-linux-machine-from-certain-death-24ced335d969][Save Your Linux Machine From Certain Death]]
- [[https://wiki.archlinux.org/title/improving_performance#RAM,_swap_and_OOM_handling][Improving performance - ArchWiki]]
- [[https://people.kernel.org/monsieuricon/what-does-a-pgp-signature-on-a-git-commit-prove][What does a PGP signature on a git commit prove?]]
- [[https://codeahoy.com/2017/01/20/hhtop-explained-visually/][htop Explained Visually | CodeAhoy]]
- [[https://robertodip.com/blog/managing-processes-with-htop/][Managing processes with htop]]
- [[https://peteris.rocks/blog/htop/][htop explained | peteris.rocks]]
- [[https://ablagoev.github.io/linux/adventures/commands/2017/02/19/adventures-in-usr-bin.html][Adventures in /usr/bin and the likes]]
- [[https://utcc.utoronto.ca/~cks/space/blog/unix/FindWithoutXargsToday][Chris's Wiki - blog/unix/FindWithoutXargsToday]]
* Primary tool-chest
:PROPERTIES:
:EXPORT_FILE_NAME: primary_toolchest
:EXPORT_HUGO_SECTION: docs/tools
:EXPORT_HTML_CONTAINER: div
:EXPORT_HTML_CONTAINER_CLASS: smol-table
:END:
** Arch Linux
These lists are generated but I update them to my website manually, so what's there on the website might not resemble what's on my system.
#+attr_html: :class book-hint danger
#+begin_quote
Also is this a security risk that I am publishing these publicly? I guess not if I manually verify shit. I'll get this confirmed anyway.
#+end_quote

*** Official Packages
| Name | Description |
#+INCLUDE: ~/projects/systemfiles/official_packages.org
*** AUR Packages
| Name | Description |
#+INCLUDE: ~/projects/systemfiles/aur_packages.org
* Home
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SECTION: /
:END:

file:homepage_poster.png
welcome to my homepage, it's mostly मानसिक मूठ siphoned into your brain. Nothing much to say, my name is /jellyfish brained certified cloudhead skinny ol' barman junior the creator of garbage III/. I am pretty friendly, I love nature and I like to simply exist, I happen to do okay things with the computah, also I speak and write broken english.

I've written extensively about why this homepage exists in the [[*Colophon][colophon]] section. If you're interested in ruining your good times, check the [[*Collaborate][collaborate]] section.
