#+hugo_section: personal_lists

* Values
:PROPERTIES:
:EXPORT_FILE_NAME: values
:END:

This list came out of a mental exercise with myself, in which i tried to look inside and list things that sort of shape me. Some of the items might seem out of place, i need to come back to this and re-think what the hell does this bullshit even mean to me.

- Candor
- Empathy
- Humor
- Stupid Optimism
- Rigor
- Friendships
- Taking ownership
- Family
- Learning
- Education should be free
- Generate money from giving experiences/pleasure and enhancing productivity/lifestyle but education should not be dealt with money atleast to the students who cannot pay enough
- Being smart
- Being kind
- Decisions are everything
- Building things
- Hypocrisy
- Doing the right thing
- Be open to change my mind if required

* Beliefs
:PROPERTIES:
:EXPORT_FILE_NAME: beliefs
:END:
I was inspired by [[https://busterbenson.com/beliefs/][Buster Benson]] and decided that i need a page where I can openly state my views on things that are external to me. Basically opinions masqueraded as beliefs.

** Writing
- small case writing is so so much more superior than anything else out there also no punctuation is just cherry on top plus making spelling mistakes and not deciding to correct deserves a chefs kiss we only use lower case cuz fuck capitalism
** Education
- we educate for two things, to take the human race forward in the right direction, so that one can live their life to their fullest
** Text editors
- emacs is goku

* Won't Do
:PROPERTIES:
:EXPORT_FILE_NAME: wontdo
:END:
Things that i'll never ever ever ever attempt in this lifetime.
- drink more than 400ml of neat at once
- kiss in an uber
- get a dog when i don't have the capacity to train her properly

* Would do again
:PROPERTIES:
:EXPORT_FILE_NAME: woulddo
:END:
- river rafting
- visit shillong, i never get tired of shillong

* Lies
:PROPERTIES:
:EXPORT_FILE_NAME: lies
:END:
- that i have time, that i know things when i don't
- that i am a good person, i am not, i am a terrible person

* Can speak on
:PROPERTIES:
:EXPORT_FILE_NAME: can_speak_on
:END:
Things that I can talk about for 30mins straight, without prep:

- Bitch about my engineering college

* Angels
:PROPERTIES:
:EXPORT_FILE_NAME: angels
:END:
I've walked the earth and after I die, people will still be able to access this page(hopefully). These are the people(*unordered*) who made the most direct positive impact in my silly little worthless life. This list is surely not exhaustive. I am thankful to everyone except the terrible ones.

I wanted to write about each of them here briefly but it might not be the best thing to do on the internet.

- Baba dada
- Babuli dada
- Tina, Tuku, Sumu
- Mom, dad and youngest sister
- Debanga
- Vishal
- Rajendra Sir
- Nina Sharma Maam
- Junmun Sir
- Simanta
- Jugal
- Abhilash
- Naval
- Nipam
- Enid Blyton
- Prachi
- Harshit
- Aaron Swartz
- Atibhi
- Rubu
- Rishi
- Noam Chomsky
- Puberun
- Zenith Hostel Boys
- Natasha
- Ronjoy
- Joyraj
- Gobin Mahanta Sir
- Krishnasish Da
- Mriyam Da
- Shyamal
- Amartya
- Ganesh
- Srijan
- Udipta
- Monsoon
- Samhita
- Khan Sir
- Indrajeet
- Devika
- Avinash
- Agnim
- Corona
- Ishani
- Anubhav
- Tasdik
- Neel
- Pritam
- Stella

* Wrong Deals
:PROPERTIES:
:EXPORT_FILE_NAME: wrong_deals
:END:
- 1996: I did not ask to be born. I exist without my consent.
- 2007: For some reason, I trusted bharat da at rajdhani internet cafe who told me to give up programming and study networking because programming got no jobs. I would probably be a totally different person today if I didn't listen to him. But I guess, it's cool. I had fun along the way. But yeah, this was definitely a wrong deal.
- 2015: Joining GIMT(my engineering college) was the worst fucking decision of my entire life. I finally ended up dropping out of college in the final year because I had too many backlogs and I could not take the daily bullshit the college was throwing at me. Ask me to bitch about my college if you meet me IRL ever( I need to be 2 beer down ).

* Don't like it
:PROPERTIES:
:EXPORT_FILE_NAME: dontlikeit
:END:
- When someone repeats something that I understood thinking I was not listening. don't like it.
- When someone just randomly calls me dump their trivial misery. don't like it.
- When people ghost me. don't like it.
- I take my time. When someone(unrelated to the work) think I am being lazy when I am taking my time. don't like it.
- Raw tomato. don't like it.
* My delusions
:PROPERTIES:
:EXPORT_FILE_NAME: mydelusions
:END:
- I think people are suffering, maybe things are not so bad. Think I need to get some reality check around this. There are books around this that I need to read too.
- I think there are more stupid people than smart people. I am not sure about this because it's contexual but seems like it.
* What if
:PROPERTIES:
:EXPORT_FILE_NAME: whatif
:END:
Writing prompts.
** What if dogs could talk?
This would be very nice because this will mean that choco(my dog) would start speaking and understanding. Then she'll actually undertstand that I am calling her a monkey.
** What if humans could fly?
World hunger solved man. Mlon Eusk should just work on building wings for humans instead of trying to buy a bird house.
* Predictions
:PROPERTIES:
:EXPORT_FILE_NAME: predictions
:END:
🔮 Predictions/Hopes/Gut
- [ ] I'll die by 30 (Either full broke or a millionaire)
- [ ] Vishal will be getting married first among us
- [ ] Guwahati will still be unbearable to live during summers in 2030
- [ ] There will be a cousins day out someday which will fix lot of my family trauma
* Communities
:PROPERTIES:
:EXPORT_FILE_NAME: communities
:END:
This involves both offline and online community.

** I was part of
*** Offline
- School and Tuition folks
- Gauhati Artists' Guild
- Bamunimaidan Drama School
- Oil India badminton gang
- Okonir naamghar (Khol classes)
- Developers from Guwahati
- Artists/Photographers/Videographers from Guwahati
- Very small set of startup founders from Guwahati (idk man most of them are like idk doing shit that i don't really like but good for them)
- College kids (did not like my time here at all)
- Clarisights people
*** Online
- Few cool but niche twitter people from Bangalore and Delhi i guess
- Indian hackathon(esp devfolio folks) and the opensource community
- Prometheus people
** I want to be part of
These are communities/micro communities that I wish to explore and be a part of.
*** Indie Developers
These are people who call themselves builders. They build businesses, some build for fun. The community primarily revolves around how we can monzonite our side projects and such. Some examples that I can recall, [[https://getmakerlog.com/][Makerlog]], [[https://barnacl.es/][Barnacles,]] [[https://www.indiehackers.com/][Indie Hackers]]
*** Gamers
I didn't play a proper game since 2010. Been almost 12 years now. I loved to play games. I now have a desktop which can run most latest games, think I'll start gaming again and join the gaming people I know. They're very nice people.
*** Rationality folks
Some places I think which can be good starting points: [[https://www.gwern.net/][Gwern]], [[https://old.reddit.com/r/slatestarcodex/][Slate Star Codex]], [[https://www.lesswrong.com/about][LessWrong]]
*** Twitter
I have been using twitter for many years, but never been a power user. Think as I am already using it, better use it properly and make more nice friends. Some resources which might help me up my game: [[https://tasshin.com/blog/a-guide-to-twitter/][A Guide to Twitter]] , [[https://github.com/igorbrigadir/twitter-advanced-search][Advanced Search for Twitter]]
*** Reddit
If I had to list which websites changed my life in big ways, it has to be Google and Reddit. To me, Reddit is like the ISS of the internet. I always leave the site impressed, depressed or amused. At-least it makes me feel real things. I've been a lurker though, want to be more active there eventually.
*** StackExchange
Stack Exchange is a network of question-and-answer websites on topics in diverse fields, each site covering a specific topic. Developers usually hang around stackoverflow but the other communities are also pretty awesome in my experience. Here are a few that I might just want to hang around: [[https://serverfault.com/][Server Fault]], [[https://dba.stackexchange.com/][Database Administrators SE]], [[https://crypto.stackexchange.com/][Cryptography SE]], [[https://security.stackexchange.com/][Information Security SE]], [[https://networkengineering.stackexchange.com/][Network Engineering SE]], [[https://electronics.stackexchange.com/][Electrical Engineering SE]], [[https://raspberrypi.stackexchange.com/][Raspberry Pi SE]], [[https://cs.stackexchange.com/][Computer Science SE]], [[https://unix.stackexchange.com/][Unix & Linux SE]], [[https://math.stackexchange.com/][Mathematics SE]], [[https://physics.stackexchange.com/][Physics SE]]
*** Guwahati Art and Design community
Think these bunch are onto something. Pretty cool stuff.
** Resources
Resources related to community building and communities in general.
- [[https://www.visakanv.com/blog/communities/][🤝 how to build and maintain communities]]
- [[https://knowingless.com/2016/08/21/strange-subculture-list/][Strange Subculture List]]
- [[https://github.com/orbit-love/orbit-model][orbit-model]]

* Apologies
:PROPERTIES:
:EXPORT_FILE_NAME: apologies
:END:
- I apologize for all the memes I have stolen and also for all the memes I am going to steal in the future.
- I apologize to all the people I have ghosted, in my defense I have been ghosted 3x so this is reactionary man. 😢
- I sometimes steal writing snippets and do not give credit. I mean idk. Eg things like I probably stole this very line from somewhere, how am I supposed to give credit to this line. Whole document will be full of footnotes otherwise.
- I am very werid in person, sometimes I'll speak non-stop, sometimes I'll just sit like a ghost. If I ever creeped you out just by existing, I am sorry about it.
* sElF hElP
:PROPERTIES:
:EXPORT_FILE_NAME: self_help
:END:
- [[https://kk.org/thetechnium/68-bits-of-unsolicited-advice/][The Technium: 68 Bits of Unsolicited Advice]]
- [[https://techcrunch.com/2013/10/19/the-ultimate-cheat-sheet-for-reinventing-yourself/][The Ultimate Cheat Sheet For Reinventing Yourself]]
* Jargonfile
:PROPERTIES:
:EXPORT_FILE_NAME: jargon
:END:
** Jargons
This is a growing list of words that I came across and I thought to myself, I'll probably forget about this but it's nice, better keep a note somewhere. This list is domain agnostic.

- *Slashdot effect*: Also known as slashdotting, occurs when a popular website links to a smaller website, causing a massive increase in traffic.
- *HugOps*: It is a way to celebrate the human, empathetic side of building, shipping, and running software.
- *Watchdog timer* : Used in Mars Exploration Rover (MER) 🚀 See also Dead man's switch.
- *Unsolicited daemon* : A daemon process that sleeping for a long time, legends say it can sometime have 0 RES memory.
- *opcode* : abbreviated from operation code, it is basically the portion of a machine language instruction that specifies the operation to be performed. Apart from ISAs, bytecode specifications also use opcodes.
- *exploratory programming* : programming that is not actually solving a problem but primarily aims at finding how things are working, btw the name is self explanatory ;)
- *tarpits* : a network service that intentionally inserts delays in its protocol, slowing down clients by forcing them to wait.
** Neologisms
A [[https://maggieappleton.com/neologisms][collection]] of interesting words that have recently been coined. In my case, this is just to keep up with gen-z folks.
- *Link* : To connect with friends or people in person and chill.
** Other lists
- [[https://en.wikipedia.org/wiki/Category:Network_software_stubs][Network software stubs]]
- [[https://en.wikipedia.org/wiki/Category:Computer_storage_stubs][Computer storage stubs]]
- [[https://en.wikipedia.org/wiki/Category:Computer_humor][Computer humor]]
- [[https://en.wikipedia.org/wiki/Category:Mathematical_humor][Mathematical humor]]
- [[https://en.wikipedia.org/wiki/List_of_mathematical_jargon][Mathematical jargon]]
- [[https://en.wikipedia.org/wiki/Glossary_of_computer_hardware_terms][Glossary of computer hardware terms]]

* Thankful
:PROPERTIES:
:EXPORT_FILE_NAME: thankful
:END:
I do not know how to be grateful. But I try. This page is to dedicated my thanks to all the people and things I am thankful for. This list is obviously not exhaustive. I think there are tools with which you can generate a thankyou page depending on your dependencies etc. but I rather just keep it personal so yeah, this will be very incomplete but like cannot thank people enough, that's what.

- I am thankful to whoever in Nepal came up with the recipe of momo. It made living worthwhile for me.
- I am thankful to my friends for taking all of my shit. I don't know what I would do without them honestly.
* Conversations dump
:PROPERTIES:
:EXPORT_FILE_NAME: conv_dump
:END:
These are dumps from my phone notes, some of these came up during conversations, self talk, reading something online etc. This is absolute horseshit btw, I am keeping these for historical reasons and now that i had a look at these, i cringed by a lot and also moved by head left and right in disagreement with myself. These are historical, newer thoughts go into org-journal and it's not public for private reasons.

** Probably selftalk
- Learning something strange requires reassembling of our brain. I like it. I want to do that often.
- It's this process of getting out of this mess that i'll appreciate and not the life i'll live after.
- i tweet when i feel things. it's a good day when i am tweeting often ig.
- comfort is a cage, do hard things.
- I am and & will not stop. - idk what i mean
- you study all this to become someone you do not want to become just so that you can make some money. once you make dem monie, you're allowed to do what you want. people can't take creative risks here.
- I just want to be a programmer who is comfortable calling himself a programmer
- on inventing: There's a lot of knowledge in other people's head, you can come up with your own knowledge. Lot of knowledge is out there floating in other people's head they did never pay enough attention to that floating thought. Sometimes someone pays extra attention to the thought and tries to formalize it and then that person becomes an inventor, or like the coiner of the term or something
- You know you're working on the edge when you don't have a book for what you're reading. You need to read academic papers etc.
- When trying to learn something it's good to see what space it fits in, see what alternatives it has; what set of problems is it solving. googling alternatives; another nice trick is to look at the category section in wikipedia to see what category of things it falls into even though it's not always 100% accurate.
- I don't want to build companies, I want to build standards, but currently I don't have the skills.
- Time has the ability to make things less valuable, what do we need to make things resistant against it?
- Because the hardware of our brain is not good enough, we need to develop algorithms that suit our mind to understand the world. Some people understand things easily because they have better brains, we can do similar stuff but we need algorithms that fit with our brain and only we can do that to ourselves.
- I am 23, I sometimes wish I was this curious when I was 13. It's okay, you can just reset. You are better equipped now, maybe you can do the things 13yo Hrishi could do twice as fast. You just need to start. You'll age anyway.
- took me a lot of balls to admit that i know nothing about maths at 23 and start doing 6th grade math. - same at 25 lol
- When we try to make a language good the popularity usually lies on the things that were built and then programming language like Erlang by design is very good and stuff but it can be popular because of the things that were built with it similarly if we want to make SMS popular so we have to build more beautiful things with SMS so if you write great books get poetry so the applications of that language should be popular so then eventually the language would become popular
- I think programming is a creative endeavour and I like to put creative people into two buckets, performers and practitioners but usually in my observation people are of the mixed kind.
  - Performers: When practicing these people train their mind and body to perfect components of their art and when performing they let whatever they learned flow through their mind and body and be present in the moment.
  - Practitioners: These people are sort of always working and do not have a stage to perform. They know their art and keep on improving their art as they work their art. Doctors or programmers might seem to fit in as practitioners but they are also performers when it comes to taking the right decision at the right time, coming up with a bright new idea etc. I want to be both but currently none at all. I can’t code properly and i take stupid decisions, all my decisions are simply intuitions.
- Gaming ping and relation to future: We can simulate future by sending information slower to some user. Future is just unavailability of information in the present. Information here is not just  the knowledge but the happening. Eg. If you have faster connection, you have access to the future.
- If you're not sure whether what you're doing is ethical or not, it's better to not do it. imo.
- does the definition of edge computing include our brains?
- I am deeply troubled. I am stuck in 17yo me when i am 24. I still want the same things, I still have the same dreams. It's not good. I don't like who I am. I have to come out of my body look at myself change myself.
- Using curiosity to learn, see what's happening in the real world in every subject and then reverse engineer from that.
- Me apna privilege bech dega bhenchod. How to sell your privilege.
- The input bandwidth is good, we can take input. But output has to be in some expressive way, talk, draw, act, write etc.
- So form tomorrow and till the day i die, i'll play my cards right no matter what. It's a game and i am here to win and help win.
- I would like to share five stupid realizations (about sorting life):
  - We are on our own journey and comparing with anyone is a complete waste of time. We need to define what sorting our life really meant to us and it's completely okay if that makes zero sense to other people.
  - Understanding the role of luck and how it compliments hard work.
  - Understanding momentum. We need to conserve momentum at all costs. fewer cold starts makes our lives easier. Also easier said than done. How your yoga streak broke.
  - No matter what we do, we should be having fun.
  - talk to stella (very important)
- I am 24, I should already have started on my mission. It's not late but will be late if i start 2-3 years later. It's time.
- If you can't use that knowledge, bro what is the use of that knowledge
- a museum, a library and a education research lab
- It haunts me everyday that i cannot be a computer scientist. It'll merely be a developer no matter how much I try.
- It's nature of life that people will dislike you for no reason. People will tend to express some affection towards you and suddenly they will be completely opposite. There might be no reason for such actions. It's the rules of the games. It's a game you play even if you know you will loose.
- Become very true to yourself, write who you think you are, that you're a dumb person with this and this disability, you don't know this and these things you want to do this and this. Basically, write the truth about who i really am. And what is my perspective on life and how i want to live it.
- I like science and history because they help me answer my questions. I want to love and study more maths because It has so many more interesting answers.
- Humans think very hard to understand their world and by understanding it they are able to represent their views in different forms such as maths. which helps in development of new worlds. Eg. calculus came from observing the world and from someone's mind. then calculus was used to create new things which birthed a new world. It's crazy. - Again, no idea what I am talking about.
- You can only thrive if the environment around you thrives. Applies at personal level too. You need to have control over you aswell as your environment. If the environment around you is instable, you won't be able to be in a stable state for long.
- We humans and like any other animals don't actually understand language. We just get better at identifying sounds. We(animals) communicate with our senses, seeing, tasting, hearing/speaking etc. The fact that animals can communicate with humans without sharing or learning a special language that both of us know points to something else. Plants on the other hand (if they can't hear) they communicate using light, they sense the sunlight. Sunlight becomes a way to indicate them something. (or no?)
- Sometimes i feel physical pain on things that happen in my dream , if someone kicks me in my dream. I mean i don't feel any pain after i wakeup but i am in pain in my dream so a lot of the physical things that humans experience are also mental. (simulation?)
- human-computer interface → dream computer interface.
- Even if some human understands a language, he might not understand what's being communicated. Even after having a rational mind, he/she is not able to understand what's being communicated despite being able to understand the language. (Me reading a book on quantum computing). - Obvious but I don't know why i felt the need to put this down.
- History is a data structure that you can use inside you mind to store information about the world. It's a index. The chaos of information becomes better organized if you learn history.
- Wrong mentoring worse than no mentoring
- Of all things one should be able to create happiness for themselves.
- My first job made me hate my entire profession (no hate towards my employer, i was fucked up)
- I am loosing hope in myself. I think this is the very moment i am getting myself into depression or whatever. But i am going to fight it and remember why i am doing all this for. - dec28’21
- Work ethic means you can get up to 1 from 0 if it happens, keeping notes means that you can get to 1 from 0 even quicker.
- froken bamilies suck so mucking fuch
- If you can ignore the opinion of other people and let them live in peace with their opinions, you can do the same to the opinions that involve you. When you can ignore other people's opinion about you then you truly reach the idgaf attitude which is essential for you to become dangerous.
- As humans, we are manually building our software for our brain rather than using a package manager
- To be able to draw and color whatever came to my dream
- One can spend a lot of time misusing the building blocks if one doesn’t understand them properly.
- Setting myself in foot of the 15y/o me as a 23 y/o guy. reap the benefits of maturity, judgment with curiosity.
- Sometimes we have to go away from our goal to reach our goal?
- The goal is to find the goal
- Learning from the past was helpful for me because I was good at few things back then which i am not good at now. so when you're good at something make notes so that you can learn from yourself later on in life.
- Mindset
  - Rather than having a recipe, have a mindset.
  - Mindset is a enabler or blocker to learning something.
  - Just givinG inspiration about why you should learn something does not form the mindset needed.
- there's a lot of info out there, but how much of it is relevant?
- I've something to prove, that kids from small villages can do a lot if they are taught the right way. Not giving them the right education and opportunity is discrimination. Internet scales by design, we just have to teach them how to use the internet and possibilities are endless.
- You don't need such strong note taking measures if you don't jump around a lot. But if you do, like me jump around so many areas at the same time. Notetaking becomes v.essential. Eg. if you just work on database you still need notes but since most of the time things will be the same the environment you work with will be your note but for someone who wants the same but also wants to hop into other ideas, need to take notes which is slow and tedious but works imo. - I absolutely have no fucking clue what i am talking about here.
- At every point in time, I make a choice. It's all about making the correct choice. We need to speed up this choice step at the same time make it more accurate. So that we can make all the choices the best and move fast. What will be the correct choice? Future has the answer, look deep into the future.
  - Contradictory, "Life isn't about getting forecasts "right"; it is about navigating the environment and controlling it." i.e if you cannot control a complex environment (x), then control your exposure to it [f(x)].
** Probably conversations with others
- The whole future lies in uncertainity, live immediately
- find something that is enjoyable to you and valuable to others
- the part of life we really live is small, all the rest of it is not life, but merely time
- We think our opinions are formed through thought and marshaling of facts and evidence. But in reality, most are formed emotionally and then covered over with a thin veneer of "facts" and "evidence."
- "A human being should be able to change a diaper, plan an invasion, butcher a hog, conn a ship, design a building, write a sonnet, balance accounts, build a wall, set a bone, comfort the dying, take orders, give orders, cooperate, act alone, solve equations, analyze a new problem, pitch manure, program a computer, cook a tasty meal, fight efficiently, die gallantly. Specialization is for insects.
- When two people fall in love, their rational thinking decrease and they become stupid but it feels good
- once you realize that in any given context, you've got a finite amount of influence you can exert on your surroundings. Picture a sports coach who's been yelling at his team for so long, the message falls on deaf ears. Leverage other voices (if the advice is good).
- Your values and your emotions is your political opinion.
- you need to be thinking relative to a problem, you need to have a constraint which you can optimize for, and this tells you what it means to have a right or wrong answer to a question." — Situating LessWrong in contemporary philosophy: An interview with Jon Livengood
- i love the smell of coredumps in the morning
- the score takes care of itself if everyone in the organization does their work precisely and accurately and is done consistently. This was jeff Bezos's way of measuring inputs.
- Behaviors that are rewarded in the zoo are suicidal in the jungle.
- Just like food should be the last thing to cut off because of cost. You might not go watch that avengers movie than to have subpar food. Similarly, the education budget is the last thing to do the cut off in, for the funding body.
- life mast nahi, thik chal rahi hai
- The reason silicon valley was sillicon valley because hardware people and software people were complimenting each other to improve the ecosystem.
- science is the negotiation between our noisy representation and what's actually out there
- A penny saved is a penny earned.
- Flatmate type family bur
- I didn't read books for quite a long time because I thought books will change how I think because I was not ready to think for myself, this helped me form my own view about the world before I started believing on random stuff. i am way too much still the kid who coasted through school on raw intelligence to do things using routine and habit, and i have tried (and failed)
- Training conflict affected youth to become technology leaders
- If you want success, figure out the price, then pay it
- Unless you pick your battles consciously, battles will pick you. And pretty soon, you’d find yourself fuming about why you’re not winning.
- Why make the same mistakes others have made and written about?
- ultimate hack that you can learn things by reading
- people contain multitudes
- worst day of fishing better than best day at work
- One unfortunate thing about writing is that you don’t know whether it has become clearer by the virtue of the writing itself or by having read the thing a hundred times during the edit
