#+HUGO_SECTION: docs/tools
#+HTML_CONTAINER: div
#+HTML_CONTAINER_CLASS: smol-table
#+TITLE: Secondary tool-chest

#+attr_html: :class book-hint info small-text
#+begin_quote
I have this habit of bookmarking different projects/tools/libraries, it has become problematic lately. I can do weekly or monthly review on my bookmarks but if my bookmarks are scattered all over the place, then it's additional work. **So the best way to tag this is tag at source/entry**

#+end_quote

There are similar lists on the internet:
- [[https://github.com/everestpipkin/tools-list][GitHub - everestpipkin/tools-list]]: Open source, experimental, and tiny tools roundup
- [[https://github.com/soruly/awesome-acg][GitHub - soruly/awesome-acg]]: A curated list of awesome technologies related to Anime, Comic and Games
Frontend
- [[https://github.com/sw-yx/spark-joy][sw-yx/spark-joy]]: 2000+ ways to add design flair, user delight, and whimsy to your product.
- [[https://github.com/matt-auckland/retro-css][matt-auckland/retro-css: A list of retro-inspired CSS frameworks]]
- [[https://github.com/ipython/xkcd-font][GitHub - ipython/xkcd-font: The xkcd font]]
- [[https://github.com/boringdesigners/boring-avatars][GitHub - boringdesigners/boring-avatars]]

#+attr_html: :class book-hint danger small-text
#+begin_quote
The ideal state of this list should be empty. But my current bookmark backlog is huge. I bookmark things either because I want to use it directly somewhere or I like some aspect of the project.

This list is semi-generated as I maintain this tool list on [[https://airtable.com/][airtable]], which allows me to easily comb through whichever tool I need. It took me 2 days to manually tag and categorize 1000+ tools but it's worth it imo. Now when I make new entries, I directly tag/categorize at entry on airtable. When the script runs it automatically generates this nicely formatted list for public viewing here.
#+end_quote
#+INCLUDE: ../assets/org-includes/toolchest.org
