* General Development Tooling
Now how I do development has varied over the years. But I am constantly updating it. This section is a scratchpad area for links/notes about current or probable future workflow.

I am planning to checkout online sandboxes for development(candidates: [[https://codesandbox.io/s/][CodeSandbox]], [[https://stackblitz.com/][StackBlitz]], [[https://replit.com/][Replit]], [[https://glitch.com/][Glitch]]) as well try [[https://lobste.rs/s/dfmiko/using_github_copilot_for_unit_testing][using AI tools]] for development. Also I use [[https://github1s.com/][GitHub1s]] to check source code on github, pretty neat stuff.
* Data Engineering
Generally I have to fiddle with the data before I even realize what approach to take. Recently came across [[https://github.com/centerofci/mathesar][mathesar]], want to try it out for quick prototyping.
* Data Analysis/Viz
Doing this stuff manually is fun but ton of tools to make things fast for me. It only makes sense to make use of these tools.
* Infrastructure Management
I haven't fiddled with infra stuff in a while but it's always a combination of so many things. Shell scripts, custom programs, infra tools, external tools and so on. I plan to streamline this process eventually.
* General Python Development
I like python. Makes it super easy to prototype things esp data related projects. I try not to delve too much into the ecosystem of tools here and try to use tools that just do the job and get out of my way. Understanding how python's import system works is a big one.
* General Web Development
I want to move more towards web engineering vs the common idea of web development, I think it's more fun for me. Steering the wheel in that direction.
* Pure Frontend Development
I don't do frontend development often but when I do I always find myself fighting with CSS the most. I am totally in for complex(rather simple) javascript application or any webstack for that matter but I would love to stay away from CSS as much as possible. I think TailwindCSS really saved my ass here. I wants to do creative programming but I needs a mix of things. I will focus on it someday but not yet.
* Network Troubleshooting
Nothing is more annoying that getting disconnected. Even if I can't fix it I need to know what's up.
* Planning/Brainstorming/Curation
Planning things and getting ideas is important for me before I start anything. I do not have any specific workflow as such but I make sure to think what will be the best way to think about this problem before I start thinking about the problem itself.
* Communication and Discussions
Asking the [[http://www.catb.org/esr/faqs/smart-questions.html][right questions]] is important. Having casual discussions is also important. I have so much problem communicating with other people idk where do I even start.

* Art/Design
I wants to do art/design but not at the moment. I also wanted to make weird game videos using assets etc. But I might have to pause that for a while as it does not directly feed into my primary goals but I definitely want to make time for it.
* AI/ML experiments
I absolutely know nothing of AI/ML but want to get into it. I also have a syllabus made for math and AI studies. Meanwhile I want to experiment with
[[https://huggingface.co/][Hugging Face]], [[https://github.com/jerryjliu/gpt_index][jerryjliu/gpt_index]], [[https://github.com/hwchase17/langchain][hwchase17/langchain]], OpenAI stuff
* Conversion/transformation
Converting stuff from one format to another is all we do.
